### ISSUE TITLE
cores on rtpengine 7.5.4

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#1062]
hello all

after https://github.com/sipwise/rtpengine/issues/1031 we moved from 7.5.3 to 7.5.4 and systems were stable for several weeks but i saw 2 cores in the 2 systems we have running with the version
Version: 7.5.4.2+0~mr7.5.4.2
commit a8bcb37322e29f93cfdb8e32f6d7d5885240efbc

i attach the 2 backtraces
One seems related to g729lib and the other with malloc

```
#0  0x00007f38e1877279 in malloc_consolidate (av=av@entry=0x7f38a4000020) at malloc.c:4213
#1  0x00007f38e1878dfa in _int_malloc (av=av@entry=0x7f38a4000020, bytes=bytes@entry=8192) at malloc.c:3488
#2  0x00007f38e187b9b6 in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3274
#3  0x00007f38e186f7c3 in __GI___open_memstream (bufloc=bufloc@entry=0x7f38b67eab20, sizeloc=sizeloc@entry=0x7f38b67eab28) at memstream.c:83
#4  0x00007f38e18e3d31 in __GI___vsyslog_chk (pri=190, flag=flag@entry=1, fmt=fmt@entry=0x55902cfab15f "%s: %s%s%.*s", ap=ap@entry=0x7f38b67eabf0) at ../misc/syslog.c:167
#5  0x000055902cf9658a in vsyslog (__ap=0x7f38b67eabf0, __fmt=0x55902cfab15f "%s: %s%s%.*s", __pri=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/syslog.h:47
#6  0x000055902cf9658a in log_both (facility_priority=<optimized out>, format=0x55902cfab15f "%s: %s%s%.*s") at loglib.c:118
#7  0x000055902cf96811 in __vpilog (prio=prio@entry=6, prefix=prefix@entry=0x7f38b67ead80 "[9f133a5d-b03d-475a-a8da-23670e13c88d]: ", fmt=fmt@entry=0x55902cfa1b00 "Received command '%.*s' from %s", ap=ap@entry=0x7f38b67ead68)
    at loglib.c:194
#8  0x000055902cf7a456 in __ilog (prio=prio@entry=6, fmt=fmt@entry=0x55902cfa1b00 "Received command '%.*s' from %s") at log.c:106
#9  0x000055902cf6524f in control_ng_incoming (obj=0x55902db5c170, buf=<optimized out>, sin=0x7f38b67eb150, addr=0x7f38b67eb170 "79.170.64.140:46827", ul=0x55902db5c208) at control_ng.strhash.c:329
#10 0x000055902cf64022 in udp_listener_incoming (fd=<optimized out>, p=0x55902db55560, x=<optimized out>) at udp_listener.c:54
#11 0x000055902cf515b0 in poller_poll (p=p@entry=0x55902db541c0, timeout=timeout@entry=100) at poller.c:351
#12 0x000055902cf5194d in poller_loop (d=0x55902db541c0) at poller.c:508
#13 0x000055902cf51a69 in thread_detach_func (d=0x55902db37360) at aux.c:207
#14 0x00007f38e1daa4a4 in start_thread (arg=0x7f38b67fc700) at pthread_create.c:456
#15 0x00007f38e18e8d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

[bt_full_mad_7.5.4_August10.log](https://github.com/sipwise/rtpengine/files/5082354/bt_full_mad_7.5.4_August10.log)

```
#0  0x00007fed8dc8114e in LP2LSPConversion () at /usr/lib/x86_64-linux-gnu/libbcg729.so.0
#1  0x00007fed8dc7e491 in bcg729Encoder () at /usr/lib/x86_64-linux-gnu/libbcg729.so.0
#2  0x000055de394f7178 in bcg729_encoder_input (enc=0x7fecf4010c10, frame=0x7fed6cff5bc8) at codeclib.c:1808
#3  0x000055de394f8136 in encoder_input_data (enc=enc@entry=0x7fecf4010c10, frame=<optimized out>, callback=callback@entry=0x55de394e9eb0 <__packet_encoded>, u1=u1@entry=0x7fed502312e0, u2=u2@entry=0x7fed6cff5e88)
    at codeclib.c:1232
#4  0x000055de394f820d in encoder_fifo_flush (u2=<optimized out>, u1=<optimized out>, callback=<optimized out>, enc=<optimized out>) at codeclib.c:1266
#5  0x000055de394f820d in encoder_input_fifo (enc=0x7fecf4010c10, frame=frame@entry=0x7fed402c8820, callback=callback@entry=0x55de394e9eb0 <__packet_encoded>, u1=u1@entry=0x7fed502312e0, u2=u2@entry=0x7fed6cff5e88)
    at codeclib.c:1280
#6  0x000055de394eb918 in __packet_decoded (decoder=<optimized out>, frame=<optimized out>, u1=<optimized out>, u2=0x7fed6cff5e88) at codec.c:1452
#7  0x000055de394f76bb in decoder_input_data (dec=0x7fed4836ef00, data=<optimized out>, ts=<optimized out>, callback=callback@entry=0x55de394eb780 <__packet_decoded>, u1=0x7fed502312e0, u2=u2@entry=0x7fed6cff5e88)
    at codeclib.c:711
#8  0x000055de394e9a87 in packet_decode (ch=<optimized out>, packet=<optimized out>, mp=0x7fed6cff5e88) at codec.c:1466
#9  0x000055de394eb255 in __handler_func_sequencer (mp=0x7fed6cff5e88, packet=0x7feccc0182d0) at codec.c:831
#10 0x000055de394e1b6e in stream_packet (phc=0x7fed6cff5e30) at media_socket.c:1804
#11 0x000055de394e1b6e in stream_fd_readable (fd=<optimized out>, p=0x7fed5017e720, u=<optimized out>) at media_socket.c:1917
#12 0x000055de394ac5b0 in poller_poll (p=p@entry=0x55de3b3aa1c0, timeout=timeout@entry=100) at poller.c:351
#13 0x000055de394ac94d in poller_loop (d=0x55de3b3aa1c0) at poller.c:508
#14 0x000055de394aca69 in thread_detach_func (d=0x7fed48001cc0) at aux.c:207
#15 0x00007fed8d45e4a4 in start_thread (arg=0x7fed6cff9700) at pthread_create.c:456
#16 0x00007fed8cf9cd0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

[bt_full_mia_7.5.4_August14.log](https://github.com/sipwise/rtpengine/files/5082355/bt_full_mia_7.5.4_August14.log)

Please let us know if you need any other info or if you want me to open separate issues

thanks a lot and regards
david

**Comment by descartin** [comment]
Dear all

today we saw another one, also seems related with some lib729 issue
Program terminated with signal SIGFPE, Arithmetic exception

```
#0  0x00007f8f02f1814e in LP2LSPConversion () at /usr/lib/x86_64-linux-gnu/libbcg729.so.0
#1  0x00007f8f02f15491 in bcg729Encoder () at /usr/lib/x86_64-linux-gnu/libbcg729.so.0
#2  0x0000560f71a47178 in bcg729_encoder_input (enc=0x7f8e6413b540, frame=0x7f8e4e7f8bc8) at codeclib.c:1808
#3  0x0000560f71a48136 in encoder_input_data (enc=enc@entry=0x7f8e6413b540, frame=<optimized out>, callback=callback@entry=0x560f71a39eb0 <__packet_encoded>, u1=u1@entry=0x7f8e44194ae0, u2=u2@entry=0x7f8e4e7f8e88)
    at codeclib.c:1232
#4  0x0000560f71a4820d in encoder_fifo_flush (u2=<optimized out>, u1=<optimized out>, callback=<optimized out>, enc=<optimized out>) at codeclib.c:1266
#5  0x0000560f71a4820d in encoder_input_fifo (enc=0x7f8e6413b540, frame=frame@entry=0x7f8e3c2afa40, callback=callback@entry=0x560f71a39eb0 <__packet_encoded>, u1=u1@entry=0x7f8e44194ae0, u2=u2@entry=0x7f8e4e7f8e88)
    at codeclib.c:1280
#6  0x0000560f71a3b918 in __packet_decoded (decoder=<optimized out>, frame=<optimized out>, u1=<optimized out>, u2=0x7f8e4e7f8e88) at codec.c:1452
#7  0x0000560f71a476bb in decoder_input_data (dec=0x7f8ebc052ce0, data=<optimized out>, ts=<optimized out>, callback=callback@entry=0x560f71a3b780 <__packet_decoded>, u1=0x7f8e44194ae0, u2=u2@entry=0x7f8e4e7f8e88)
    at codeclib.c:711
#8  0x0000560f71a39a87 in packet_decode (ch=<optimized out>, packet=<optimized out>, mp=0x7f8e4e7f8e88) at codec.c:1466
#9  0x0000560f71a3b255 in __handler_func_sequencer (mp=0x7f8e4e7f8e88, packet=0x7f8e40092320) at codec.c:831
#10 0x0000560f71a31b6e in stream_packet (phc=0x7f8e4e7f8e30) at media_socket.c:1804
#11 0x0000560f71a31b6e in stream_fd_readable (fd=<optimized out>, p=0x7f8e9824a000, u=<optimized out>) at media_socket.c:1917
#12 0x0000560f719fc5b0 in poller_poll (p=p@entry=0x560f737241c0, timeout=timeout@entry=100) at poller.c:351
#13 0x0000560f719fc94d in poller_loop (d=0x560f737241c0) at poller.c:508
#14 0x0000560f719fca69 in thread_detach_func (d=0x560f7372eac0) at aux.c:207
#15 0x00007f8f026f54a4 in start_thread (arg=0x7f8e4e7fc700) at pthread_create.c:456
#16 0x00007f8f02233d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
``` 

i attach backtrace

thanks a lot and regards
david
[bt_full_mia_7.5.4_August31.log](https://github.com/sipwise/rtpengine/files/5149043/bt_full_mia_7.5.4_August31.log)

**Comment by rfuchs** [comment]
I'm not sure how actionable these are for us since they both occurred in libraries. SIGFPE in libbcg729 in particular points to a division by zero in the encoder, so you should probably go to them about it.

And a segfault in malloc via vsyslog might point to some random memory corruption but this is virtually impossible to debug without being reproducible.

**Comment by rfuchs** [comment]
Cleaning up old tickets
