### ISSUE TITLE
Segfaults on 10.0.0.0

### ISSUE THREAD

**Issue by StellaTeam** [sipwise/rtpengine#1302]
Hello,

I upgraded from 9.1.0.0 to 10.0.0.0 yesterday on two server and both crashed, one of them crashed twice.

Unfortunately, i don't have any core, and very few logs on the reason of the crash.

I don't have the proof but the the first crash happens on both devices when a client updated its NTP settings on its SBC, and so, a clock skew happened.
According to recent logs, clock skew protection was added to RTPEngine, so that looks strange.

Several minutes after the first crash, one of the server crashed again.

On every crashes, the messages are the same:

On syslog, i got 

```
Jul  6 09:25:30 juil.  6 09:25:30 systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=killed, status=11/SEGV
Jul  6 09:25:30 juil.  6 09:25:30 systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'signal'.


Jul  6 09:31:00 juil.  6 09:31:00 systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=killed, status=11/SEGV
Jul  6 09:31:00 juil.  6 09:31:00 systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'signal'.
Jul  6 10:06:39 juil.  6 10:06:39 systemd[1]: ngcp-rtpengine-daemon.service: Main process exited, code=killed, status=11/SEGV
Jul  6 10:06:39 juil.  6 10:06:39 systemd[1]: ngcp-rtpengine-daemon.service: Failed with result 'signal'.

```

On kernel logs i got

```
Jul  6 09:25:30 kernel: [24549226.873833] poller[10764]: segfault at 10 ip 00007ff0a55336c0 sp 00007ff0990f4518 error 4 in libpthread-2.28.so[7ff0a552f000+f000]
Jul  6 09:25:30 kernel: [24549226.873842] Code: ff 48 8d 0d c2 af 00 00 ba b1 01 00 00 48 8d 35 4b ae 00 00 48 8d 3d ff ae 00 00 e8 1a bb ff ff 8b 03 e9 45 fa ff ff 0f 1f 00 <8b> 47 10 89 c2 81 e2 7f 01 00 00 83 e0 7c 0f 85 9c 00 00 00 48 83


Jul  6 09:31:00 kernel: [24662872.850025] poller[7800]: segfault at 10 ip 00007f592d5616c0 sp 00007f592091e518 error 4 in libpthread-2.28.so[7f592d55d000+f000]
Jul  6 09:31:00 kernel: [24662872.850032] Code: ff 48 8d 0d c2 af 00 00 ba b1 01 00 00 48 8d 35 4b ae 00 00 48 8d 3d ff ae 00 00 e8 1a bb ff ff 8b 03 e9 45 fa ff ff 0f 1f 00 <8b> 47 10 89 c2 81 e2 7f 01 00 00 83 e0 7c 0f 85 9c 00 00 00 48 83
Jul  6 10:06:39 kernel: [24665011.916222] poller[23926]: segfault at 10 ip 00007f98e65ba6c0 sp 00007f98d9b78518 error 4 in libpthread-2.28.so[7f98e65b6000+f000]
Jul  6 10:06:39 kernel: [24665011.916233] Code: ff 48 8d 0d c2 af 00 00 ba b1 01 00 00 48 8d 35 4b ae 00 00 48 8d 3d ff ae 00 00 e8 1a bb ff ff 8b 03 e9 45 fa ff ff 0f 1f 00 <8b> 47 10 89 c2 81 e2 7f 01 00 00 83 e0 7c 0f 85 9c 00 00 00 48 83
```

For now i can't afford to make more tests and crashes as these devices are in production.

I hope somebody will have ideas on the reasons.

Hoping this might help others not to have such crashes.

Thank you all !

**Comment by rfuchs** [comment]
Do you have core dumps? If you do, load them up in gdb and post the backtrace.

**Comment by StellaTeam** [comment]
Hello @rfuchs

I had to do the backtrace on another server.
I'm not in use with all this, i hope this is what you need.

I also hope this will help.

Thank you


```
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/rtpengine...(no debugging symbols found)...done.
[New LWP 23926]
[New LWP 23918]
[New LWP 23917]
[New LWP 23933]
[New LWP 23932]
[New LWP 23941]
[New LWP 23923]
[New LWP 23919]
[New LWP 23934]
[New LWP 23939]
[New LWP 23916]
[New LWP 23937]
[New LWP 23950]
[New LWP 23920]
[New LWP 23930]
[New LWP 23931]
[New LWP 23929]
[New LWP 23936]
[New LWP 23943]
[New LWP 23935]
[New LWP 23938]
[New LWP 23940]
[New LWP 23945]
[New LWP 23944]
[New LWP 23946]
[New LWP 23948]
[New LWP 23949]
[New LWP 23951]
[New LWP 23942]
[New LWP 23925]
[New LWP 23953]
[New LWP 23922]
[New LWP 23928]
[New LWP 23921]
[New LWP 23947]
[New LWP 23924]
[New LWP 23952]
[New LWP 23927]

warning: Unexpected size of section `.reg-xstate/23926' in core file.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rtpengine -f -E --no-log-timestamps --pidfile /run/ngcp-rtpengine-dae'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Unexpected size of section `.reg-xstate/23926' in core file.
#0  __GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:67
67	../nptl/pthread_mutex_lock.c: Aucun fichier ou dossier de ce type.
[Current thread is 1 (Thread 0x7f98d9b7c700 (LWP 23926))]
(gdb) bt
#0  0x00007f98e65ba6c0 in __GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:67
#1  0x000055fc410786a0 in  ()
#2  0x000055fc4107e42e in  ()
#3  0x000055fc4107f2d8 in  ()
#4  0x000055fc4102cf13 in  ()
#5  0x000055fc4102d3ed in  ()
#6  0x000055fc4102d542 in  ()
#7  0x00007f98e65b7fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007f98e64e84cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

```
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/rtpengine...(no debugging symbols found)...done.
[New LWP 4637]
[New LWP 4646]
[New LWP 4635]
[New LWP 4632]
[New LWP 4631]
[New LWP 4648]
[New LWP 4641]
[New LWP 4633]
[New LWP 4645]
[New LWP 4650]
[New LWP 4642]
[New LWP 4634]
[New LWP 4636]
[New LWP 4649]
[New LWP 4644]
[New LWP 4643]
[New LWP 4652]
[New LWP 4638]
[New LWP 4647]
[New LWP 4651]
[New LWP 4640]
[New LWP 4639]

warning: Could not load shared library symbols for 153 libraries, e.g. /lib/x86_64-linux-gnu/libglib-2.0.so.0.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rtpengine -f -E --no-log-timestamps --pidfile /run/ngcp-rtpengine-dae'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:67
67	../nptl/pthread_mutex_lock.c: Aucun fichier ou dossier de ce type.
[Current thread is 1 (Thread 0x7fa74710e700 (LWP 4637))]
(gdb) bt
#0  __GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:67
#1  0x000055a520d056a0 in ?? ()
#2  0x000055a520d0b42e in ?? ()
#3  0x000055a520d0c2d8 in ?? ()
#4  0x000055a520cb9f13 in ?? ()
#5  0x000055a520cba3ed in ?? ()
#6  0x000055a520cba542 in ?? ()
#7  0x00007fa753345fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fa7532764cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by rfuchs** [comment]
If you have -dbg or -dbgsym packages for rtpengine, install them and then pull the backtrace again.

**Comment by StellaTeam** [comment]
Here are the bt with dbgsym

```
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/rtpengine...Reading symbols from /usr/lib/debug/.build-id/d7/0b18b5a39cd64ab16c0c04818dbbe0b1957469.debug...done.
done.
[New LWP 4637]
[New LWP 4646]
[New LWP 4635]
[New LWP 4632]
[New LWP 4631]
[New LWP 4648]
[New LWP 4641]
[New LWP 4633]
[New LWP 4645]
[New LWP 4650]
[New LWP 4642]
[New LWP 4634]
[New LWP 4636]
[New LWP 4649]
[New LWP 4644]
[New LWP 4643]
[New LWP 4652]
[New LWP 4638]
[New LWP 4647]
[New LWP 4651]
[New LWP 4640]
[New LWP 4639]

warning: Could not load shared library symbols for 153 libraries, e.g. /lib/x86_64-linux-gnu/libglib-2.0.so.0.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rtpengine -f -E --no-log-timestamps --pidfile /run/ngcp-rtpengine-dae'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI___pthread_mutex_lock (mutex=mutex@entry=0x0) at ../nptl/pthread_mutex_lock.c:67
67	../nptl/pthread_mutex_lock.c: Aucun fichier ou dossier de ce type.
[Current thread is 1 (Thread 0x7fa74710e700 (LWP 4637))]
(gdb) bt
#0  __GI___pthread_mutex_lock (mutex=mutex@entry=0x0) at ../nptl/pthread_mutex_lock.c:67
#1  0x000055a520d056a0 in __stream_ssrc_in (in_srtp=0x0, ssrc_bs=<optimized out>, ssrc_in_p=ssrc_in_p@entry=0x7fa74710a760, ssrc_hash=0x7fa72c35c320) at media_socket.c:1556
#2  0x000055a520d0b42e in media_packet_rtp_in (phc=0x7fa74710a660) at media_socket.c:1761
#3  stream_packet (phc=phc@entry=0x7fa74710a660) at media_socket.c:2214
#4  0x000055a520d0c2d8 in stream_fd_readable (fd=465, p=0x7fa704370460, u=<optimized out>) at media_socket.c:2444
#5  0x000055a520cb9f13 in poller_poll (p=0x55a5224876d0, timeout=<optimized out>) at poller.c:440
#6  0x000055a520cba3ed in poller_loop2 (d=0x55a5224876d0) at poller.c:612
#7  0x000055a520cba542 in thread_detach_func (d=0x55a522455340) at aux.c:232
#8  0x00007fa753345fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#9  0x00007fa7532764cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

```
root@sfr-th2:~/compilation-20210705# gdb /usr/sbin/rtpengine core-18
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/rtpengine...Reading symbols from /usr/lib/debug/.build-id/d7/0b18b5a39cd64ab16c0c04818dbbe0b1957469.debug...done.
done.
[New LWP 23926]
[New LWP 23918]
[New LWP 23917]
[New LWP 23933]
[New LWP 23932]
[New LWP 23941]
[New LWP 23923]
[New LWP 23919]
[New LWP 23934]
[New LWP 23939]
[New LWP 23916]
[New LWP 23937]
[New LWP 23950]
[New LWP 23920]
[New LWP 23930]
[New LWP 23931]
[New LWP 23929]
[New LWP 23936]
[New LWP 23943]
[New LWP 23935]
[New LWP 23938]
[New LWP 23940]
[New LWP 23945]
[New LWP 23944]
[New LWP 23946]
[New LWP 23948]
[New LWP 23949]
[New LWP 23951]
[New LWP 23942]
[New LWP 23925]
[New LWP 23953]
[New LWP 23922]
[New LWP 23928]
[New LWP 23921]
[New LWP 23947]
[New LWP 23924]
[New LWP 23952]
[New LWP 23927]

warning: Unexpected size of section `.reg-xstate/23926' in core file.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rtpengine -f -E --no-log-timestamps --pidfile /run/ngcp-rtpengine-dae'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Unexpected size of section `.reg-xstate/23926' in core file.
#0  __GI___pthread_mutex_lock (mutex=mutex@entry=0x0) at ../nptl/pthread_mutex_lock.c:67
67	../nptl/pthread_mutex_lock.c: Aucun fichier ou dossier de ce type.
[Current thread is 1 (Thread 0x7f98d9b7c700 (LWP 23926))]
(gdb) bt
#0  0x00007f98e65ba6c0 in __GI___pthread_mutex_lock (mutex=mutex@entry=0x0) at ../nptl/pthread_mutex_lock.c:67
#1  0x000055fc410786a0 in __stream_ssrc_in (in_srtp=0x0, ssrc_bs=<optimized out>, ssrc_in_p=ssrc_in_p@entry=0x7f98d9b78760, ssrc_hash=0x7f98c00bb510) at media_socket.c:1556
#2  0x000055fc4107e42e in media_packet_rtp_in (phc=0x7f98d9b78660) at media_socket.c:1761
#3  0x000055fc4107e42e in stream_packet (phc=phc@entry=0x7f98d9b78660) at media_socket.c:2214
#4  0x000055fc4107f2d8 in stream_fd_readable (fd=905, p=0x7f98a40f48b0, u=<optimized out>) at media_socket.c:2444
#5  0x000055fc4102cf13 in poller_poll (p=0x55fc42a7ba80, timeout=<optimized out>) at poller.c:440
#6  0x000055fc4102d3ed in poller_loop2 (d=0x55fc42a7ba80) at poller.c:612
#7  0x000055fc4102d542 in thread_detach_func (d=0x55fc42a49640) at aux.c:232
#8  0x00007f98e65b7fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#9  0x00007f98e64e84cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
