### ISSUE TITLE
RTPEngine crash at media_socket.c:1111 - Media packet discarded due to lack of sink

### ISSUE THREAD

**Issue by mkezys** [sipwise/rtpengine#1401]
Hello,

7 identical servers handling 300-400 calls per server. Each crashes 3-4 times in 24h with the same gdb output.

CentOS Linux release 7.8.2003 (Core)
Latest RTPEngine Revision

Checked several crash times. Just before the crash log shows:

```
Nov 16 21:06:23.8911 WARNING: [060bce38472111ec8852005056a93d3c port 27694]: [core] Media packet from 222.222.222.222:26594 discarded due to lack of sink
Nov 16 21:06:26.0222 WARNING: [060bce38472111ec8852005056a93d3c port 27695]: [core] Media packet from 222.222.222.222:26595 discarded due to lack of sink
```

```
Core was generated by `/usr/local/bin/rtpengine -p /var/run/rtpengine.pid -i 111.111.111.111 -n 111.111.11'.
Program terminated with signal 11, Segmentation fault.

#0  0x00000000004d03d4 in __re_address_translate_ep (ep=0x30, o=0x7fa504057290) at media_socket.c:1111
1111 ep->address.family->endpoint2kernel(o, ep);
#0  0x00000000004d03d4 in kernelize_one (ep=0x30, o=0x7fa504057290) at media_socket.c:1111
        redi = 0x7fa504057270
        call = 0x7fa4ec239500
        media = 0x7fa50c240fc0
        sink = 0x7fa4f44d6c20
        non_forwarding = false
        blackhole = false
        handler = 0x555790 <__sh_noop_rtp>
        __PRETTY_FUNCTION__ = "kernelize_one"
#1  0x00000000004d03d4 in kernelize_one (reti=0x7fa51f120240, outputs=0x7fa51f120220, stream=0x7fa4f44d64e0, sink_handler=0x7fa4ec361920, sinks=0x7fa4f44d65a0) at media_socket.c:1289
        redi = 0x7fa504057270
        call = 0x7fa4ec239500
        media = 0x7fa50c240fc0
        sink = 0x7fa4f44d6c20
        non_forwarding = false
        blackhole = false
        handler = 0x555790 <__sh_noop_rtp>
        __PRETTY_FUNCTION__ = "kernelize_one"
#2  0x00000000004d09b8 in kernelize (stream=0x7fa4f44d64e0) at media_socket.c:1359
        sh = 0x7fa4ec361920
        sink = 0x7fa4f44d6c20
        err = 0x7fa4f44d6c48 "\001"
        l = 0x7fa4f42ee8c0 = {0x7fa4ec361920}
        call = 0x7fa4ec239500
        nk_warn_msg = 0x556590 "interface to kernel module not open"
        media = 0x7fa50c240fc0
        sinks = 0x7fa4f44d65a0
        reti = {local = {family = 2, u = {ipv6 = "\252N8\017", '\000' , ipv4 = 25534839, u8 = "\252N8\017", '\000' , u16 = {20138, 3896, 0, 0, 0, 0, 0, 0}, u32 = {25534839, 0, 0, 0}}, port = 18736}, expected_src = {family = 0, u = {ipv6 = '\000' , ipv4 = 0, u8 = '\000' , u16 = {0, 0, 0, 0, 0, 0, 0, 0}, u32 = {0, 0, 0, 0}}, port = 0}, src_mismatch = MSM_IGNORE, num_destinations = 0, intercept_stream_idx = 0, decrypt = {cipher = REC_NULL, hmac = REH_NULL, master_key = '\000' , master_key_len = 0, master_salt = '\000' , master_salt_len = 0, session_key_len = 0, session_salt_len = 0, mki = '\000' , last_index = {0, 0, 0, 0}, auth_tag_len = 0, mki_len = 0}, ssrc = {3141625808, 0, 0, 0}, payload_types = {{pt_num = 0 '\000', replace_pattern_len = 0 '\000', clock_rate = 8000, replace_pattern = '\000' }, {pt_num = 8 '\b', replace_pattern_len = 0 '\000', clock_rate = 8000, replace_pattern = '\000' }, {pt_num = 18 '\022', replace_pattern_len = 0 '\000', clock_rate = 8000, replace_pattern = '\000' }, {pt_num = 0 '\000', replace_pattern_len = 0 '\000', clock_rate = 0, replace_pattern = '\000' } }, num_payload_types = 3, rtcp_mux = 0, dtls = 0, stun = 0, rtp = 1, rtp_only = 0, do_intercept = 0, transcoding = 0, non_forwarding = 0, blackhole = 0, rtp_stats = 0}
        outputs = {head = 0x0, tail = 0x0, length = 0}
        redi = 0x0
#3  0x00000000004d6341 in media_packet_kernel_check (phc=0x7fa51f120d60) at media_socket.c:2156
#4  0x00000000004d885d in stream_packet (phc=0x7fa51f120d60) at media_socket.c:2497
        ret = 0
        handler_ret = 0
        free_list = {head = 0x0, tail = 0x0, length = 0}
        stun_ret = -1
        address_check = 0
        orig_raw = {s = 0x0, len = 0}
#5  0x00000000004d93ea in stream_fd_readable (fd=1612, p=0x7fa50048ccf0, u=0) at media_socket.c:2599
        phc = {s = {s = 0x7fa51f120f30 "\200", len = 172}, sinks = 0x7fa4f44d65a0, decrypt_func = 0x0, encrypt_func = 0x0, rtcp_filter = 0x0, in_srtp = 0x7fa4f44d64e0, out_srtp = 0x7fa4f44d6c20, payload_type = 0, rtcp = 0, rtcp_list = {head = 0x0, tail = 0x0, length = 0}, update = 1, unkernelize = 0, unconfirm = 0, unkernelize_subscriptions = 0, kernelize = 1, rtcp_discard = 0, mp = {raw = {s = 0x7fa51f120f30 "\200", len = 172}, fsin = {address = {family = 0x777780 <__socket_families>, u = {ipv4 = {s_addr = 1736152768}, ipv6 = {__in6_u = {__u6_addr8 = "\300\226{g", '\000' , __u6_addr16 = {38592, 26491, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {1736152768, 0, 0, 0}}}}}, port = 17544}, tv = {tv_sec = 1637084090, tv_usec = 21757}, sfd = 0x7fa50048ccf0, call = 0x7fa4ec239500, stream = 0x7fa4f44d64e0, media = 0x7fa50c240fc0, media_out = 0x7fa50c240da0, sink = {sink = 0x7fa4f44d6c20, handler = 0x555790 <__sh_noop_rtp>, kernel_output_idx = -1}, rtp = 0x7fa51f120f30, rtcp = 0x0, ssrc_in = 0x7fa4fc239850, ssrc_out = 0x0, payload = {s = 0x7fa51f120f3c '\377' , "\244\177", len = 160}, packets_out = {head = 0x0, tail = 0x0, length = 0}, ptime = 0}}
        sfd = 0x7fa50048ccf0
        buf = "\300\024\022\037\245\177\000\000\213\027`0\245\177", '\000' , " ", '\000' , "\060\020\022\037\245\177\000\000\360\017\022\037\245\177\000\000\035c`0\245\177\000\000\000\000\000\000\000\000\000\000\200\000S\a\r\345\347P\320gA\273", '\377' ...
        ret = 172
        iters = 0
        update = 0
        ca = 0x7fa50c24f180
        strikes = 0
#6  0x00000000004215e3 in poller_poll (p=0x1714590, timeout=100) at poller.c:440
        ret = 1
        i = 0
        it = 0x7fa4e801f9e0
        evs = {{events = 1, data = {ptr = 0x64c, fd = 1612, u32 = 1612, u64 = 1612}}, {events = 1, data = {ptr = 0x4be, fd = 1214, u32 = 1214, u64 = 1214}}, {events = 1, data = {ptr = 0x3fe, fd = 1022, u32 = 1022, u64 = 1022}}, {events = 1, data = {ptr = 0x440, fd = 1088, u32 = 1088, u64 = 1088}}, {events = 1, data = {ptr = 0x47, fd = 71, u32 = 71, u64 = 71}}, {events = 1, data = {ptr = 0x26b, fd = 619, u32 = 619, u64 = 619}}, {events = 1, data = {ptr = 0x71, fd = 113, u32 = 113, u64 = 113}}, {events = 1, data = {ptr = 0x211, fd = 529, u32 = 529, u64 = 529}}, {events = 1, data = {ptr = 0x49c, fd = 1180, u32 = 1180, u64 = 1180}}, {events = 1, data = {ptr = 0x24e, fd = 590, u32 = 590, u64 = 590}}, {events = 1, data = {ptr = 0x471, fd = 1137, u32 = 1137, u64 = 1137}}, {events = 1, data = {ptr = 0x444, fd = 1092, u32 = 1092, u64 = 1092}}, {events = 1, data = {ptr = 0x483, fd = 1155, u32 = 1155, u64 = 1155}}, {events = 1, data = {ptr = 0x6c3, fd = 1731, u32 = 1731, u64 = 1731}}, {events = 1, data = {ptr = 0x47f, fd = 1151, u32 = 1151, u64 = 1151}}, {events = 1, data = {ptr = 0x4f0, fd = 1264, u32 = 1264, u64 = 1264}}, {events = 1, data = {ptr = 0x601, fd = 1537, u32 = 1537, u64 = 1537}}, {events = 1, data = {ptr = 0x48a, fd = 1162, u32 = 1162, u64 = 1162}}, {events = 1, data = {ptr = 0x26, fd = 38, u32 = 38, u64 = 38}}, {events = 1, data = {ptr = 0x6ca, fd = 1738, u32 = 1738, u64 = 1738}}, {events = 1, data = {ptr = 0x5ee, fd = 1518, u32 = 1518, u64 = 1518}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}} , {events = 0, data = {ptr = 0x100000000000, fd = 0, u32 = 0, u64 = 17592186044416}}, {events = 0, data = {ptr = 0x7fa4fc000070, fd = -67108752, u32 = 4227858544, u64 = 140346579222640}}, {events = 3773679921, data = {ptr = 0x1f1236d0ffff805a, fd = -32678, u32 = 4294934618, u64 = 2238912236032589914}}, {events = 32677, data = {ptr = 0xffff805ae0edc8e1, fd = -521287455, u32 = 3773679841, u64 = 18446603726541932769}}, {events = 67, data = {ptr = 0x1000000000, fd = 0, u32 = 0, u64 = 68719476736}}, {events = 0, data = {ptr = 0x2, fd = 2, u32 = 2, u64 = 2}}, {events = 64, data = {ptr = 0x1f1237200000005d, fd = 93, u32 = 93, u64 = 2238912575335039069}}, {events = 32677, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 4227866096, data = {ptr = 0xfc00002000007fa4, fd = 32676, u32 = 32676, u64 = 18158513834996826020}}, {events = 32676, data = {ptr = 0x20210, fd = 131600, u32 = 131600, u64 = 131600}}, {events = 1, data = {ptr = 0xfc00202000000000, fd = 0, u32 = 0, u64 = 18158549019368882176}}, {events = 32676, data = {ptr = 0x1ffe0, fd = 131040, u32 = 131040, u64 = 131040}}, {events = 811835554, data = {ptr = 0x7c00007fa5, fd = 32677, u32 = 32677, u64 = 532575977381}}, {events = 0, data = {ptr = 0x7fa4fc001620, fd = -67103200, u32 = 4227864096, u64 = 140346579228192}}, {events = 133600, data = {ptr = 0x3063a0a200000000, fd = 0, u32 = 0, u64 = 3486807154160041984}}, {events = 32677, data = {ptr = 0x7c, fd = 124, u32 = 124, u64 = 124}}, {events = 0, data = {ptr = 0x1f12470000000000, fd = 0, u32 = 0, u64 = 2238930030082129920}}, {events = 32677, data = {ptr = 0x200, fd = 512, u32 = 512, u64 = 512}}, {events = 512, data = {ptr = 0xfc001bf000000000, fd = 0, u32 = 0, u64 = 18158544415163940864}}, {events = 32676, data = {ptr = 0x7fa4fc000020, fd = -67108832, u32 = 4227858464, u64 = 140346579222560}}, {events = 512, data = {ptr = 0x3300000000, fd = 0, u32 = 0, u64 = 219043332096}}, {events = 0, data = {ptr = 0x7fa53063c1bb <_int_memalign+491>, fd = 811844027, u32 = 811844027, u64 = 140347458175419}}, {events = 4227858464, data = {ptr = 0xfc00002000007fa4, fd = 32676, u32 = 32676, u64 = 18158513834996826020}}, {events = 32676, data = {ptr = 0x200, fd = 512, u32 = 512, u64 = 512}}, {events = 496, data = {ptr = 0x2000000000, fd = 0, u32 = 0, u64 = 137438953472}}, {events = 0, data = {ptr = 0x7fa53063f075 , fd = 811855989, u32 = 811855989, u64 = 140347458187381}}, {events = 521287648, data = {ptr = 0x2000007fa5, fd = 32677, u32 = 32677, u64 = 137438986149}}, {events = 0, data = {ptr = 0x8, fd = 8, u32 = 8, u64 = 8}}, {events = 811863292, data = {ptr = 0x100007fa5, fd = 32677, u32 = 32677, u64 = 4294999973}}, {events = 0, data = {ptr = 0x7fa536bed9ac , fd = 918477228, u32 = 918477228, u64 = 140347564808620}}, {events = 4227865600, data = {ptr = 0x4261f10000007fa4, fd = 32676, u32 = 32676, u64 = 4783369261546504100}}, {events = 3247436339, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 4227860672, data = {ptr = 0x1800007fa4, fd = 32676, u32 = 32676, u64 = 103079247780}}, {events = 0, data = {ptr = 0x7fa4fc0008e0, fd = -67106592, u32 = 4227860704, u64 = 140346579224800}}, {events = 32, data = {ptr = 0x3200000000, fd = 0, u32 = 0, u64 = 214748364800}}, {events = 0, data = {ptr = 0x33, fd = 51, u32 = 51, u64 = 51}}, {events = 918794915, data = {ptr = 0x1000007fa5, fd = 32677, u32 = 32677, u64 = 68719509413}}, {events = 0, data = {ptr = 0x7fa4f8001b60, fd = -134210720, u32 = 4160756576, u64 = 140346512120672}}}
        ev = 0x7fa51f123240
        e = {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}
#7  0x0000000000421d36 in poller_loop2 (d=0x1714590) at poller.c:612
        ret = 1
        p = 0x1714590
#8  0x00000000004229c8 in thread_detach_func (d=0x16f6da0) at aux.c:234
        dt = 0x16f6da0
        t = 0x7fa4f8001440
        scheduler = 0x0
#9  0x00007fa530fa9ea5 in start_thread () at /lib64/libpthread.so.0
#10 0x00007fa5306b79fd in clone () at /lib64/libc.so.6
```

**Comment by rfuchs** [comment]
Which version/commit is this on?

**Comment by mkezys** [comment]
Revision: 2c0e196be9f63c027b09b82884866843c3ed2e89
