### ISSUE TITLE
Crash rtcp_send_report at rtcp.c:1595 with generate-RTCP

### ISSUE THREAD

**Issue by mkezys** [sipwise/rtpengine#1408]
Hello,

Revision: 2c0e196

With **_generate-RTCP_** from Kamailio, RTPEngine crashes every 10-15 min with the log provided below.

Removing **_generate-RTCP_** eliminates crashes.

```
(gdb) bt full
#0  0x00007fd6dfd4f3d7 in raise () at /lib64/libc.so.6
#1  0x00007fd6dfd50ac8 in abort () at /lib64/libc.so.6
#2  0x00007fd6dfd91f67 in __libc_message () at /lib64/libc.so.6
#3  0x00007fd6dfd99a4f in malloc_consolidate () at /lib64/libc.so.6
#4  0x00007fd6dfd9a20e in _int_free () at /lib64/libc.so.6
#5  0x00007fd6e638386e in g_free () at /lib64/libglib-2.0.so.0
#6  0x00007fd6e639f5da in g_string_free () at /lib64/libglib-2.0.so.0
#7  0x0000000000488620 in rtcp_send_report (media=0x7fd6ac0366b0, ssrc_out=0x7fd6a41bccd0) at rtcp.c:1595
        ps = 0x7fd6b010b850
        rrs = {head = 0x0, tail = 0x0, length = 0}
        ssr = {ssrc = 2069521000, ntp_msw = 3847526206, ntp_lsw = 171244641, timestamp = 2351261920, packet_count = 725, octet_count = 124700}
        srrs =
          {head = 0x7fd6c0133e40 = {0x7fd6b4023ce0, 0x7fd6a015dc80, 0x7fd6980de040, 0x7fd6b0047ac0, 0x7fd6c0088820, 0x7fd6b0225300, 0x7fd6c0135d40, 0x7fd69c14dd60, 0x7fd6ac054e60, 0x7fd6c007e640, 0x7fd6a0221c40, 0x7fd6a0080b60, 0x7fd6bc251720}, tail = 0x7fd698099ac0 = {0x7fd6bc251720}, length = 13}
        sr = 0x7fd6ac07e940
        sinks = 0xfaa10bd37c20fa00
#8  0x00000000004fc416 in __rtcp_timer_run (ct=0x7fd6ac01af20) at codec.c:827
        u = 0
        rt = 0x7fd6ac01af20
        media = 0x7fd6ac0366b0
        ssrc_out = {0x7fd6a41bccd0, 0x0, 0x0, 0x0}
#9  0x0000000000512fe0 in codec_timers_run (p=0x7fd6ac01af20) at codec.c:4035
        ct = 0x7fd6ac01af20
#10 0x0000000000515cb9 in timerthread_run (p=0x779640 <codec_timers_thread>) at timerthread.c:57
        tt_obj = 0x7fd6ac01af20
        sleeptime = 49615
        tv = {tv_sec = 1638537406, tv_usec = 39780}
        tt = 0x779640 <codec_timers_thread>
        waker = {lock = 0x779648 <codec_timers_thread+8>, cond = 0x779670 <codec_timers_thread+48>}
#11 0x000000000051301d in codec_timers_loop (p=0x0) at codec.c:4045
#12 0x00000000004229c8 in thread_detach_func (d=0x2649220) at aux.c:234
        dt = 0x2649220
        t = 0x7fd668001410
        scheduler = 0x0
#13 0x00007fd6e0709ea5 in start_thread () at /lib64/libpthread.so.0
#14 0x00007fd6dfe179fd in clone () at /lib64/libc.so.6
```

**Comment by rfuchs** [comment]
Already fixed by 835ba08b
