### ISSUE TITLE
Segfault when initializing call using rtpproxy udp mode

### ISSUE THREAD

**Issue by yokem55** [sipwise/rtpengine#1437]
Hi,
I'm seeing an immediate segfault after rtpengine starts processing a call request on the legacy rtpproxy udp protocol;

Version(s): Seen with 10.2.1.5 (dfx packages) and latest mr9.5 from git (`~# rtpengine -v
Version: 9.5.4.0+0~mr9.5.4.0 git-HEAD-b00ce05f`)

gdb backtrace of the coredump with the latest mr9.5 git:
```
root@rtpengine-host:~# rtpengine -v
Version: 9.5.4.0+0~mr9.5.4.0 git-HEAD-b00ce05f
root@rtpengine-host:~# gdb /usr/sbin/rtpengine rtpengine-core.dump 
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/rtpengine...
Reading symbols from /usr/lib/debug/.build-id/2c/bb4f7fc0910f8f07484d37e173d272d1497470.debug...
[New LWP 50861]
[New LWP 50857]
[New LWP 50859]
[New LWP 50862]
[New LWP 50863]
[New LWP 50868]
[New LWP 50869]
[New LWP 50871]
[New LWP 50872]
[New LWP 50873]
[New LWP 50875]
[New LWP 50877]
[New LWP 50870]
[New LWP 50874]
[New LWP 50867]
[New LWP 50865]
[New LWP 50866]
[New LWP 50864]
[New LWP 50856]
[New LWP 50876]
[New LWP 50860]
[New LWP 50858]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
--Type <RET> for more, q to quit, c to continue without paging--
Core was generated by `/usr/sbin/rtpengine -f -E --no-log-timestamps --pidfile /run/ngcp-rtpengine-dae'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  monologue_offer_answer (other_ml=other_ml@entry=0x7f7844019830, streams=streams@entry=0x7f786af2c4c0, flags=flags@entry=0x0)
    at call.c:2414
2414	call.c: No such file or directory.
[Current thread is 1 (Thread 0x7f786af2e700 (LWP 50861))]
(gdb) bt full
#0  monologue_offer_answer (other_ml=other_ml@entry=0x7f7844019830, streams=streams@entry=0x7f786af2c4c0, flags=flags@entry=0x0)
    at call.c:2414
        sp = <optimized out>
        media_iter = <optimized out>
        ml_media = 0x558336bf28c0 = {0x7f784401c0a0}
        other_ml_media = 0x558336bf2900 = {0x7f784401c2d0}
        media = <optimized out>
        other_media = 0x7f784401c2d0
        num_ports = 2
        monologue = <optimized out>
        em = 0x7f784401e1e0
        call = <optimized out>
#1  0x00005583369074a1 in call_update_lookup_udp (out=out@entry=0x7f7844017a50, opmode=(OP_ANSWER | OP_OTHER | unknown: 0x6af2c4dc), 
    opmode@entry=OP_OFFER, addr=addr@entry=0x7f7844017398 "172.25.0.37:46739", sin=sin@entry=0x7f7844017378)
    at call_interfaces.strhash.c:518
        c = 0x7f7844018100
        monologue = 0x7f7844019830
        q = {head = 0x558336bf2880 = {0x7f786af2c4e0}, tail = 0x558336bf2880 = {0x7f786af2c4e0}, length = 1}
        sp = 
            {index = 1, type = {s = 0x0, len = 0}, rtp_endpoint = {address = {family = 0x558336993ac0 <__socket_families>, u = {ipv4 = {s_addr = 3142796752}, ipv6 = {__in6_u = {__u6_addr8 = "\320ES\273", '\000' <repeats 11 times>, __u6_addr16 = {17872, 47955, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {3142796752, 0, 0, 0}}}}}, port = 46716}, rtcp_endpoint = {address = {family = 0x558336993ac0 <__socket_families>, u = {ipv4 = {s_addr = 3142796752}, ipv6 = {__in6_u = {__u6_addr8 = "\320ES\273", '\000' <repeats 11 times>, __u6_addr16 = {17872, 47955, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {3142796752, 0, 0, 0}}}}}, port = 46717}, consecutive_ports = 1, protocol = 0x55833698db20 <transport_protocols>, format_str = {s = 0x0, len = 0}, sdes_params = {head = 0x0, tail = 0x0, length = 0}, direction = {{s = 0x55833696c9bf "external", len = 8}, {s = 0x55833696c9c8 "internal", len = 8}}, desired_family = 0x0, fingerprint = {digest = '\000' <repeats 63 times>, digest_len = 0, hash_func = 0x0}, sp_flags = 12, rtp_payload_types = {head = 0x0, tail = 0x0, length = 0}, ice_candidates = {head = 0x0, tail = 0x0, length = 0}, ice_ufrag = {s = 0x0, len = 0}, ice_pwd = {s = 0x0, len = 0}, ptime = 0, media_id = {s = 0x0, len = 0}, t38_options = {version = 0, fec_span = 0, min_ec_entries = 0, max_ec_entries = 0, max_ifp = 0, max_datagram = 0, local_tcf = 0, fill_bit_removal = 0, transcoding_mmr = 0, transcoding_jbig = 0, no_ecm = 0, no_v17 = 0, no_v27ter = 0, no_v29 = 0, no_v34 = 0, no_iaf = 0}}
        ret = <optimized out>
        callid = {s = 0x7f7844017b0f "426290103_66956988@208.69.83.180", len = 32}
        viabranch = {s = <optimized out>, len = <optimized out>}
        fromtag = {s = 0x7f7844017b46 "gK08280195", len = 10}
        totag = {s = 0x0, len = 0}
        i = <optimized out>
#2  0x000055833690e03d in call_update_udp
    (out=out@entry=0x7f7844017a50, addr=addr@entry=0x7f7844017398 "172.25.0.37:46739", sin=sin@entry=0x7f7844017378)
--Type <RET> for more, q to quit, c to continue without paging--
    at call_interfaces.strhash.c:553
#3  0x00005583368e52de in control_udp_incoming (obj=0x558336beb000, udp_buf=0x7f78440070d0) at control_udp.c:88
        u = 0x558336beb000
        ret = 1794295504
        ovec = 
          {0, 79, 0, 7, 8, 9, 9, 13, 14, 46, -1, -1, 47, 60, -1, -1, 61, 66, 67, 77, 78, 79, -1 <repeats 20 times>, 16, 0, 1794295888, 32632, 9321472, -1812500178, 1794296096, 32632, 918417296, 21891, 1140879568, 32632, 1140945816, 32632, 915838369, 21891, 79, 0, 1140945784, 32632, 1939053419, 32632, 40, 48, 1794296224, 32632, 1794296032, 32632, 9321472, -1812500178, 915838369, 21891, 66320, 0, 918464776, 21891, 1938522777, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 78, 67, 61, -1, 47, -1, 14, 9, 8, 0, -1812500178}
        out = 0x7f7844017a50
        iov = 
            {{iov_base = 0x7f7844000000, iov_len = 140155167098752}, {iov_base = 0x3933373634ffffff, iov_len = 10662115085214694400}, {iov_base = 0x7f78440173a3, iov_len = 140155167099072}, {iov_base = 0xffffffffffffffff, iov_len = 6}, {iov_base = 0x7f786af2c780, iov_len = 94022044915105}, {iov_base = 0x7f78440173a3, iov_len = 140155311247568}, {iov_base = 0xfbad8001, iov_len = 140154513748899}, {iov_base = 0x7f78440173a3, iov_len = 140154513748899}, {iov_base = 0x7f78440173a3, iov_len = 140154513748905}, {iov_base = 0xffffffffffffffff, iov_len = 140154513748899}}
        iovlen = <optimized out>
        cookie = {s = 0x7f7844017b00 "19530_4", len = 7}
        reply = <optimized out>
#4  0x00005583368f3b55 in udp_listener_incoming (fd=<optimized out>, p=0x558336bdef90, x=<optimized out>) at udp_listener.c:54
        cb = 0x558336bdef90
        len = 79
        udp_buf = 0x7f78440070d0
#5  0x00005583368d7617 in poller_poll (p=0x558336bea900, timeout=<optimized out>) at poller.c:440
        ret = 1
        i = 0
        it = 0x558336be9980
        evs = 
              {{events = 1, data = {ptr = 0x5, fd = 5, u32 = 5, u64 = 5}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}} <repeats 91 times>, {events = 0, data = {ptr = 0x738b71cc00000000, fd = 0, u32 = 0, u64 = 8325873457111760896}}, {events = 32632, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x4100000000, fd = 0, u32 = 0, u64 = 279172874240}}, {events = 0, data = {ptr = 0x7f78738b71cc <_int_malloc+3196>, fd = 1938518476, u32 = 1938518476, u64 = 140155311321548}}, {events = 0, data = {ptr = 0x42000000000, fd = 0, u32 = 0, u64 = 4535485464576}}, {events = 0, data = {ptr = 0x40, fd = 64, u32 = 64, u64 = 64}}, {events = 0, data = {ptr = 0x23000000000, fd = 0, u32 = 0, u64 = 2405181685760}}, {events = 0, data = {ptr = 0x10, fd = 16, u32 = 16, u64 = 16}}, {events = 67, data = {ptr = 0x6e00000040, fd = 64, u32 = 64, u64 = 472446402624}}, {events = 124, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 93, data = {ptr = 0x200000077, fd = 119, u32 = 119, u64 = 8589934711}}, {events = 0, data = {ptr = 0x93f7712e008e3c00, fd = 9321472, u32 = 9321472, u64 = 10662115085214694400}}, {events = 0, data = {ptr = 0x20000000000, fd = 0, u32 = 0, u64 = 2199023255552}}, {events = 0, data = {ptr = 0x7f7844000020, fd = 1140850720, u32 = 1140850720, u64 = 140154513653792}}, {events = 1140869632, data = {ptr = 0x440049f000007f78, fd = 32632, --Type <RET> for more, q to quit, c to continue without paging--
u32 = 32632, u64 = 4899997689720110968}}, {events = 32632, data = {ptr = 0x2c0, fd = 704, u32 = 704, u64 = 704}}, {events = 517, data = {ptr = 0x738b75c500000000, fd = 0, u32 = 0, u64 = 8325877825093500928}}, {events = 32632, data = {ptr = 0x7f7844000020, fd = 1140850720, u32 = 1140850720, u64 = 140154513653792}}, {events = 1794297760, data = {ptr = 0x20000007f78, fd = 32632, u32 = 32632, u64 = 2199023288184}}, {events = 0, data = {ptr = 0x1f0, fd = 496, u32 = 496, u64 = 496}}, {events = 1140850720, data = {ptr = 0x20000007f78, fd = 32632, u32 = 32632, u64 = 2199023288184}}, {events = 0, data = {ptr = 0x10, fd = 16, u32 = 16, u64 = 16}}, {events = 1938523484, data = {ptr = 0x800007f78, fd = 32632, u32 = 32632, u64 = 34359771000}}, {events = 0, data = {ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 917972440, data = {ptr = 0x738b9b4200005583, fd = 21891, u32 = 21891, u64 = 8325919043894662531}}, {events = 32632, data = {ptr = 0x20, fd = 32, u32 = 32, u64 = 32}}, {events = 1977149097, data = {ptr = 0x44004a0000007f78, fd = 32632, u32 = 32632, u64 = 4899997758439587704}}, {events = 32632, data = {ptr = 0x93f7712e008e3c00, fd = 9321472, u32 = 9321472, u64 = 10662115085214694400}}, {events = 16, data = {ptr = 0x44002f7000000000, fd = 0, u32 = 0, u64 = 4899968552661942272}}, {events = 32632, data = {ptr = 0x33, fd = 51, u32 = 51, u64 = 51}}, {events = 918497312, data = {ptr = 0x44002f9000005583, fd = 21891, u32 = 21891, u64 = 4899968690100917635}}, {events = 32632, data = {ptr = 0x18, fd = 24, u32 = 24, u64 = 24}}, {events = 16, data = {ptr = 0x75d8f3b500000000, fd = 0, u32 = 0, u64 = 8491805056121700352}}, {events = 32632, data = {ptr = 0x7f7844002f80, fd = 1140862848, u32 = 1140862848, u64 = 140154513665920}}, {events = 1140869888, data = {ptr = 0x2000007f78, fd = 32632, u32 = 32632, u64 = 137438986104}}, {events = 0, data = {ptr = 0x33, fd = 51, u32 = 51, u64 = 51}}}
        ev = 0x7f786af2ca10
        e = {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}
#6  0x00005583368d7b5d in poller_loop2 (d=0x558336bea900) at poller.c:612
        ret = <optimized out>
        p = 0x558336bea900
#7  0x00005583368d7c92 in thread_detach_func (d=0x558336bc3900) at aux.c:210
        dt = 0x558336bc3900
        t = 0x558336bf1830
        scheduler = <optimized out>
#8  0x00007f78739fbea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140155167106816, -7070573090915023108, 140723879647646, 140723879647647, 140155167101312, 2105344, 7138366872706287356, 7138381345218692860}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#9  0x00007f787392bdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
rtpengine-daemon log:
```
Feb 02 07:12:33 rtpengine-host systemd[1]: Starting NGCP RTP/media Proxy Daemon...
Feb 02 07:12:33 rtpengine-host rtpengine-iptables-setup[8266]: modprobe: ERROR: could not insert 'xt_RTPENGINE': Operation not permitted
Feb 02 07:12:33 rtpengine-host rtpengine-iptables-setup[8273]: iptables v1.8.7 (nf_tables): unknown option "--id"
Feb 02 07:12:33 rtpengine-host rtpengine-iptables-setup[8273]: Try `iptables -h' or 'iptables --help' for more information.
Feb 02 07:12:33 rtpengine-host rtpengine-iptables-setup[8281]: ip6tables v1.8.7 (nf_tables): unknown option "--id"
Feb 02 07:12:33 rtpengine-host rtpengine-iptables-setup[8281]: Try `ip6tables -h' or 'ip6tables --help' for more information.
Feb 02 07:12:33 rtpengine-host rtpengine[8283]: INFO: [crypto] Generating new DTLS certificate
Feb 02 07:12:33 rtpengine-host rtpengine[8283]: ERR: [core] FAILED TO CREATE KERNEL TABLE 0 (No such file or directory), KERNEL FORWARDING DISABLED
Feb 02 07:12:33 rtpengine-host rtpengine[8283]: INFO: [core] Startup complete, version 9.5.3.3-1~bpo11+1
Feb 02 07:12:33 rtpengine-host systemd[1]: Started NGCP RTP/media Proxy Daemon.
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:32842: 19438_0 V
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:54288: 19439_0 V
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:54288: 19439_1 VF 20050322
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:32842: 19438_1 VF 20050322
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:54288: 19439_2 VF 20071116
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:50344: 19440_0 V
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:32842: 19438_2 VF 20071116
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:54288: 19439_3 VF 20081102
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:32842: 19438_3 VF 20081102
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:50344: 19440_1 VF 20050322
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:50344: 19440_2 VF 20071116
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:50344: 19440_3 VF 20081102
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:46085: 19443_0 V
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:46085: 19443_1 VF 20050322
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:46085: 19443_2 VF 20071116
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:46085: 19443_3 VF 20081102
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:58812: 19436_0 V
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:45427: 19435_0 V
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:40534: 19434_0 V
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:45427: 19435_1 VF 20050322
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:58812: 19436_1 VF 20050322
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:40534: 19434_1 VF 20050322
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:45427: 19435_2 VF 20071116
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:58812: 19436_2 VF 20071116
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:40534: 19434_2 VF 20071116
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:58812: 19436_3 VF 20081102
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:45427: 19435_3 VF 20081102
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:51950: 19437_0 V
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:40534: 19434_3 VF 20081102
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:51950: 19437_1 VF 20050322
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:51950: 19437_2 VF 20071116
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:51950: 19437_3 VF 20081102
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:35550: 19444_0 V
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:35550: 19444_1 VF 20050322
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:54887: 19445_0 V
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:35550: 19444_2 VF 20071116
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:44969: 19442_0 V
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:54887: 19445_1 VF 20050322
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:35550: 19444_3 VF 20081102
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:44969: 19442_1 VF 20050322
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:54887: 19445_2 VF 20071116
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:44969: 19442_2 VF 20071116
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:54887: 19445_3 VF 20081102
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:44969: 19442_3 VF 20081102
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:37112: 19441_0 V
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:37112: 19441_1 VF 20050322
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:37112: 19441_2 VF 20071116
Feb 02 07:13:11 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:37112: 19441_3 VF 20081102
Feb 02 07:13:19 rtpengine-host rtpengine[8283]: INFO: [control] Got valid command from udp:[kamailio rfc1918 addr]:58812: 19436_4 UAEIS 426522387_134215390@[remote public v4 addr] [internal rfc1918 addr] 33452 [internal rfc1918 addr]+1+417e1f+faf9e97c;1 gK0c49533b;1
Feb 02 07:13:19 rtpengine-host rtpengine[8283]: NOTICE: [426522387_134215390@[remote public v4 addr]]: [core] Creating new call
Feb 02 07:13:19 rtpengine-host systemd[1]: rtpengine-daemon.service: Main process exited, code=killed, status=11/SEGV
Feb 02 07:13:20 rtpengine-host systemd[1]: rtpengine-daemon.service: Failed with result 'signal'.
```
rtpengine.conf:
```
[rtpengine]
table = -1
interface = internal/[rfc1918 addr]];external/[public v4 addr]
listen-udp = [rfc1918 addr]:5050
timeout = 60
silent-timeout = 3600
tos = 184
port-min = 52000
port-max = 54024
```

Running on Debian 11:
```
root@rtpengine-host:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by rfuchs** [comment]
Out of curiosity, any particular reason why you're using the legacy protocol? It's barely maintained or even tested and I actually considered removing it in recent times.
