### ISSUE TITLE
spandsp_logging.h:5:2: error: too few arguments to function ‘span_log_set_message_handler’

### ISSUE THREAD

**Issue by zhangds007** [sipwise/rtpengine#1450]
Hi,

I meet this compile error in branch Master. Do you know how to solve it?

==============================
../utils/build_test_wrapper "spandsp_logging.h"
Looking for usable alternative for spandsp_logging.h
Trying build with ../lib/spandsp_logging-01.h
make[3]: Entering directory '/home/zds5gc/rtpengine/daemon'
cc -g -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include       -pthread     -I/usr/include    -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread       -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/x86_64-linux-gnu   -I/usr/include/x86_64-linux-gnu   -I/usr/include/x86_64-linux-gnu   -I/usr/include/x86_64-linux-gnu   -I/usr/include/x86_64-linux-gnu   -I/usr/local/include   -DWITH_TRANSCODING -I/usr/include/mysql  -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DHAVE_BCG729 -I/usr/local/include   -DHAVE_MQTT   -DRTPENGINE_VERSION="\"10.4.0.0+0~mr10.4.0.0 git-master-4eecec9a\""   -DHAVE_LIBSYSTEMD -g -O2 -fdebug-prefix-map=/home/zds5gc/rtpengine/daemon=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -rdynamic -Wl,-Bsymbolic-functions -Wl,-z,relro  spandsp_logging-test.c  -lm -lglib-2.0   -lgthread-2.0 -pthread -lglib-2.0   -lz   -lpcre   -lcrypto   -lssl -lcrypto   -levent_pthreads -levent   -lpcap -L/usr/lib/x86_64-linux-gnu   -lxmlrpc_client -lxmlrpc  -lxmlrpc_xmlparse -lxmlrpc_xmltok -lxmlrpc_util -lcurl    -lhiredis -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0   -lwebsockets -lcap   -lip4tc -lip6tc    -lavcodec    -lavformat    -lavutil    -lswresample    -lavfilter   -L/usr/local/lib -lspandsp   -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -latomic -ldl -L/usr/local/lib -lbcg729   -lmosquitto   -lsystemd    -o spandsp_logging-test
In file included from spandsp_logging-test.c:9:0:
spandsp_logging.h: In function ‘my_span_set_log’:
spandsp_logging.h:5:2: error: too few arguments to function ‘span_log_set_message_handler’
  span_log_set_message_handler(ls, h);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from spandsp_logging-test.c:7:0:
/usr/local/include/spandsp/logging.h:123:20: note: declared here
 SPAN_DECLARE(void) span_log_set_message_handler(logging_state_t *s, message_handler_func_t func, void *user_data);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from spandsp_logging-test.c:9:0:
spandsp_logging.h: In function ‘my_span_mh’:
spandsp_logging.h:8:2: error: too few arguments to function ‘span_set_message_handler’
  span_set_message_handler(h);
  ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from spandsp_logging-test.c:7:0:
/usr/local/include/spandsp/logging.h:125:20: note: declared here
 SPAN_DECLARE(void) span_set_message_handler(message_handler_func_t func, void *user_data);
                    ^~~~~~~~~~~~~~~~~~~~~~~~
spandsp_logging-test.c: In function ‘main’:
spandsp_logging-test.c:18:22: warning: passing argument 2 of ‘my_span_set_log’ from incompatible pointer type [-Wincompatible-pointer-types]
  my_span_set_log(ls, logfunc);
                      ^~~~~~~
In file included from spandsp_logging-test.c:9:0:
spandsp_logging.h:4:13: note: expected ‘message_handler_func_t {aka void (*)(void *, int,  const char *)}’ but argument is of type ‘void (*)(int,  const char *)’
 INLINE void my_span_set_log(logging_state_t *ls, message_handler_func_t h) {
             ^~~~~~~~~~~~~~~
<builtin>: recipe for target 'spandsp_logging-test' failed
make[3]: *** [spandsp_logging-test] Error 1
make[3]: Leaving directory '/home/zds5gc/rtpengine/daemon'
Failed build with ../lib/spandsp_logging-01.h
Trying build with ../lib/spandsp_logging-02.h

**Comment by rfuchs** [comment]
I don't think this shows the actual build error. Build should succeed with `spandsp_logging-02.h` as printed in the last line you posted.

**Comment by zhangds007** [comment]
yes. I check again. It is OK to build with ../lib/spandsp_logging-02.h.
but I do not know if this error is connected with error dpkg-buildpackage.

ERROR: testKeepalive (__main__.TestVideoroom)
==error dpkg-buildpackage   log===================================================
new call 606-test-callID-0.140303590634989
ok 1382 - SDP replace everything - 'offer' status
ok 1383 - SDP replace everything - output 'offer' SDP
ok 1384 - SDP replace everything - 'offer' status
ok 1385 - SDP replace everything - output 'offer' SDP
ok 1386 - SDP replace everything - 'offer' status
ok 1387 - SDP replace everything - output 'offer' SDP
1..1387
test "$(ls fake-daemon-tests-main-sockets)" = ""
rmdir fake-daemon-tests-main-sockets
EEEEEEEEEEEEEEE
======================================================================
ERROR: testKeepalive (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 329, in testKeepalive
    (token, session) = self.startSession()
  File "auto-daemon-tests-websocket.py", line 164, in startSession
    "admin_secret": "dfgdfgdvgLyATjHPvckg",
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 55, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomDTLS (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 794, in testVideoroomDTLS
    (token, session, control_handle, room) = self.startVideoroom()
  File "auto-daemon-tests-websocket.py", line 191, in startVideoroom
    (token, session) = self.startSession()
  File "auto-daemon-tests-websocket.py", line 164, in startSession
    "admin_secret": "dfgdfgdvgLyATjHPvckg",
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 55, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomICE (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 1363, in testVideoroomICE
    (token, session, control_handle, room) = self.startVideoroom()
  File "auto-daemon-tests-websocket.py", line 191, in startVideoroom
    (token, session) = self.startSession()
  File "auto-daemon-tests-websocket.py", line 164, in startSession
    "admin_secret": "dfgdfgdvgLyATjHPvckg",
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 55, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomPubSub (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 1668, in testVideoroomPubSub
    (token, session, control_handle, room) = self.startVideoroom()
  File "auto-daemon-tests-websocket.py", line 191, in startVideoroom
    (token, session) = self.startSession()
  File "auto-daemon-tests-websocket.py", line 164, in startSession
    "admin_secret": "dfgdfgdvgLyATjHPvckg",
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 55, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomSDES (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 706, in testVideoroomSDES
    (token, session, control_handle, room) = self.startVideoroom()
  File "auto-daemon-tests-websocket.py", line 191, in startVideoroom
    (token, session) = self.startSession()
  File "auto-daemon-tests-websocket.py", line 164, in startSession
    "admin_secret": "dfgdfgdvgLyATjHPvckg",
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 55, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomSDESDTLS (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 615, in testVideoroomSDESDTLS
    (token, session, control_handle, room) = self.startVideoroom()
  File "auto-daemon-tests-websocket.py", line 191, in startVideoroom
    (token, session) = self.startSession()
  File "auto-daemon-tests-websocket.py", line 164, in startSession
    "admin_secret": "dfgdfgdvgLyATjHPvckg",
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 55, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomWebRTC (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 339, in testVideoroomWebRTC
    (token, session, control_handle, room) = self.startVideoroom()
  File "auto-daemon-tests-websocket.py", line 191, in startVideoroom
    (token, session) = self.startSession()
  File "auto-daemon-tests-websocket.py", line 164, in startSession
    "admin_secret": "dfgdfgdvgLyATjHPvckg",
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 55, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomWebRTCVideo (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 986, in testVideoroomWebRTCVideo
    (token, session, control_handle, room) = self.startVideoroom()
  File "auto-daemon-tests-websocket.py", line 191, in startVideoroom
    (token, session) = self.startSession()
  File "auto-daemon-tests-websocket.py", line 164, in startSession
    "admin_secret": "dfgdfgdvgLyATjHPvckg",
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 55, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomWebrtcup (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 883, in testVideoroomWebrtcup
    (token, session, control_handle, room) = self.startVideoroom()
  File "auto-daemon-tests-websocket.py", line 191, in startVideoroom
    (token, session) = self.startSession()
  File "auto-daemon-tests-websocket.py", line 164, in startSession
    "admin_secret": "dfgdfgdvgLyATjHPvckg",
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 55, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testListNumsessions (__main__.TestWSCli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 89, in testListNumsessions
    self._eventloop.run_until_complete(testIO(self, "list numsessions"))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 29, in testIO
    await self._ws.send(msg)
AttributeError: 'TestWSCli' object has no attribute '_ws'

======================================================================
ERROR: testEcho (__main__.TestWSEcho)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 73, in testEcho
    self._eventloop.run_until_complete(testIO(self, b"foobar"))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 29, in testIO
    await self._ws.send(msg)
AttributeError: 'TestWSEcho' object has no attribute '_ws'

======================================================================
ERROR: testEchoText (__main__.TestWSEcho)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 77, in testEchoText
    self._eventloop.run_until_complete(testIO(self, "foobar"))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 29, in testIO
    await self._ws.send(msg)
AttributeError: 'TestWSEcho' object has no attribute '_ws'

======================================================================
ERROR: testInfo (__main__.TestWSJanus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 129, in testInfo
    testIOJson(self, {"janus": "info", "transaction": "foobar"})
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 34, in testIOJson
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestWSJanus' object has no attribute '_ws'

======================================================================
ERROR: testPing (__main__.TestWSJanus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 110, in testPing
    testIOJson(self, {"janus": "ping", "transaction": "test123"})
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 34, in testIOJson
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestWSJanus' object has no attribute '_ws'

======================================================================
ERROR: testPingNoTS (__main__.TestWSJanus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 115, in testPingNoTS
    self._eventloop.run_until_complete(testIOJson(self, {"janus": "ping"}))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "auto-daemon-tests-websocket.py", line 34, in testIOJson
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestWSJanus' object has no attribute '_ws'

----------------------------------------------------------------------
Ran 15 tests in 133.769s

FAILED (errors=15)
Traceback (most recent call last):
  File "auto-daemon-tests-websocket.py", line 2053, in <module>
    unittest.main()
  File "/usr/lib/python3.6/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python3.6/unittest/main.py", line 258, in runTests
    sys.exit(not self.result.wasSuccessful())
SystemExit: True
HINT: Stdout and stderr are /tmp/tmpwyg9odv_ and /tmp/tmp2w7gquce
Makefile:168: recipe for target 'daemon-tests-websocket' failed
make[3]: *** [daemon-tests-websocket] Error 1
rm sdp.strhash.c control_ng.strhash.c test-const_str_hash.strhash.c call_interfaces.strhash.c janus.strhash.c
make[3]: Leaving directory '/home/zds5gc/rtpengine/t'
../lib/common.Makefile:4: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/zds5gc/rtpengine/t'
Makefile:54: recipe for target 'check' failed
make[1]: *** [check] Error 2
make[1]: Leaving directory '/home/zds5gc/rtpengine'
dh_auto_test: make -j4 check returned exit code 2
debian/rules:33: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

**Comment by rfuchs** [comment]
What platform/OS/distro are you building this on?
