### ISSUE TITLE
crash in mr10.3

### ISSUE THREAD

**Issue by john08burke** [sipwise/rtpengine#1474]
When trying to upgrade to mr10.3, some of my SRTP unit tests are failing due to rtpengine crashing.  It's very likely that I wrote a bad SRTP unit test... but the dump indicates a double free.  They are signalling only (no RTP).  Let me know if you need any more info.

**Platform:**
- **OS**: debian 10
- **version**: latest mr10.3 branch

**Signaling**
Control protocol signal [here](https://github.com/sipwise/rtpengine/files/8401599/rtpengine_signal.txt).

**Backtrace:**

Full trace [here](https://github.com/sipwise/rtpengine/files/8401559/full_backtrace.txt)

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fb57eedf535 in __GI_abort () at abort.c:79
#2  0x00007fb57ef36518 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fb57f04028d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fb57ef3cc3a in malloc_printerr (str=str@entry=0x7fb57f041fe0 "double free or corruption (out)") at malloc.c:5359
#4  0x00007fb57ef3e770 in _int_free (av=0x7fb57f077c40 <main_arena>, p=0x7fb56c038030, have_lock=<optimized out>) at malloc.c:4321
#5  0x00007fb5826651c7 in g_hash_table_unref () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x000055a1b1db8c4d in free_attributes (a=a@entry=0x7fb56c016418) at sdp.strhash.c:1479
#7  0x000055a1b1dba696 in session_free (p=0x7fb56c016300) at sdp.strhash.c:1493
#8  g_queue_clear_full (free_func=<optimized out>, q=0x7fb56c01e120) at ../include/aux.h:152
#9  sdp_free (sessions=sessions@entry=0x7fb56c01e120) at sdp.strhash.c:1497
#10 0x000055a1b1dd0ccf in save_last_sdp (ml=0x7fb56c01e000, sdp=0x7fb5716ce4a0, parsed=0x7fb5716ce4b0, streams=0x7fb5716ce4d0) at call_interfaces.strhash.c:2226
#11 0x000055a1b1dd146c in call_offer_answer_ng (ngbuf=ngbuf@entry=0x55a1b3eddc60, input=<optimized out>, output=output@entry=0x7fb56c02da18, opmode=opmode@entry=OP_OFFER, 
    addr=addr@entry=0x7fb56c012ac8 "192.168.1.24:39849", sin=sin@entry=0x7fb56c012aa8) at call_interfaces.strhash.c:2369
#12 0x000055a1b1dd1e5d in call_offer_ng (ngbuf=ngbuf@entry=0x55a1b3eddc60, input=<optimized out>, output=output@entry=0x7fb56c02da18, addr=addr@entry=0x7fb56c012ac8 "192.168.1.24:39849", 
    sin=sin@entry=0x7fb56c012aa8) at call_interfaces.strhash.c:2417
#13 0x000055a1b1db7b26 in control_ng_process (buf=<optimized out>, sin=<optimized out>, addr=<optimized out>, cb=<optimized out>, p1=<optimized out>, ref=<optimized out>)
    at control_ng.strhash.c:396
#14 0x000055a1b1db6166 in udp_listener_incoming (fd=<optimized out>, x=<optimized out>, p=0x55a1b3eaed60) at udp_listener.c:54
#15 udp_listener_incoming (fd=<optimized out>, p=0x55a1b3eaed60, x=<optimized out>) at udp_listener.c:28
#16 0x000055a1b1d94d68 in poller_poll (p=0x55a1b3eb6610, timeout=<optimized out>) at poller.c:440
#17 0x000055a1b1d9545d in poller_loop2 (d=0x55a1b3eb6610) at poller.c:619
#18 0x000055a1b1d9564d in thread_detach_func (d=0x55a1b3e89260) at aux.c:250
#19 0x00007fb57f084fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#20 0x00007fb57efb5eff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by john08burke** [comment]
Valgrind output:
```
==566== Invalid free() / delete / delete[] / realloc()
==566==    at 0x48369AB: free (vg_replace_malloc.c:530)
==566==    by 0x15A445: sdp_streams_free (in /usr/sbin/rtpengine)
==566==    by 0x13DB72: ??? (in /usr/sbin/rtpengine)
==566==    by 0x15322C: control_ng_process (in /usr/sbin/rtpengine)
==566==    by 0x152165: ??? (in /usr/sbin/rtpengine)
==566==    by 0x130D67: poller_poll (in /usr/sbin/rtpengine)
==566==    by 0x13145C: poller_loop2 (in /usr/sbin/rtpengine)
==566==    by 0x13164C: ??? (in /usr/sbin/rtpengine)
==566==    by 0x847AFA2: start_thread (pthread_create.c:486)
==566==    by 0x858CEFE: clone (clone.S:95)
==566==  Address 0x13875750 is 0 bytes inside a block of size 32 free'd
==566==    at 0x48369AB: free (vg_replace_malloc.c:530)
==566==    by 0x1347F4: ??? (in /usr/sbin/rtpengine)
==566==    by 0x13A9CC: monologue_offer_answer (in /usr/sbin/rtpengine)
==566==    by 0x16D268: ??? (in /usr/sbin/rtpengine)
==566==    by 0x153B25: control_ng_process (in /usr/sbin/rtpengine)
==566==    by 0x152165: ??? (in /usr/sbin/rtpengine)
==566==    by 0x130D67: poller_poll (in /usr/sbin/rtpengine)
==566==    by 0x13145C: poller_loop2 (in /usr/sbin/rtpengine)
==566==    by 0x13164C: ??? (in /usr/sbin/rtpengine)
==566==    by 0x847AFA2: start_thread (pthread_create.c:486)
==566==    by 0x858CEFE: clone (clone.S:95)
==566==  Block was alloc'd at
==566==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==566==    by 0x159A0A: sdp_streams (in /usr/sbin/rtpengine)
==566==    by 0x16CEC4: ??? (in /usr/sbin/rtpengine)
==566==    by 0x153B25: control_ng_process (in /usr/sbin/rtpengine)
==566==    by 0x152165: ??? (in /usr/sbin/rtpengine)
==566==    by 0x130D67: poller_poll (in /usr/sbin/rtpengine)
==566==    by 0x13145C: poller_loop2 (in /usr/sbin/rtpengine)
==566==    by 0x13164C: ??? (in /usr/sbin/rtpengine)
==566==    by 0x847AFA2: start_thread (pthread_create.c:486)
==566==    by 0x858CEFE: clone (clone.S:95)
```

**Comment by rfuchs** [comment]
Do you have a log output from rtpengine (with debugging enabled) that would show the signalling? The raw dump of the network traffic is a little hard to use.

The valgrind output is _almost_ useful except that some of the file/line information is missing for some reason. Was the valgrind run done without debugging symbols installed?

**Comment by john08burke** [comment]
@rfuchs I installed the dbg packages and re-ran valgrind with debug logging enabled. Here is output: 
[debug.txt](https://github.com/sipwise/rtpengine/files/8428493/debug.txt).

**Comment by john08burke** [comment]
```
==7764== Invalid free() / delete / delete[] / realloc()
==7764==    at 0x48369AB: free (vg_replace_malloc.c:530)
==7764==    by 0x15A445: crypto_params_cleanup (crypto.h:149)
==7764==    by 0x15A445: crypto_params_sdes_free (crypto.h:204)
==7764==    by 0x15A445: g_queue_clear_full (aux.h:152)
==7764==    by 0x15A445: crypto_params_sdes_queue_clear (crypto.h:208)
==7764==    by 0x15A445: sp_free (sdp.strhash.c:1901)
==7764==    by 0x15A445: g_queue_clear_full (aux.h:152)
==7764==    by 0x15A445: sdp_streams_free (sdp.strhash.c:1905)
==7764==    by 0x16CCFB: save_last_sdp (call_interfaces.strhash.c:2230)
==7764==    by 0x16D46B: call_offer_answer_ng (call_interfaces.strhash.c:2369)
==7764==    by 0x153C7E: control_ng_process (control_ng.strhash.c:400)
==7764==    by 0x152165: udp_listener_incoming (udp_listener.c:54)
==7764==    by 0x152165: udp_listener_incoming (udp_listener.c:28)
==7764==    by 0x130D67: poller_poll (poller.c:440)
==7764==    by 0x13145C: poller_loop2 (poller.c:619)
==7764==    by 0x13164C: thread_detach_func (aux.c:250)
==7764==    by 0x8080FA2: start_thread (pthread_create.c:486)
==7764==    by 0x8192EFE: clone (clone.S:95)
==7764==  Address 0x1341be70 is 0 bytes inside a block of size 32 free'd
==7764==    at 0x48369AB: free (vg_replace_malloc.c:530)
==7764==    by 0x1347F4: crypto_params_cleanup (crypto.h:149)
==7764==    by 0x1347F4: crypto_params_copy (crypto.h:166)
==7764==    by 0x1347F4: crypto_params_sdes_queue_copy (crypto.h:215)
==7764==    by 0x1347F4: __media_init_from_flags (call.c:2644)
==7764==    by 0x13A9CC: monologue_offer_answer (call.c:2753)
==7764==    by 0x16D268: call_offer_answer_ng (call_interfaces.strhash.c:2356)
==7764==    by 0x153B25: control_ng_process (control_ng.strhash.c:396)
==7764==    by 0x152165: udp_listener_incoming (udp_listener.c:54)
==7764==    by 0x152165: udp_listener_incoming (udp_listener.c:28)
==7764==    by 0x130D67: poller_poll (poller.c:440)
==7764==    by 0x13145C: poller_loop2 (poller.c:619)
==7764==    by 0x13164C: thread_detach_func (aux.c:250)
==7764==    by 0x8080FA2: start_thread (pthread_create.c:486)
==7764==    by 0x8192EFE: clone (clone.S:95)
==7764==  Block was alloc'd at
==7764==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==7764==    by 0x159A0A: sdp_streams (sdp.strhash.c:1795)
==7764==    by 0x16CEC4: call_offer_answer_ng (call_interfaces.strhash.c:2278)
==7764==    by 0x153B25: control_ng_process (control_ng.strhash.c:396)
==7764==    by 0x152165: udp_listener_incoming (udp_listener.c:54)
==7764==    by 0x152165: udp_listener_incoming (udp_listener.c:28)
==7764==    by 0x130D67: poller_poll (poller.c:440)
==7764==    by 0x13145C: poller_loop2 (poller.c:619)
==7764==    by 0x13164C: thread_detach_func (aux.c:250)
==7764==    by 0x8080FA2: start_thread (pthread_create.c:486)
==7764==    by 0x8192EFE: clone (clone.S:95)
```

**Comment by rfuchs** [comment]
Perfect, thanks. Patch is on its way.

**Comment by john08burke** [comment]
Thanks @rfuchs!

Could you clarify how the branch versioning works? I was expecting that mr10.X would contain all the commits up to the latest mr10.X.Y (so mr10.3 would be the same as mr10.3.1 in this case... and then eventually mr10.3.2), but that doesn't seem to be the case.  If I was to use 10.3, should I be on the latest mr10.3.Y branch instead of the mr10.3 branch?

**Comment by rfuchs** [comment]
mr10.3 is not LTS therefore there never will be an mr10.3.2. So in this case you're quite right that mr10.3 should always be the same as mr10.3.1 (and indeed it is). Then periodically tagged mr10.3.1.X releases are created from mr10.3.1, usually when there was a change significant enough to warrant creating a new tag/release, so the latest mr10.3.1.X is not always the same as mr10.3(.1). IOW unless you care about tagged releases you can use either mr10.3 or mr10.3.1.

**Comment by john08burke** [comment]
Ahh, I was thinking it was LTS. Is there a wiki or docs page that lists the LTS versions? If not, how do I ensure that I'm running an LTS version? Thanks!

**Comment by rfuchs** [comment]
mrX.5 are the LTS branches.
