### ISSUE TITLE
DTMF event shuts down transcoder

### ISSUE THREAD

**Issue by szcom** [sipwise/rtpengine#1504]
Rtpengine 06ee68b0c641ad57cb38295157a8fac328f3d34d (11), libopencore-amrwb0_0.1.5
Config options: -t -1 --dtx-delay 20 --max-dtx 0

AMR/WB to PCMA transcoding works until DTMF events start coming from the AMR side. 

After DTMF from AMR/WB side, media sent to PCMA side has gaps up to 30 seconds. 

<img width="981" alt="image" src="https://user-images.githubusercontent.com/1636682/173815084-8b7759ac-f79a-4f58-812a-a9cc0a03b1b7.png">

Looking at the output, the following script fails to reproduce the issue, but still shows the SDPs flows
 
```
#!/usr/bin/perl

#mkdir /tmp/fs1
#RTPENGINE_HOST=localhost RTPE_TEST_NO_LAUNCH=1 RTPE_BIN=/rtpengine/daemon/rtpengine TEST_SOCKET_PATH=/tmp/fs1 perl -I../perl tg.pl
use strict;
use warnings;
use NGCP::Rtpengine::Test;
use NGCP::Rtpclient::SRTP;
use NGCP::Rtpengine::AutoTest;
use Test::More;
use POSIX;
use Time::HiRes;
use Time::HiRes qw(time);


autotest_start(qw(-t -1 -i 203.0.113.1/203.0.113.1 -i 2001:db8:4321::1/2001:db8:4321::1
			-n 2223 -c 12345 -f -L 7 -E -u 2222 --dtx-delay 30 --max-dtx 0 --silence-detect 0.05 ))
		or die;

sub show_ts
{
  my $t = time;
  my $date = strftime "%Y%m%d %H:%M:%S", localtime $t;
  $date .= sprintf ".%03d", ($t-int($t))*1000; # without rounding

  print $date, " at $_[0]\n";
}

#my $amr_tests = (POSIX::uname())[1] eq 'moose';
my $amr_tests = 0;



my ($sock_a, $sock_b, $sock_c, $sock_d, $port_a, $port_b, $ssrc, $ssrc_b, $resp,
	$sock_ax, $sock_bx, $port_ax, $port_bx,
	$srtp_ctx_a, $srtp_ctx_b, $srtp_ctx_a_rev, $srtp_ctx_b_rev,
	@ret1, @ret2, @ret3, @ret4, $srtp_key_a, $srtp_key_b, $ts, $seq);




($sock_a, $sock_b) = new_call([qw(172.17.0.2 4024)], [qw(172.17.0.2 4026)]);

($port_a) = offer('AMR SID',
	{ ICE => 'remove', replace => ['origin'], codec => { transcode => ['PCMA','telephone-event'],
	'set' => ['AMR-WB/16000/1/23850'] } }, <<SDP);
v=0
o=- 1545997027 1 IN IP4 172.17.0.2
s=tester
t=0 0
m=audio 4024 RTP/AVP 96 105
a=maxptime:240
c=IN IP4 172.17.0.2
a=rtpmap:96 AMR-WB/16000
a=fmtp:96 max-red=220; mode-change-capability=2
a=rtpmap:105 telephone-event/16000
a=fmtp:105 0-15
a=sendrecv
a=ptime20
----------------------------------
v=0
o=- 1545997027 1 IN IP4 172.17.0.2
s=tester
t=0 0
m=audio PORT RTP/AVP 96 8 97 105
a=maxptime:240
c=IN IP4 172.17.0.2
a=ptime20
a=rtpmap:96 AMR-WB/16000
a=fmtp:96 max-red=220; mode-change-capability=2
a=rtpmap:8 PCMA/8000
a=rtpmap:97 telephone-event/8000
a=fmtp:97 0-15
a=rtpmap:105 telephone-event/16000
a=fmtp:105 0-15
a=sendrecv
a=rtcp:PORT
SDP

($port_b) = answer('AMR SID',
	{ ICE => 'remove', replace => ['origin'] }, <<SDP);
v=0
o=- 1545997027 1 IN IP4 172.17.0.2
s=tester
t=0 0
m=audio 4026 RTP/AVP 8 100
c=IN IP4 172.17.0.2
a=rtpmap:100 telephone-event/8000
a=fmtp:100 0-16
a=sendrecv
a=ptime:20
--------------------------------------
v=0
o=- 1545997027 1 IN IP4 172.17.0.2
s=tester
t=0 0
m=audio PORT RTP/AVP 96 105
c=IN IP4 172.17.0.2
a=rtpmap:96 AMR-WB/16000
a=fmtp:96 max-red=220; mode-change-capability=2
a=rtpmap:105 telephone-event/16000
a=fmtp:105 0-15
a=sendrecv
a=rtcp:PORT
a=ptime:20
SDP


snd($sock_a, $port_b, rtp(96, 255, 4456181, 0x5678, "\xf4\xf5\xff\xdf\x7c\x5c\x80"), "172.17.0.2");
Time::HiRes::usleep(20000); # 20 ms
snd($sock_a, $port_b, rtp(96, 256, 4458741, 0x5678, "\xf4\xfa\xff\xdf\x6c\x64\x80"), "172.17.0.2");
Time::HiRes::usleep(20000); # 20 ms
snd($sock_a, $port_b, rtp(96, 257, 4461301, 0x5678, "\xf4\xf8\xf7\xcf\x6c\x6c\x80"), "172.17.0.2");
Time::HiRes::usleep(20000); # 20 ms
snd($sock_a, $port_b, rtp(96, 258, 4463861, 0x5678, "\xf4\xfb\xff\xef\x6c\x7c\x80"), "172.17.0.2");
show_ts("send 1st packet");
Time::HiRes::usleep(15000); # 20 ms
snd($sock_a, $port_b, rtp(96, 259, 4466421, 0x5678, "\xf4\xf8\xff\xef\x7c\xac\x80"), "172.17.0.2");
Time::HiRes::usleep(15000); # 20 ms
snd($sock_a, $port_b, rtp(96, 260, 4466741, 0x5678, "\xf1\x66\x8b\xf3\xee\xa9\xc2\x41\xb0\xc0\x8c\x18\x85\x05\xe1\xf2\xcb\xee\x22\x0a\x47\x61\x24\x9e\x27\x6c\x6f\x75\xf6\x8e\xbb\xf2\x3e"
), "172.17.0.2");
Time::HiRes::usleep(28000); # 20 ms
snd($sock_a, $port_b, rtp(96, 261, 4467061, 0x5678, "\xf1\x74\x07\x68\x1c\x5d\x3c\x42\xcb\x9b\x69\x99\x15\x0b\xa0\xce\xe5\xb8\x6a\x04\x30\x3b\x7a\x60\x4a\x10\xaf\x77\xdf\x0e\x93\x08\xc6"
), "172.17.0.2");
show_ts("send 2nd packet");
($ssrc) = rcv($sock_b, $port_a, rtpm(8, 2000, 4000, -1, "\xd5\xd5\xd5\xd5\xd5\xd5\xd5\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\xd5\x55\x55\xd5\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\xd5\x55\xd5\x55\xd4\xd4\xd7\xd4\xd7\xd5\xd0\x52\x72\x64\x66\x66\x66\x66\x67\x67\x67\x65\x7a\x79\x7c\x72\x70\x77\x75\x4e\x43\x47\x5b\x5c\x5d\x55\x5d\x71\x7e\x7b\x79\x7e\x7c\x7d\x73\x70\x77\x4b\x4c\x45\xc1\xf0\xf1\xfd\xf8\xfa\xe5\xe7\xe6\xe6\xe1\xe6\xe0\xe0\xe1\xe0\xe3\xe2\xe2\xe2\xed\xec\xef\xec\xec\xec\xed\xe2\xe3\xe3\xe1\xe1\xe7\xe7\xe7\xe5\xe5\xfa\xfa\xfb\xfb\xfb\xff\xfc\xf2\xf3\xf1\xf6\xf7\xf4\xf5\xcb\xce\xcd\xc3\xc1\xc7\xd8\xd9\xdf\xdc\xd3\xd3\xd7\x54\x51\x53\x5c\x5c\x5f\x5e\x58\x5a\x44"));
show_ts("recv 1st packet");
show_ts("start tx");
# start sending DTMF

snd($sock_a, $port_b, rtp(105, 262, 4468061, 0x56799, "\x01\x00\x03\xc0"), "172.17.0.2");
snd($sock_a, $port_b, rtp(105, 263, 4468061, 0x56799, "\x01\x00\x07\x80"), "172.17.0.2");
snd($sock_a, $port_b, rtp(105, 264, 4468061, 0x56799, "\x01\x80\x08\xc0"), "172.17.0.2");
snd($sock_a, $port_b, rtp(96, 268, 4467081, 0x5678, "\xf4\xf8\xff\xef\x7c\xac\x80"), "172.17.0.2");
snd($sock_a, $port_b, rtp(96, 269, 4467101, 0x5678, "\xf4\xf8\xff\xef\x7c\xac\x80"), "172.17.0.2");
snd($sock_a, $port_b, rtp(105, 265, 4468061, 0x56799, "\x01\x80\x08\xc0"), "172.17.0.2");
snd($sock_a, $port_b, rtp(105, 266, 4468061, 0x56799, "\x01\x80\x08\xc0"), "172.17.0.2");
sleep(1); 
snd($sock_a, $port_b, rtp(96, 270, 4468121, 0x5678, "\xf4\xf8\xff\xef\x7c\xac\x80"), "172.17.0.2");
snd($sock_a, $port_b, rtp(96, 271, 4468141, 0x5678, "\xf4\xf8\xff\xef\x7c\xac\x80"), "172.17.0.2");
sleep(1); 
show_ts("send 1st packet");


rtpe_req('delete', 'AMR SID', { 'from-tag' => ft() });





NGCP::Rtpengine::AutoTest::terminate('f00');
done_testing();


```

**Comment by rfuchs** [comment]
Do you have a pcap that I can use to try to replicate this?

**Comment by szcom** [comment]
needs more safe guards

```
#0  __dtx_send_later (ct=0x7f30ac03fc10) at codec.c:3006
#1  0x000055a6fd3b24e5 in timerthread_run (p=0x55a6fd410220 <codec_timers_thread>) at timerthread.c:62
#2  0x000055a6fd32d7ac in thread_detach_func (d=0x55a6fd852ec0) at aux.c:250
#3  0x00007f30cdedbea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#4  0x00007f30cde0bdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by szcom** [comment]
initial tests look promising

**Comment by szcom** [comment]
seems to be the fix
