### ISSUE TITLE
rtpengine carsh with signal 11, Segmentation fault.

### ISSUE THREAD

**Issue by aofei0721** [sipwise/rtpengine#1511]
Missing separate debuginfo for /lib64/libevent_pthreads-2.0.so.5
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/aa/b5d7da54013a24388b38e77d0181027f60e2da.debug
Missing separate debuginfo for /lib64/libevent-2.0.so.5
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/fa/fe26a6aca753913be50c41e96e498b09df5265.debug
Missing separate debuginfo for /lib64/libhiredis.so.0.12
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/fd/1dce3bec148e651cfdd673b5fd1b197a6d9168.debug
Missing separate debuginfo for /lib64/libjson-glib-1.0.so.0
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/8c/bde40e56caf8f09ad78d9e2295cb9fa8ff3628.debug
Missing separate debuginfo for /lib64/libwebsockets.so.13
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/2f/721c51c3b56f8078f98b7fea75cad67200b747.debug
Missing separate debuginfo for /lib64/libspandsp.so.2
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/63/9de5217f55dbecff3742d57b24086985dc9bfe.debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /lib64/libuv.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/19/f5c1eda5ffdc5161a65c04c6831282e25733fe.debug
Core was generated by `rtpengine --config-file=/usr/local/etc/rtpengine/rtpengine.conf'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fdf1845fd51 in __strnlen_sse2 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 elfutils-libelf-0.168-8.el7.x86_64 elfutils-libs-0.168-8.el7.x86_64 glib2-2.50.3-3.el7.x86_64 glibc-2.17-196.el7.x86_64 iptables-1.4.21-18.0.1.el7.centos.x86_64 jbigkit-libs-2.0-11.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 libattr-2.4.46-12.el7.x86_64 libblkid-2.23.2-43.el7.x86_64 libcap-2.22-9.el7.x86_64 libcom_err-1.42.9-10.el7.x86_64 libffi-3.0.13-18.el7.x86_64 libgcc-4.8.5-16.el7.x86_64 libgcrypt-1.5.3-14.el7.x86_64 libgpg-error-1.12-3.el7.x86_64 libjpeg-turbo-1.2.1-3.el6_5.x86_64 libjpeg-turbo-1.2.90-5.el7.x86_64 libmount-2.23.2-43.el7.x86_64 libpcap-1.5.3-9.el7.x86_64 libselinux-2.5-11.el7.x86_64 libstdc++-4.8.5-16.el7.x86_64 libtiff-4.0.3-27.el7_3.x86_64 libuuid-2.23.2-43.el7.x86_64 libxml2-2.9.1-6.el7_2.3.x86_64 mariadb-libs-5.5.56-2.el7.x86_64 openssl-libs-1.0.2k-8.el7.x86_64 systemd-libs-219-42.el7.x86_64 xmlrpc-c-1.32.5-1905.svn2451.el7.x86_64 xmlrpc-c-client-1.32.5-1905.svn2451.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.3-29.el6.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) where
#0  0x00007fdf1845fd51 in __strnlen_sse2 () from /lib64/libc.so.6
#1  0x00007fdf184214b8 in vfprintf () from /lib64/libc.so.6
#2  0x00007fdf1844d1b9 in vsnprintf () from /lib64/libc.so.6
#3  0x00007fdf1842a962 in snprintf () from /lib64/libc.so.6
#4  0x00000000004b403b in ilog_prefix_default (prefix=0x7fdd137f9960 "[\220U\030\337\177", prefix_len=300) at log.c:57
#5  0x00000000004b43ce in __ilog (prio=6, fmt=0x561f50 "[%s] Detected command from %s as a duplicate") at log.c:108
#6  0x000000000046bacf in control_ng_process (buf=0x7fdd00013a98, sin=0x7fdd00013aa8, addr=0x7fdd00013ac8 "10.X.X.33:58788",
    cb=0x46dcef <control_ng_send>, p1=0x1e30068, ref=0x7fdd00003800) at control_ng.strhash.c:346
#7  0x000000000046de38 in control_ng_incoming (obj=0x1e30050, udp_buf=0x7fdd00003800) at control_ng.strhash.c:598
#8  0x000000000046a9ac in udp_listener_incoming (fd=6, p=0x1e28960, x=0) at udp_listener.c:54
#9  0x0000000000424030 in poller_poll (p=0x1e2a200, timeout=10000) at poller.c:440
#10 0x0000000000424b2a in poller_loop2 (d=0x1e2a200) at poller.c:619
#11 0x000000000042591c in thread_detach_func (d=0x1e419a0) at aux.c:250
#12 0x00007fdf189a7e25 in start_thread () from /lib64/libpthread.so.0
#13 0x00007fdf184d134d in clone () from /lib64/libc.so.6

**Comment by rfuchs** [comment]
Which version and what's the build and runtime environment?

**Comment by aofei0721** [comment]
centos7.4 and rtpengine version is mr10.5.1
