### ISSUE TITLE
Build error on Ubuntu 22.04

### ISSUE THREAD

**Issue by dominikmauritz** [sipwise/rtpengine#1549]
Hi there,

I'm trying to build rtpengine on Ubuntu 22.04 (tested with 10.5 and 11.1) and I'm running into the following errors:

```
======================================================================
ERROR: testKeepalive (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 344, in testKeepalive
    (token, session) = self.startSession()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 173, in startSession
    eventloop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 58, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomDTLS (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 809, in testVideoroomDTLS
    (token, session, control_handle, room) = self.startVideoroom()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 206, in startVideoroom
    (token, session) = self.startSession()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 173, in startSession
    eventloop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 58, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomICE (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 1378, in testVideoroomICE
    (token, session, control_handle, room) = self.startVideoroom()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 206, in startVideoroom
    (token, session) = self.startSession()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 173, in startSession
    eventloop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 58, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomPubSub (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 1683, in testVideoroomPubSub
    (token, session, control_handle, room) = self.startVideoroom()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 206, in startVideoroom
    (token, session) = self.startSession()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 173, in startSession
    eventloop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 58, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomSDES (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 721, in testVideoroomSDES
    (token, session, control_handle, room) = self.startVideoroom()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 206, in startVideoroom
    (token, session) = self.startSession()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 173, in startSession
    eventloop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 58, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomSDESDTLS (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 630, in testVideoroomSDESDTLS
    (token, session, control_handle, room) = self.startVideoroom()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 206, in startVideoroom
    (token, session) = self.startSession()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 173, in startSession
    eventloop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 58, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomWebRTC (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 354, in testVideoroomWebRTC
    (token, session, control_handle, room) = self.startVideoroom()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 206, in startVideoroom
    (token, session) = self.startSession()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 173, in startSession
    eventloop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 58, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomWebRTCVideo (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 1001, in testVideoroomWebRTCVideo
    (token, session, control_handle, room) = self.startVideoroom()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 206, in startVideoroom
    (token, session) = self.startSession()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 173, in startSession
    eventloop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 58, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: testVideoroomWebrtcup (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 898, in testVideoroomWebrtcup
    (token, session, control_handle, room) = self.startVideoroom()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 206, in startVideoroom
    (token, session) = self.startSession()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 173, in startSession
    eventloop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 58, in testIOJanus
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestVideoroom' object has no attribute '_ws'

======================================================================
ERROR: tearDownClass (__main__.TestVideoroom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 166, in tearDownClass
    eventloop.run_until_complete(cls._ws.close())
AttributeError: type object 'TestVideoroom' has no attribute '_ws'

======================================================================
ERROR: testListNumsessions (__main__.TestWSCli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 98, in testListNumsessions
    eventloop.run_until_complete(testIO(self, "list numsessions"))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 32, in testIO
    await self._ws.send(msg)
AttributeError: 'TestWSCli' object has no attribute '_ws'

======================================================================
ERROR: tearDownClass (__main__.TestWSCli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 94, in tearDownClass
    eventloop.run_until_complete(cls._ws.close())
AttributeError: type object 'TestWSCli' has no attribute '_ws'

======================================================================
ERROR: testEcho (__main__.TestWSEcho)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 79, in testEcho
    eventloop.run_until_complete(testIO(self, b"foobar"))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 32, in testIO
    await self._ws.send(msg)
AttributeError: 'TestWSEcho' object has no attribute '_ws'

======================================================================
ERROR: testEchoText (__main__.TestWSEcho)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 83, in testEchoText
    eventloop.run_until_complete(testIO(self, "foobar"))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 32, in testIO
    await self._ws.send(msg)
AttributeError: 'TestWSEcho' object has no attribute '_ws'

======================================================================
ERROR: tearDownClass (__main__.TestWSEcho)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 76, in tearDownClass
    eventloop.run_until_complete(cls._ws.close())
AttributeError: type object 'TestWSEcho' has no attribute '_ws'

======================================================================
ERROR: testInfo (__main__.TestWSJanus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 140, in testInfo
    eventloop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 37, in testIOJson
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestWSJanus' object has no attribute '_ws'

======================================================================
ERROR: testPing (__main__.TestWSJanus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 121, in testPing
    eventloop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 37, in testIOJson
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestWSJanus' object has no attribute '_ws'

======================================================================
ERROR: testPingNoTS (__main__.TestWSJanus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 127, in testPingNoTS
    eventloop.run_until_complete(testIOJson(self, {"janus": "ping"}))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 37, in testIOJson
    await self._ws.send(json.dumps(msg))
AttributeError: 'TestWSJanus' object has no attribute '_ws'

======================================================================
ERROR: tearDownClass (__main__.TestWSJanus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 118, in tearDownClass
    eventloop.run_until_complete(cls._ws.close())
AttributeError: type object 'TestWSJanus' has no attribute '_ws'

----------------------------------------------------------------------
Ran 15 tests in 120.928s

FAILED (errors=19)
Traceback (most recent call last):
  File "/usr/src/rtpengine/t/auto-daemon-tests-websocket.py", line 2070, in <module>
    unittest.main()
  File "/usr/lib/python3.10/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/usr/lib/python3.10/unittest/main.py", line 273, in runTests
    sys.exit(not self.result.wasSuccessful())
SystemExit: True
HINT: Stdout and stderr are /tmp/tmpygz8f8ht and /tmp/tmppfuaqz3c
make[3]: *** [Makefile:182: daemon-tests-websocket] Error 1
rm control_ng.strhash.c sdp.strhash.c janus.strhash.c call_interfaces.strhash.c test-const_str_hash.strhash.c
make[3]: Leaving directory '/usr/src/rtpengine/t'
make[2]: *** [../lib/common.Makefile:4: all] Error 2
make[2]: Leaving directory '/usr/src/rtpengine/t'
make[1]: *** [Makefile:54: check] Error 2
make[1]: Leaving directory '/usr/src/rtpengine'
dh_auto_test: error: make -j8 check returned exit code 2
make: *** [debian/rules:31: build] Error 255
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

I'm using websockets on that server and have libwebsockets installed.

**Comment by rfuchs** [comment]
Do you also have python3-websockets installed?

**Comment by dominikmauritz** [comment]
Yes python3-webockets is installed

```
# dpkg -l |grep python3-websockets
ii  python3-websockets                    9.1-1                                   all          implementation of the WebSocket Protocol (RFC 6455)
```

I forgot to mention that this server was upgraded from Ubuntu 20.04 running rtpengine 10.2.0.0 to Ubuntu 22.04, but I don't think that has any implications

**Comment by linuxmaniac** [comment]
yes, same here. I've just enabled jammy on our nightly builds to check

https://kamailio.sipwise.com/view/rtpengine/job/rtpengine-nightly-binaries/architecture=amd64,distribution=jammy/119/consoleText

**Comment by linuxmaniac** [comment]
on [bookworm](https://kamailio.sipwise.com/view/rtpengine/job/rtpengine-nightly-binaries/architecture=amd64,distribution=bookworm/119/consoleText) we have no issues
```
python3-websockets all 10.2-1
```

on [bullseye](https://kamailio.sipwise.com/view/rtpengine/job/rtpengine-nightly-binaries/architecture=amd64,distribution=bullseye/119/consoleText) we have no issues either
```
python3-websockets all 8.1-1
```

**Comment by linuxmaniac** [comment]
It seems that python3-websockets 9.1 doesn't work for [python 3.10](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008598)

**Comment by dominikmauritz** [comment]
Interesting! Thanks for looking into it.

So waiting for Ubuntu to update to python3-websockets version 10 is the best option?

**Comment by linuxmaniac** [comment]
@dominikmauritz or just install python3-websockets from kinetic for instance:
http://de.archive.ubuntu.com/ubuntu/pool/universe/p/python-websockets/python3-websockets_10.2-1_all.deb

**Comment by dominikmauritz** [comment]
Tried that on my test server. Works. Thanks @linuxmaniac and @rfuchs for your help!

Closing this issue.
