### ISSUE TITLE
Build error on Debian 11

### ISSUE THREAD

**Issue by kovalyshyn** [sipwise/rtpengine#1570]
I'm trying to build mr10 or mr11 on Debian 11. All dependencies are installed (2 months ago all build fine). Now I get this error:

```
dpkg-checkbuilddeps


dpkg-buildpackage --no-sign

dpkg-buildpackage: info: source package ngcp-rtpengine
dpkg-buildpackage: info: source version 11.1.1.2+0~mr11.1.1.2
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Sipwise Jenkins Builder <jenkins@sipwise.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
dpkg-source: info: using options from rtpengine/debian/source/options: --extend-diff-ignore=.gitreview
 fakeroot debian/rules clean
dh clean
   dh_auto_clean
        make -j32 distclean
make[1]: Entering directory '/mnt/md1/RTP/rtpengine'

[....]

new call 630-test-callID-0.396171338457766
ok 1464 - SDP version string lengths - 'offer' status
ok 1465 - SDP version string lengths - output 'offer' SDP
ok 1466 - SDP version string lengths - 'offer' status
ok 1467 - SDP version string lengths - output 'offer' SDP
ok 1468 - SDP version string lengths - 'offer' status
ok 1469 - SDP version string lengths - output 'offer' SDP
ok 1470 - SDP version string lengths - 'offer' status
ok 1471 - SDP version string lengths - output 'offer' SDP
ok 1472 - SDP version string lengths - 'offer' status
ok 1473 - SDP version string lengths - output 'offer' SDP
new call 633-test-callID-0.396171338457766
ok 1474 - SDP replace everything - 'offer' status
ok 1475 - SDP replace everything - output 'offer' SDP
ok 1476 - SDP replace everything - 'offer' status
ok 1477 - SDP replace everything - output 'offer' SDP
ok 1478 - SDP replace everything - 'offer' status
ok 1479 - SDP replace everything - output 'offer' SDP
new call 636-test-callID-0.396171338457766
ok 1480 - GH \#1461 - 'offer' status
ok 1481 - GH \#1461 - output 'offer' SDP
new call 639-test-callID-0.396171338457766
ok 1482 - GH \#1461 - 'offer' status
ok 1483 - GH \#1461 - output 'offer' SDP
new call 642-test-callID-0.396171338457766
ok 1484 - MKI re-invite (GH \#1474) - 'offer' status
ok 1485 - MKI re-invite (GH \#1474) - output 'offer' SDP
ok 1486 - MKI re-invite (GH \#1474) - 'offer' status
ok 1487 - MKI re-invite (GH \#1474) - output 'offer' SDP
1..1487
test "$(ls fake-daemon-tests-main-sockets)" = ""
rmdir fake-daemon-tests-main-sockets
rm control_ng.strhash.c sdp.strhash.c janus.strhash.c call_interfaces.strhash.c test-const_str_hash.strhash.c
make[3]: Leaving directory '/mnt/md1/RTP/rtpengine/t'
make[2]: *** [../lib/common.Makefile:4: all] Error 2
make[2]: Leaving directory '/mnt/md1/RTP/rtpengine/t'
make[1]: *** [Makefile:54: check] Error 2
make[1]: Leaving directory '/mnt/md1/RTP/rtpengine'
dh_auto_test: error: make -j32 check returned exit code 2
make: *** [debian/rules:31: build] Error 255
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

```

**Comment by rfuchs** [comment]
Post the full log as this doesn't show the actual error

**Comment by kovalyshyn** [comment]
Building output:

[bash-tmux.log](https://github.com/sipwise/rtpengine/files/10093028/bash-tmux.log)

**Comment by rfuchs** [comment]
```
Traceback (most recent call last):
  File "/mnt/md1/RTP/rtpengine/t/auto-daemon-tests-websocket.py", line 14, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'
```

Do you have python3-websockets installed?

**Comment by kovalyshyn** [comment]
```
(base) [samael@ai ~]$  dpkg -l | grep websock

ii  libwebsockets-dev:amd64                                     4.0.20-2                         amd64        lightweight C websockets library - development files
ii  libwebsockets16:amd64                                       4.0.20-2                         amd64        lightweight C websockets library
ii  python3-websockets                                          8.1-1                            all          implementation of the WebSocket Protocol (RFC 6455)
```

**Comment by kovalyshyn** [comment]
Intresting....

I've just tested:

```
(base) [samael@ai ~]$ dpkg -l | grep 3-websockets
ii  python3-websockets                                          8.1-1                            all          implementation of the WebSocket Protocol (RFC 6455)
(base) [samael@ai ~]$ echo "import websockets" > test-ws.py 
(base) [samael@ai ~]$ python test-ws.py 
Traceback (most recent call last):
  File "/home/samael/test-ws.py", line 1, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'
```

After that I've created a new python anv and install websockets inside it:

```
(base) [samael@ai ~]$ conda activate pyDev
(pyDev) [samael@ai ~]$ conda install -c conda-forge websockets
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: done
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /mnt/md1/miniconda3/envs/pyDev

  added / updated specs:
    - websockets


The following NEW packages will be INSTALLED:

  python_abi         conda-forge/linux-64::python_abi-3.10-2_cp310 None
  websockets         conda-forge/linux-64::websockets-10.3-py310h5764c6d_0 None

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2022.10.11~ --> conda-forge::ca-certificates-2022.9.24-ha878542_0 None
  certifi            pkgs/main/linux-64::certifi-2022.9.24~ --> conda-forge/noarch::certifi-2022.9.24-pyhd8ed1ab_0 None

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done

(pyDev) [samael@ai ~]$ echo "import websockets" > test-ws.py 
(pyDev) [samael@ai ~]$ python test-ws.py 
```

Now, I compiled rtpengine successful.
