### ISSUE TITLE
rtpengine: kernel.c:63: kernel_alloc: Assertion `b != NULL && b != MAP_FAILED' failed

### ISSUE THREAD

**Issue by sergey-safarov** [sipwise/rtpengine#1843]
### rtpengine version the issue has been seen with

12.4.1.7

### Used distribution and its version

CentOS Stream 8

### Linux kernel version used

Linux sbc-stage-a0.nga911.com 4.18.0-517.el8.aarch64 #1 SMP Wed Oct 11 00:31:27 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### CPU architecture issue was seen on (see `uname -m`)

aarch64

### Expected behaviour you didn't see

rtpengine process started

### Unexpected behaviour you saw

```
[root@sbc-stage-a0 rtpengine]# /usr/bin/rtpengine -f
rtpengine: kernel.c:63: kernel_alloc: Assertion `b != NULL && b != MAP_FAILED' failed.
Aborted (core dumped)
```

### Steps to reproduce the problem

just compiled release sources with disabled transcoding

### Additional program output to the terminal or logs illustrating the issue

```shell
GDB output

(gdb) bt full
#0  0x0000fffff6f46274 in raise () at /lib64/libc.so.6
#1  0x0000fffff6f30a2c in abort () at /lib64/libc.so.6
#2  0x0000fffff6f3fba0 in __assert_fail_base () at /lib64/libc.so.6
#3  0x0000fffff6f3fc18 in __assert_perror_fail () at /lib64/libc.so.6
#4  0x0000aaaaaab72084 in kernel_alloc (len=<optimized out>) at kernel.c:61
        b = <optimized out>
        __PRETTY_FUNCTION__ = "kernel_alloc"
#5  0x0000aaaaaab72084 in kernel_alloc (len=<optimized out>, len=<optimized out>) at kernel.c:61
        b = <optimized out>
        __PRETTY_FUNCTION__ = "kernel_alloc"
#6  0x0000aaaaaaac45cc in bufferpool_new_shard (bp=bp@entry=0xaaaaaac483d0) at bufferpool.c:102
        buf = <optimized out>
        ret = <optimized out>
        __auto_lock_6 = <optimized out>
#7  0x0000aaaaaaac6f5c in bufferpool_alloc (bp=0xaaaaaac483d0, len=208) at bufferpool.c:133
        __auto_lock_7 = 0xaaaaaac483f0
        shard = <optimized out>
        ret = <optimized out>
#8  0x0000aaaaaab0d994 in bufferpool_alloc0 (len=208, bp=<optimized out>) at ../lib/bufferpool.h:23
        ret = <optimized out>
        lif = 0xaaaaaac4a850
        ifc = 0xaaaaaac4a8a0
        spec = 0xaaaaaac27130
#9  0x0000aaaaaab0d994 in __interface_append (ifa=0xaaaaaac27030, fam=<optimized out>, create=create@entry=true) at media_socket.c:809
        lif = 0xaaaaaac4a850
        ifc = 0xaaaaaac4a8a0
        spec = 0xaaaaaac27130
#10 0x0000aaaaaab0df34 in interfaces_init (interfaces=0xaaaaaabd01d0 <rtpe_config+456>) at media_socket.c:836
        i = 2
        l = 0xaaaaaac1e800 = {0xaaaaaac27030, 0xaaaaaac270b0}
        ifa = <optimized out>
#11 0x0000aaaaaaac29e0 in init_everything () at main.c:1291
#12 0x0000aaaaaaac29e0 in main (argc=<optimized out>, argv=<optimized out>) at main.c:1482
```
```


### Anything else?

_No response_

**Comment by sergey-safarov** [comment]
Crush related to the old kernel module usage.
After the server restarted, a new module loaded, and the issue was resolved.

**Comment by rfuchs** [comment]
Behaviour as expected then :laughing:
