### ISSUE TITLE
RTPEngine does not respond to a "delete" after a "play media" with the "block egress" flag

### ISSUE THREAD

**Issue by NormB** [sipwise/rtpengine#1883]
### rtpengine version the issue has been seen with

Version: 13.2.0.0+0~mr13.2.0.0 git-master-2a46eb2c

### Used distribution and its version

Debian bookworm

### Linux kernel version used

6.1.0-26-amd64

### CPU architecture issue was seen on (see `uname -m`)

x86_64

### Expected behaviour you didn't see

When a "delete" message is received, it should be responded to in a timely fashion.

### Unexpected behaviour you saw

The "delete" message is received however no response is generated.

### Steps to reproduce the problem

Issue a "play media" with the "block egress" flag specified.

### Additional program output to the terminal or logs illustrating the issue

When using the "block egress" flag in a "play media" message, the subsequent "delete" message is not responded to.

The logs show that this message is not being emitted:

[core] Deleting call branch ‘888114273’ (via-branch ‘br0’)

I've looked at monologue_delete_iter() as that is where the above log message is being written from. Will be happy to dig deeper to try to get to the bottom of the problem, but need a little direction.

I will be happy to test any possible fixes.

Regards,
Norm

The RTPEngine debug logs show:
```
[1733926135.056452] INFO: [B2B.113.6861687.1733926131.1858877025]: [control] Received command 'delete' from 100.127.6.111:58829
[1733926135.056490] DEBUG: [B2B.113.6861687.1733926131.1858877025]: [control] Dump for 'delete' from 100.127.6.111:58829: { "call-id": "B2B.113.6861687.1733926131.1858877025", "via-branch": "br0", "received-from": [ "IP4", "0.0.0.0" ], "from-tag": "d469a2e1464e6403b836512408a7eb12-7fe2", "to-tag": "868381717", "command": "delete" }
[1733926135.056539] DEBUG: [B2B.113.6861687.1733926131.1858877025]: [core] 0 packets removed from send queue
```

A capture of the control port from the sending system shows a "delete" is sent. When no response is received, another "delete" is sent. The second "delete" gets a response indicating that the call (monologue) appears to have been deleted.

```
#
U 100.127.6.111:35456 -> 100.127.6.106:22222 #19
43_3332_3 d7:call-id35:B2B.113.8197460.1733927984.6465717510:via-branch3:br013:received-froml3:IP47:0.0.0.0e8:from-tag37:a0f4c113d6483795b04428d8830af30d-7fe26:to-tag9:9103690087:command6:deletee
#
U 100.127.6.111:35456 -> 100.127.6.106:22222 #20
43_3332_3 d7:call-id35:B2B.113.8197460.1733927984.6465717510:via-branch3:br013:received-froml3:IP47:0.0.0.0e8:from-tag37:a0f4c113d6483795b04428d8830af30d-7fe26:to-tag9:9103690087:command6:deletee
#
U 100.127.6.106:22222 -> 100.127.6.111:35456 #21
43_3332_3 d7:warning38:Call-ID not found or tags didn't match6:result2:oke
#
```

The RTPEngine debug logs when not using "block egress" is:

```
[1733927034.904419] INFO: [B2B.113.38841.1733927030.1703970125]: [control] Received command ‘delete’ from 100.127.6.111:47435  
[1733927034.904444] DEBUG: [B2B.113.38841.1733927030.1703970125]: [control] Dump for ‘delete’ from 100.127.6.111:47435: { “call-id”: “B2B.113.38841.1733927030.1703970125”, “via-branch”: “br0”, “received-from”: [ “IP4”, “0.0.0.0” ], “from-tag”: “1dd6f6689bab4e15d707290814ad2ff0-7fe2”, “to-tag”: “888114273”, “command”: “delete” }  
[1733927034.904533] DEBUG: [B2B.113.38841.1733927030.1703970125]: [core] 0 packets removed from send queue  
[1733927034.904556] INFO: [B2B.113.38841.1733927030.1703970125]: [core] Deleting call branch ‘888114273’ (via-branch ‘br0’)
```

A control port capture from a similar flow that does not use "block egress" is:

```
#
U 100.127.6.111:52438 -> 100.127.6.107:22222 #31
46_9842_9 d7:call-id36:B2B.113.625345.1733927856.122192111010:via-branch3:br013:received-froml3:IP47:0.0.0.0e8:from-tag37:16943b22cb1038d4ef459f5f2ef0fcb6-7fe26:to-tag9:9070437647:command6:deletee
#
U 100.127.6.107:22222 -> 100.127.6.111:52438 #32
46_9842_9 d7:createdi1733927857e10:created_usi69221e11:last signali1733927858e17:last redis update ...
```

### Anything else?

Reference: https://groups.google.com/g/rtpengine/c/RHn6P7Iyr90

**Comment by NormB** [comment]
Now, when a "delete" message is received by RTPEngine after a "play media" with the "block egress" flag, a segfault happens 100% of the time.

(gdb)  bt
#0  0x0000560c06540a71 in atomic64_and (a=18446744065119617023, u=0x3b0) at ../lib/auxlib.h:544
#1  bf_clear (f=8589934592, u=0x3b0) at ../lib/auxlib.h:636
#2  media_player_shutdown.part.0.lto_priv.0 (mp=0x7f7dac0201b0) at ./media_player.c:134
#3  0x0000560c06495168 in media_player_shutdown (mp=<optimized out>) at ./media_player.c:119
#4  media_player_stop (mp=<optimized out>) at ./media_player.c:161
#5  __monologue_stop (ml=0x7f7dac028010) at ./call.c:4880
#6  monologue_stop.part.0.lto_priv.0 (ml=ml@entry=0x7f7dac028380, stop_media_subsribers=<optimized out>) at ./call.c:4907
#7  0x0000560c06495351 in monologue_stop (stop_media_subsribers=true, ml=0x7f7dac028380) at ./call.c:4895
#8  call_delete_branch (c=0x7f7dac01c620, branch=0x7f7dd2b92368, fromtag=0x7f7dd2b92338, totag=0x0, ctx=0x7f7dd2b92ab0, delete_delay=0) at ./call.c:4985
#9  0x0000560c064d3eec in call_delete_ng (ctx=0x7f7dd2b92ab0) at ./call_interfaces.c:2422
#10 0x0000560c064af359 in control_ng_process_payload (hctx=hctx@entry=0x0, reply=reply@entry=0x7f7dd2b92b90, data=data@entry=0x7f7dd2b92bd0, sin=sin@entry=0x7f7dac013ac0, addr=<optimized out>, ref=ref@entry=0x7f7dac003810, ngbufp=<optimized out>) at ./control_ng.c:758
#11 0x0000560c064afa3f in control_ng_process (buf=<optimized out>, sin=0x7f7dac013ac0, addr=<optimized out>, local=0x7f7dac013ae0, cb=cb@entry=0x560c064ab410 <control_ng_send_from>, p1=0x560c0f658028, ref=0x7f7dac003810) at ./control_ng.c:956
#12 0x0000560c064afd47 in control_ng_incoming (obj=<optimized out>, udp_buf=<optimized out>) at ./control_ng.c:1006
#13 0x0000560c064a446b in udp_listener_incoming (fd=<optimized out>, p=0x560c0f646a00) at ./udp_listener.c:58
#14 0x0000560c0656f1ea in uring_poll_event (req=0x7f7dac002ec0, res=<optimized out>, flags=2) at ./uring.c:289
#15 0x0000560c06569af3 in __uring_thread_loop () at ./uring.c:92
#16 0x0000560c0656a5b0 in uring_poller_poll (p=0x560c0f641370) at ./uring.c:565
#17 0x0000560c06478683 in uring_poller_loop (ptr=0x560c0f641370) at ./main.c:1530
#18 0x0000560c06476d9b in thread_detach_func (d=<optimized out>) at ./helpers.c:264
#19 0x00007f80058d01c4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#20 0x00007f800595085c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81


Lines 133-134 of demon/media_player.c:


if (mp->opts.block_egress)
        MEDIA_CLEAR(mp->media, BLOCK_EGRESS);


It appears that "block egress" is still causing problems.

**Comment by NormB** [comment]
Confirmed that this update fixes the segfault problem.

Thank you for the quick response.

Norm
