### ISSUE TITLE
Transcoding Opus to PCMA fails and giving Segmentation fault (core dumped)...

### ISSUE THREAD

**Issue by pavanps** [sipwise/rtpengine#473]
Hi,

I have configured the latest rtpengine which supports transcoding. While am sending sdp with Opus Codec to transcode to PCMA, then rtpengine is crashing and also conversion is failed. Please find the logs below and please let me know if any other configuration is required,

[1519632008.213070] INFO: [A_2oY0Bi8ueoD0DWH3Z3nw..]: Received command 'offer' from 192.168.2.152:47478
[1519632008.213082] DEBUG: [A_2oY0Bi8ueoD0DWH3Z3nw..]: Dump for 'offer' from 192.168.2.152:47478: { "sdp": "v=0
o=- 3728639342 3728639342 IN IP4 192.168.123.124
s=pjmedia
t=0 0
m=audio 4002 RTP/AVP 123 101
c=IN IP4 192.168.123.124
a=rtpmap:123 opus/48000/2
a=rtpmap:101 telephone-event/8000
a=fmtp:123 maxplaybackrate=16000
a=fmtp:101 0-16
a=sendrecv
", "flags": [ "transcode-PCMA" ], "call-id": "A_2oY0Bi8ueoD0DWH3Z3nw..", "received-from": [ "IP4", "10.10.30.112" ], "from-tag": "37fd5a71", "command": "offer" }
[1519632008.213109] NOTICE: [A_2oY0Bi8ueoD0DWH3Z3nw..]: Creating new call
[1519632008.213132] DEBUG: [A_2oY0Bi8ueoD0DWH3Z3nw..]: Codec 'PCMA/8000' added for transcoding with payload type 8
[1519632008.213140] DEBUG: [A_2oY0Bi8ueoD0DWH3Z3nw..]: Default sink codec is opus/48000/2
[1519632008.213143] DEBUG: [A_2oY0Bi8ueoD0DWH3Z3nw..]: Creating codec handler for opus/48000/2
[1519632008.213147] DEBUG: [A_2oY0Bi8ueoD0DWH3Z3nw..]: Sink supports codec opus/48000/2
[1519632008.213150] DEBUG: [A_2oY0Bi8ueoD0DWH3Z3nw..]: Creating codec handler for telephone-event/8000
[1519632008.213154] DEBUG: [A_2oY0Bi8ueoD0DWH3Z3nw..]: Creating codec handler for PCMA/8000
[1519632008.213157] DEBUG: [A_2oY0Bi8ueoD0DWH3Z3nw..]: Sink does not support codec PCMA/8000
[1519632008.213161] DEBUG: [A_2oY0Bi8ueoD0DWH3Z3nw..]: Creating SSRC transcoder from PCMA/8000/1 to opus/48000/2
[1519632008.213197] WARNING: [A_2oY0Bi8ueoD0DWH3Z3nw..]: Failed to set Opus frame_duration option (error code -1414549496)
[1519632008.213208] ERR: [A_2oY0Bi8ueoD0DWH3Z3nw..]: av_log: The encoder 'opus' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
[1519632008.213218] NOTICE: [A_2oY0Bi8ueoD0DWH3Z3nw..]: av_log: Average Intensity Stereo band: 0.0
[1519632008.213222] NOTICE: [A_2oY0Bi8ueoD0DWH3Z3nw..]: av_log: Dual Stereo used: -nan%
[1519632008.213230] ERR: [A_2oY0Bi8ueoD0DWH3Z3nw..]: Error configuring media output for codec opus: failed to open output context
Segmentation fault (core dumped)

**Comment by rfuchs** [comment]
You should probably update your ffmpeg (libavcodec). A gdb backtrace would also be appreciated.

**Comment by pavanps** [comment]
Hi,
Please find the backtrace of core dump below,

Core was generated by `rtpengine --interface 192.168.2.81 --listen-ng 192.168.2.81:60000 -f -m 60001 -'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000860662 in avcodec_is_open (s=0x0) at libavcodec/utils.c:1859
1859    {
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.23-15.el6_6.2.x86_64 glibc-2.12-1.209.el6_9.2.x86_64 json-glib-0.14.2-3.el6.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-23.el6.x86_64 libcurl-7.19.7-53.el6_9.x86_64 libevent2-2.0.21-2.el6.x86_64 libffi-3.0.5-3.2.el6.x86_64 libidn-1.18-2.el6.x86_64 libpcap-1.4.0-4.20130826git2dbcaa1.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 libssh2-1.4.2-2.el6_7.1.x86_64 libxml2-2.7.6-21.el6_8.1.x86_64 nspr-4.13.1-1.el6.x86_64 nss-3.28.4-4.el6_9.x86_64 nss-softokn-freebl-3.14.3-23.3.el6_8.x86_64 nss-util-3.28.4-1.el6_9.x86_64 openldap-2.4.40-16.el6.x86_64 openssl-1.0.1e-57.el6.x86_64 pcre-7.8-7.el6.x86_64 xmlrpc-c-1.16.24-1210.1840.el6.x86_64 xmlrpc-c-client-1.16.24-1210.1840.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x0000000000860662 in avcodec_is_open (s=0x0) at libavcodec/utils.c:1859
#1  0x0000000000558ba4 in avcodec_receive_packet (avctx=0x0, avpkt=0x7fd7ec016110) at libavcodec/encode.c:430
#2  0x00000000004c721b in avc_encoder_input (enc=0x7fd7ec0160e0, frame=<value optimized out>) at codeclib.c:1026
#3  0x00000000004c69a6 in encoder_input_data (enc=0x7fd7ec0160e0, frame=0x0, callback=0x4c26e0 <__encoder_flush>, u1=0x7fd7f6e38eac, u2=0x0) at codeclib.c:1077
#4  0x00000000004c33c1 in __ssrc_handler_free (ch=0x7fd7ec016020) at codec.c:623
#5  0x00000000004c35e8 in __ssrc_handler_new (p=0x7fd7e00235b0) at codec.c:606
#6  0x00000000004c02a1 in create_ssrc_hash_full (cfunc=0x4c3400 <__ssrc_handler_new>, ffunc=0x4c3370 <__ssrc_handler_free>, uptr=0x7fd7e00235b0) at ssrc.c:155
#7  0x00000000004c49f3 in __make_transcoder (receiver=0x7fd7e00227a0, sink=0x7fd7e0022980) at codec.c:130
#8  codec_handlers_update (receiver=0x7fd7e00227a0, sink=0x7fd7e0022980) at codec.c:345
#9  0x000000000048a1c6 in monologue_offer_answer (other_ml=0x7fd7ec006970, streams=<value optimized out>, flags=0x7fd7f6e390f0) at call.c:1595
#10 0x00000000004a9338 in call_offer_answer_ng (input=<value optimized out>, output=0x7fd7ec010af8, opmode=OP_OFFER, addr=<value optimized out>,
    sin=<value optimized out>) at call_interfaces.c:822
#11 0x00000000004978e9 in control_ng_incoming (obj=0x279c030, buf=<value optimized out>, sin=0x7fd7f6e494f0, addr=0x7fd7f6e494b0 "192.168.2.152:56566", ul=0x279c0c8)
    at control_ng.c:187
#12 0x000000000049697b in udp_listener_incoming (fd=<value optimized out>, p=0x27960a0, x=<value optimized out>) at udp_listener.c:54
#13 0x000000000048365e in poller_poll (p=0x279b190, timeout=100) at poller.c:350
#14 0x0000000000483688 in poller_loop (d=0x279b190) at poller.c:505
#15 0x0000000000483daf in thread_detach_func (d=0x27724b0) at aux.c:143
#16 0x00007fd7fe28baa1 in start_thread () from /lib64/libpthread.so.0
#17 0x00007fd7fdfd8bcd in clone () from /lib64/libc.so.6

**Comment by pavanps** [comment]
This is the version used,

 Libavcodec version macros.

#define LIBAVCODEC_VERSION_MAJOR  58
#define LIBAVCODEC_VERSION_MINOR  11
#define LIBAVCODEC_VERSION_MICRO 101

**Comment by pavanps** [comment]
Updated the code and there is no core dump. Closing this ticket. Thank you.
