### ISSUE TITLE
Segfault after 2 or 3 days of running

### ISSUE THREAD

**Issue by beastaw56** [sipwise/rtpengine#477]
Feb 27 16:55:07 optimus kernel: [532924.708108] rtpengine[16639]: segfault at 0 ip 00000000004277b7 sp 00007f956919afa8 error 4 in rtpengine[400000+64000]

I have attached the logs leading up to the crash. Any help is appreciated. Let me know if anything else would help. 

[Logs.txt](https://github.com/sipwise/rtpengine/files/1767305/Logs.txt)

**Comment by beastaw56** [comment]
[coredump.txt](https://github.com/sipwise/rtpengine/files/1767430/coredump.txt)

**Comment by rfuchs** [comment]
These crash files are not useful since I don't have the binary you're running. Please load up the core in gdb and post a backtrace.

**Comment by etamme** [comment]
Hey richard, we had a crash on a relatively unloaded relay yesterday.  Here is our bt.

https://gist.github.com/etamme/dc44ccd8a005303c488541f600e928ea

**Comment by rfuchs** [comment]
@etamme that one looks like it's the one fixed by 14262f56f

**Comment by etamme** [comment]
perfect thanks.

**Comment by beastaw56** [comment]
Hey Richard,
Please see below. Let me know if this is what your looking for:

GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Reading symbols from /usr/sbin/rtpengine...(no debugging symbols found)...done.
[New LWP 16639]
[New LWP 16635]
[New LWP 16637]
[New LWP 16636]
[New LWP 16640]
[New LWP 16634]
[New LWP 16638]
[New LWP 16641]
[New LWP 16642]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rtpengine --table=0 --interface=70.42.44.195 --listen-ng=127.0.0.1:22'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004277b7 in ?? ()
[Current thread is 1 (Thread 0x7f956919e700 (LWP 16639))]
(gdb) backtrace
#0  0x00000000004277b7 in ?? ()
#1  0x00000000004261d6 in ?? ()
#2  0x0000000000427a34 in ?? ()
#3  0x000000000043e0fb in ?? ()
#4  0x000000000040d95e in ?? ()
#5  0x000000000040dcfd in ?? ()
#6  0x000000000040dd70 in ?? ()
#7  0x00007f95813066ba in start_thread (arg=0x7f956919e700) at pthread_create.c:333
#8  0x00007f958103c41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by rfuchs** [comment]
Yes, it would be, but this has had all the debug symbols stripped. If you have a debug package, install it and pull another backtrace.
