### ISSUE TITLE
Crash in libpthread

### ISSUE THREAD

**Issue by digipigeon** [sipwise/rtpengine#571]
Hello, I am experiencing a crash on the master 6.4 branch, previously stable on 6.2

Using the latest master after 5 hours in production.

Last Lines of the log file:

```
Jul  3 18:45:23 rtp-lon-1 kernel: [14578.904653] show_signal_msg: 7 callbacks suppressed
Jul  3 18:45:23 rtp-lon-1 kernel: [14578.904658] rtpengine[8769]: segfault at 38 ip 00007f5378e3f2c2 sp 00007f535c4d58e0 error 4 in libpthread-2.27.so[7f5378e33000+1a000]
```
gdb, bt full and bt

```
gdb /usr/sbin/rtpengine CoreDump
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/rtpengine...(no debugging symbols found)...done.
[New LWP 8769]
[New LWP 8752]
[New LWP 8762]
[New LWP 8763]
[New LWP 8764]
[New LWP 8765]
[New LWP 8768]
[New LWP 8761]
[New LWP 8767]
[New LWP 8766]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rtpengine -f -E --pidfile /var/run/ngcp-rtpengine-daemon.pid --config'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __pthread_rwlock_rdlock_full (abstime=0x0, rwlock=0x20) at pthread_rwlock_common.c:287
287     pthread_rwlock_common.c: No such file or directory.
[Current thread is 1 (Thread 0x7f535c4d9700 (LWP 8769))]
(gdb) bt full
#0  __pthread_rwlock_rdlock_full (abstime=0x0, rwlock=0x20) at pthread_rwlock_common.c:287
        r = <optimized out>
        wpf = <optimized out>
        ready = <optimized out>
        r = <optimized out>
        wpf = <optimized out>
        ready = <optimized out>
        __value = <optimized out>
        private = <optimized out>
        err = <optimized out>
        private = <optimized out>
        private = <optimized out>
        err = <optimized out>
#1  __GI___pthread_rwlock_rdlock (rwlock=0x20) at pthread_rwlock_rdlock.c:27
        result = <optimized out>
#2  0x0000560f08eaa00f in ?? ()
No symbol table info available.
#3  0x0000560f08ead346 in ?? ()
No symbol table info available.
#4  0x0000560f08ea529d in ?? ()
No symbol table info available.
#5  0x0000560f08e71bb3 in ?? ()
No symbol table info available.
#6  0x0000560f08e71f9d in ?? ()
No symbol table info available.
#7  0x0000560f08e720b3 in ?? ()
No symbol table info available.
#8  0x00007f5378e3a6db in start_thread (arg=0x7f535c4d9700) at pthread_create.c:463
        pd = 0x7f535c4d9700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139996007601920, 2222443995460368730, 139996007597504, 0, 94622579118112, 140726224488928, -2274021411957933734, -2273960682072737446}, mask_was_saved = 0}}, priv = {pad = {0x0,
              0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#9  0x00007f5378b6388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
(gdb) bt
#0  __pthread_rwlock_rdlock_full (abstime=0x0, rwlock=0x20) at pthread_rwlock_common.c:287
#1  __GI___pthread_rwlock_rdlock (rwlock=0x20) at pthread_rwlock_rdlock.c:27
#2  0x0000560f08eaa00f in ?? ()
#3  0x0000560f08ead346 in ?? ()
#4  0x0000560f08ea529d in ?? ()
#5  0x0000560f08e71bb3 in ?? ()
#6  0x0000560f08e71f9d in ?? ()
#7  0x0000560f08e720b3 in ?? ()
#8  0x00007f5378e3a6db in start_thread (arg=0x7f535c4d9700) at pthread_create.c:463
#9  0x00007f5378b6388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Kind Regards Jonathan

**Comment by rfuchs** [comment]
Please install the dbg or dbgsym package and do the backtrace again.

**Comment by digipigeon** [comment]
```
(gdb) bt
#0  __pthread_rwlock_rdlock_full (abstime=0x0, rwlock=0x20) at pthread_rwlock_common.c:287
#1  __GI___pthread_rwlock_rdlock (rwlock=rwlock@entry=0x20) at pthread_rwlock_rdlock.c:27
#2  0x0000560f08eaa00f in find_ssrc (ht=0x0, ssrc=<optimized out>) at ssrc.c:77
#3  get_ssrc (ssrc=<optimized out>, ht=0x0) at ssrc.c:110
#4  0x0000560f08ead346 in __handler_func_sequencer (mp=0x7f535c4d5aa8, packet=0x7f5354383540, h=<optimized out>) at codec.c:526
#5  0x0000560f08ea529d in stream_packet (phc=0x7f535c4d5a50) at media_socket.c:1664
#6  stream_fd_readable (fd=<optimized out>, p=0x7f53500815b0, u=<optimized out>) at media_socket.c:1791
#7  0x0000560f08e71bb3 in poller_poll (p=p@entry=0x560f09370e10, timeout=timeout@entry=100) at poller.c:350
#8  0x0000560f08e71f9d in poller_loop (d=0x560f09370e10) at poller.c:505
#9  0x0000560f08e720b3 in thread_detach_func (d=0x560f09375020) at aux.c:209
#10 0x00007f5378e3a6db in start_thread (arg=0x7f535c4d9700) at pthread_create.c:463
#11 0x00007f5378b6388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) bt full
#0  __pthread_rwlock_rdlock_full (abstime=0x0, rwlock=0x20) at pthread_rwlock_common.c:287
        r = <optimized out>
        wpf = <optimized out>
        ready = <optimized out>
        r = <optimized out>
        wpf = <optimized out>
        ready = <optimized out>
        __value = <optimized out>
        private = <optimized out>
        err = <optimized out>
        private = <optimized out>
        private = <optimized out>
        err = <optimized out>
#1  __GI___pthread_rwlock_rdlock (rwlock=rwlock@entry=0x20) at pthread_rwlock_rdlock.c:27
        result = <optimized out>
#2  0x0000560f08eaa00f in find_ssrc (ht=0x0, ssrc=<optimized out>) at ssrc.c:77
        ret = <optimized out>
        ret = <optimized out>
#3  get_ssrc (ssrc=<optimized out>, ht=0x0) at ssrc.c:110
        ent = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
#4  0x0000560f08ead346 in __handler_func_sequencer (mp=0x7f535c4d5aa8, packet=0x7f5354383540, h=<optimized out>) at codec.c:526
        ch = <optimized out>
        seq_next_packet = <optimized out>
#5  0x0000560f08ea529d in stream_packet (phc=0x7f535c4d5a50) at media_socket.c:1664
        transcoder = <optimized out>
        ret = 0
        stun_ret = <optimized out>
        address_check = <optimized out>
        handler_ret = <optimized out>
        p = <optimized out>
        ret = <optimized out>
        handler_ret = <optimized out>
        stun_ret = <optimized out>
        address_check = <optimized out>
        p = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        __loglevel = <optimized out>
        transcoder = <optimized out>
        _g_boolean_var_ = <optimized out>
        __loglevel = <optimized out>
#6  stream_fd_readable (fd=<optimized out>, p=0x7f53500815b0, u=<optimized out>) at media_socket.c:1791
        phc = {s = {s = 0x7f535c4d5bd0 "\200e\005\fb", <incomplete sequence \327>, len = 16}, sink = 0x7f5344282cb0, decrypt_func = 0x0, encrypt_func = 0x0, rtcp_filter = 0x0, in_srtp = 0x7f53545f78c0, out_srtp = 0x7f5344282cb0,
          payload_type = 101, rtcp = 0, update = 0, unkernelize = 0, kernelize = 0, mp = {raw = {s = 0x7f535c4d5bd0 "\200e\005\fb", <incomplete sequence \327>, len = 16}, fsin = {address = {
                family = 0x560f090cfd40 <__socket_families>, u = {ipv4 = {s_addr = 3553059663}, ipv6 = {__in6_u = {__u6_addr8 = "Oc\307\323", '\000' <repeats 11 times>, __u6_addr16 = {25423, 54215, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {
                        3553059663, 0, 0, 0}}}}}, port = 24458}, tv = {tv_sec = 1530643523, tv_usec = 411486}, sfd = 0x7f53500815b0, call = 0x7f535012d8b0, stream = 0x7f53545f78c0, media = 0x7f534c561d60, rtp = 0x7f535c4d5bd0,
            rtcp = 0x0, ssrc_in = 0x7f53540ed050, ssrc_out = 0x7f53540ed270, payload = {
              s = 0x7f535c4d5bdc "\v\207\006\220?==?HZ\342ɾ\272\270\271\275\307\337TA9546<Iyɻ\264\260\261\264\274\315]@60./4=Uϼ\262\256\255\257\265\300\354F7/,,/7Hླ\255\253\254\257\272\317P;/,+-2>`Ƿ\256\254\254\256\266\305l?4.,-0:M\327\275\262\256\255\256\264\276\334K:2..19F\371ƹ\262\257\260\265\275\316_C9435:D^\325»\270\267\272\277\315\367PD=<=?HY\356\320\307\302\302\304\311\323\347gVBF", len = 4}, packets_out = {head = 0x0, tail = 0x0, length = 0}}}
        sfd = 0x7f53500815b0
        buf = '\000' <repeats 128 times>, "\200e\005\fbu\327\000^h;\n\v\207\006\220?==?HZ\342ɾ\272\270\271\275\307\337TA9546<Iyɻ\264\260\261\264\274\315]@60./4=Uϼ\262\256\255\257\265\300\354F7/,,/7Hླ"...
        ret = <optimized out>
        iters = <optimized out>
        update = <optimized out>
        ca = <optimized out>
#7  0x0000560f08e71bb3 in poller_poll (p=p@entry=0x560f09370e10, timeout=timeout@entry=100) at poller.c:350
---Type <return> to continue, or q <return> to quit---
        ret = 1
        i = <optimized out>
        it = 0x7f534c3c0180
        evs = {{events = 1, data = {ptr = 0x36e, fd = 878, u32 = 878, u64 = 878}}, {events = 1, data = {ptr = 0x38f, fd = 911, u32 = 911, u64 = 911}}, {events = 1, data = {ptr = 0x5e0, fd = 1504, u32 = 1504, u64 = 1504}}, {
            events = 1, data = {ptr = 0x416, fd = 1046, u32 = 1046, u64 = 1046}}, {events = 1, data = {ptr = 0xf9, fd = 249, u32 = 249, u64 = 249}}, {events = 1, data = {ptr = 0xf7, fd = 247, u32 = 247, u64 = 247}}, {events = 1,
            data = {ptr = 0x430, fd = 1072, u32 = 1072, u64 = 1072}}, {events = 1, data = {ptr = 0x1fa, fd = 506, u32 = 506, u64 = 506}}, {events = 1, data = {ptr = 0x92, fd = 146, u32 = 146, u64 = 146}}, {events = 1, data = {
              ptr = 0x416, fd = 1046, u32 = 1046, u64 = 1046}}, {events = 1, data = {ptr = 0xc5, fd = 197, u32 = 197, u64 = 197}}, {events = 1, data = {ptr = 0x304, fd = 772, u32 = 772, u64 = 772}}, {events = 1, data = {ptr = 0xda,
              fd = 218, u32 = 218, u64 = 218}}, {events = 1, data = {ptr = 0x530, fd = 1328, u32 = 1328, u64 = 1328}}, {events = 1, data = {ptr = 0x614, fd = 1556, u32 = 1556, u64 = 1556}}, {events = 1, data = {ptr = 0x5ea,
              fd = 1514, u32 = 1514, u64 = 1514}}, {events = 1, data = {ptr = 0x5ae, fd = 1454, u32 = 1454, u64 = 1454}}, {events = 1, data = {ptr = 0x5a7, fd = 1447, u32 = 1447, u64 = 1447}}, {events = 1, data = {ptr = 0x3b4,
              fd = 948, u32 = 948, u64 = 948}}, {events = 1, data = {ptr = 0x53a, fd = 1338, u32 = 1338, u64 = 1338}}, {events = 1, data = {ptr = 0x32f, fd = 815, u32 = 815, u64 = 815}}, {events = 1, data = {ptr = 0x466, fd = 1126,
              u32 = 1126, u64 = 1126}}, {events = 1, data = {ptr = 0x3c8, fd = 968, u32 = 968, u64 = 968}}, {events = 1, data = {ptr = 0x372, fd = 882, u32 = 882, u64 = 882}}, {events = 1, data = {ptr = 0x44c, fd = 1100, u32 = 1100,
              u64 = 1100}}, {events = 1, data = {ptr = 0xe1, fd = 225, u32 = 225, u64 = 225}}, {events = 1, data = {ptr = 0x34a, fd = 842, u32 = 842, u64 = 842}}, {events = 1, data = {ptr = 0x82, fd = 130, u32 = 130, u64 = 130}}, {
            events = 1, data = {ptr = 0x3b7, fd = 951, u32 = 951, u64 = 951}}, {events = 1, data = {ptr = 0x448, fd = 1096, u32 = 1096, u64 = 1096}}, {events = 1, data = {ptr = 0x170, fd = 368, u32 = 368, u64 = 368}}, {events = 1,
            data = {ptr = 0x44b, fd = 1099, u32 = 1099, u64 = 1099}}, {events = 1, data = {ptr = 0x1a6, fd = 422, u32 = 422, u64 = 422}}, {events = 1, data = {ptr = 0x353, fd = 851, u32 = 851, u64 = 851}}, {events = 1, data = {
              ptr = 0x226, fd = 550, u32 = 550, u64 = 550}}, {events = 1, data = {ptr = 0x18f, fd = 399, u32 = 399, u64 = 399}}, {events = 1, data = {ptr = 0x33e, fd = 830, u32 = 830, u64 = 830}}, {events = 1, data = {ptr = 0x100,
              fd = 256, u32 = 256, u64 = 256}}, {events = 1, data = {ptr = 0x1e5, fd = 485, u32 = 485, u64 = 485}}, {events = 1, data = {ptr = 0x213, fd = 531, u32 = 531, u64 = 531}}, {events = 1, data = {ptr = 0x42a, fd = 1066,
              u32 = 1066, u64 = 1066}}, {events = 1, data = {ptr = 0x1b8, fd = 440, u32 = 440, u64 = 440}}, {events = 1, data = {ptr = 0x284, fd = 644, u32 = 644, u64 = 644}}, {events = 1, data = {ptr = 0x357, fd = 855, u32 = 855,
              u64 = 855}}, {events = 1, data = {ptr = 0x328, fd = 808, u32 = 808, u64 = 808}}, {events = 1, data = {ptr = 0x3e5, fd = 997, u32 = 997, u64 = 997}}, {events = 1, data = {ptr = 0x373, fd = 883, u32 = 883, u64 = 883}}, {
            events = 1, data = {ptr = 0x16b, fd = 363, u32 = 363, u64 = 363}}, {events = 1, data = {ptr = 0x4ac, fd = 1196, u32 = 1196, u64 = 1196}}, {events = 1, data = {ptr = 0x457, fd = 1111, u32 = 1111, u64 = 1111}}, {
            events = 1, data = {ptr = 0x592, fd = 1426, u32 = 1426, u64 = 1426}}, {events = 1, data = {ptr = 0x578, fd = 1400, u32 = 1400, u64 = 1400}}, {events = 1, data = {ptr = 0x2b4, fd = 692, u32 = 692, u64 = 692}}, {
            events = 1, data = {ptr = 0x32b, fd = 811, u32 = 811, u64 = 811}}, {events = 1, data = {ptr = 0x41d, fd = 1053, u32 = 1053, u64 = 1053}}, {events = 1, data = {ptr = 0x243, fd = 579, u32 = 579, u64 = 579}}, {events = 1,
            data = {ptr = 0x4b5, fd = 1205, u32 = 1205, u64 = 1205}}, {events = 1, data = {ptr = 0x481, fd = 1153, u32 = 1153, u64 = 1153}}, {events = 1, data = {ptr = 0x18c, fd = 396, u32 = 396, u64 = 396}}, {events = 1, data = {
              ptr = 0x666, fd = 1638, u32 = 1638, u64 = 1638}}, {events = 1, data = {ptr = 0x49f, fd = 1183, u32 = 1183, u64 = 1183}}, {events = 1, data = {ptr = 0x3c5, fd = 965, u32 = 965, u64 = 965}}, {events = 1, data = {
              ptr = 0x52d, fd = 1325, u32 = 1325, u64 = 1325}}, {events = 1, data = {ptr = 0x2f9, fd = 761, u32 = 761, u64 = 761}}, {events = 1, data = {ptr = 0x26e, fd = 622, u32 = 622, u64 = 622}}, {events = 1, data = {
              ptr = 0x22d, fd = 557, u32 = 557, u64 = 557}}, {events = 1, data = {ptr = 0x675, fd = 1653, u32 = 1653, u64 = 1653}}, {events = 1, data = {ptr = 0x681, fd = 1665, u32 = 1665, u64 = 1665}}, {events = 1, data = {
              ptr = 0x531, fd = 1329, u32 = 1329, u64 = 1329}}, {events = 1, data = {ptr = 0x1ff, fd = 511, u32 = 511, u64 = 511}}, {events = 1, data = {ptr = 0x1a, fd = 26, u32 = 26, u64 = 26}}, {events = 1, data = {ptr = 0x44f,
              fd = 1103, u32 = 1103, u64 = 1103}}, {events = 1, data = {ptr = 0x2f0, fd = 752, u32 = 752, u64 = 752}}, {events = 1, data = {ptr = 0x404, fd = 1028, u32 = 1028, u64 = 1028}}, {events = 1, data = {ptr = 0x40b,
              fd = 1035, u32 = 1035, u64 = 1035}}, {events = 1, data = {ptr = 0x144, fd = 324, u32 = 324, u64 = 324}}, {events = 1, data = {ptr = 0x294, fd = 660, u32 = 660, u64 = 660}}, {events = 1, data = {ptr = 0x191, fd = 401,
              u32 = 401, u64 = 401}}, {events = 1, data = {ptr = 0x163, fd = 355, u32 = 355, u64 = 355}}, {events = 1, data = {ptr = 0x139, fd = 313, u32 = 313, u64 = 313}}, {events = 1, data = {ptr = 0x2b3, fd = 691, u32 = 691,
              u64 = 691}}, {events = 1, data = {ptr = 0xa8, fd = 168, u32 = 168, u64 = 168}}, {events = 1, data = {ptr = 0x685, fd = 1669, u32 = 1669, u64 = 1669}}, {events = 1, data = {ptr = 0x1a2, fd = 418, u32 = 418, u64 = 418}},
          {events = 1, data = {ptr = 0x346, fd = 838, u32 = 838, u64 = 838}}, {events = 1, data = {ptr = 0x483, fd = 1155, u32 = 1155, u64 = 1155}}, {events = 1, data = {ptr = 0x51c, fd = 1308, u32 = 1308, u64 = 1308}}, {events = 1,
            data = {ptr = 0x53, fd = 83, u32 = 83, u64 = 83}}, {events = 1, data = {ptr = 0x694, fd = 1684, u32 = 1684, u64 = 1684}}, {events = 1, data = {ptr = 0x2bb, fd = 699, u32 = 699, u64 = 699}}, {events = 1, data = {
              ptr = 0x413, fd = 1043, u32 = 1043, u64 = 1043}}, {events = 1, data = {ptr = 0x4d, fd = 77, u32 = 77, u64 = 77}}, {events = 1, data = {ptr = 0x3dd, fd = 989, u32 = 989, u64 = 989}}, {events = 1, data = {ptr = 0x49,
              fd = 73, u32 = 73, u64 = 73}}, {events = 1, data = {ptr = 0x50, fd = 80, u32 = 80, u64 = 80}}, {events = 1, data = {ptr = 0x852, fd = 2130, u32 = 2130, u64 = 2130}}, {events = 1, data = {ptr = 0x6d5, fd = 1749,
              u32 = 1749, u64 = 1749}}, {events = 1, data = {ptr = 0x7b4, fd = 1972, u32 = 1972, u64 = 1972}}, {events = 1, data = {ptr = 0x18d, fd = 397, u32 = 397, u64 = 397}}, {events = 1, data = {ptr = 0xa6a, fd = 2666,
              u32 = 2666, u64 = 2666}}, {events = 1, data = {ptr = 0x510, fd = 1296, u32 = 1296, u64 = 1296}}, {events = 1, data = {ptr = 0x16f, fd = 367, u32 = 367, u64 = 367}}, {events = 1, data = {ptr = 0xb50, fd = 2896,
              u32 = 2896, u64 = 2896}}, {events = 1, data = {ptr = 0x7, fd = 7, u32 = 7, u64 = 7}}, {events = 1, data = {ptr = 0xb85, fd = 2949, u32 = 2949, u64 = 2949}}, {events = 1, data = {ptr = 0xa2c, fd = 2604, u32 = 2604,
              u64 = 2604}}, {events = 1, data = {ptr = 0x4df, fd = 1247, u32 = 1247, u64 = 1247}}, {events = 1, data = {ptr = 0xb6d, fd = 2925, u32 = 2925, u64 = 2925}}, {events = 1, data = {ptr = 0xb75, fd = 2933, u32 = 2933,
              u64 = 2933}}, {events = 1, data = {ptr = 0x3ed, fd = 1005, u32 = 1005, u64 = 1005}}, {events = 1, data = {ptr = 0x530, fd = 1328, u32 = 1328, u64 = 1328}}, {events = 1, data = {ptr = 0x433, fd = 1075, u32 = 1075,
              u64 = 1075}}, {events = 1, data = {ptr = 0x86, fd = 134, u32 = 134, u64 = 134}}, {events = 1, data = {ptr = 0xa9, fd = 169, u32 = 169, u64 = 169}}, {events = 1, data = {ptr = 0x3a0, fd = 928, u32 = 928, u64 = 928}}, {
            events = 1, data = {ptr = 0x64b, fd = 1611, u32 = 1611, u64 = 1611}}, {events = 1, data = {ptr = 0x216, fd = 534, u32 = 534, u64 = 534}}, {events = 1, data = {ptr = 0x75b, fd = 1883, u32 = 1883, u64 = 1883}}, {
            events = 1, data = {ptr = 0x2af, fd = 687, u32 = 687, u64 = 687}}, {events = 1, data = {ptr = 0x6cf, fd = 1743, u32 = 1743, u64 = 1743}}, {events = 1, data = {ptr = 0xaeb, fd = 2795, u32 = 2795, u64 = 2795}}, {
            events = 1, data = {ptr = 0x6bc, fd = 1724, u32 = 1724, u64 = 1724}}, {events = 1, data = {ptr = 0x8d1, fd = 2257, u32 = 2257, u64 = 2257}}, {events = 1, data = {ptr = 0x3b4, fd = 948, u32 = 948, u64 = 948}}, {
            events = 1, data = {ptr = 0xa58, fd = 2648, u32 = 2648, u64 = 2648}}, {events = 1, data = {ptr = 0x9e6, fd = 2534, u32 = 2534, u64 = 2534}}, {events = 1, data = {ptr = 0x3bd, fd = 957, u32 = 957, u64 = 957}}, {
            events = 1, data = {ptr = 0x3dc, fd = 988, u32 = 988, u64 = 988}}}
        ev = <optimized out>
        e = {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}
#8  0x0000560f08e71f9d in poller_loop (d=0x560f09370e10) at poller.c:505
        p = 0x560f09370e10
#9  0x0000560f08e720b3 in thread_detach_func (d=0x560f09375020) at aux.c:209
        dt = 0x560f09375020
        t = 0x7f5350001a90
        scheduler = <optimized out>
#10 0x00007f5378e3a6db in start_thread (arg=0x7f535c4d9700) at pthread_create.c:463
        pd = 0x7f535c4d9700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139996007601920, 2222443995460368730, 139996007597504, 0, 94622579118112, 140726224488928, -2274021411957933734, -2273960682072737446}, mask_was_saved = 0}}, priv = {pad = {0x0,
              0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
---Type <return> to continue, or q <return> to quit---
        not_first_call = <optimized out>
#11 0x00007f5378b6388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```

**Comment by rfuchs** [comment]
Is your build with or without transcoding support?

**Comment by digipigeon** [comment]
With transcoding support, but transcoding should not be in use at present.
