### ISSUE TITLE
RTPEngine Crash

### ISSUE THREAD

**Issue by syedrizwansrs** [sipwise/rtpengine#573]
Hi we are running RTP Engine Version: 6.4.0.0+0~mr6.4.0.0 git-master-a9ec666 and this has been stable for many days however we have experienced the following error.

```
(gdb) bt full
#0  __pthread_rwlock_rdlock_full (abstime=0x0, rwlock=0x20) at pthread_rwlock_common.c:287
        r = <optimized out>
        wpf = <optimized out>
        ready = <optimized out>
        r = <optimized out>
        wpf = <optimized out>
        ready = <optimized out>
        __value = <optimized out>
        private = <optimized out>
        err = <optimized out>
        private = <optimized out>
        private = <optimized out>
        err = <optimized out>
#1  __GI___pthread_rwlock_rdlock (rwlock=rwlock@entry=0x20) at pthread_rwlock_rdlock.c:27
        result = <optimized out>
#2  0x000055f07caeb00f in find_ssrc (ht=0x0, ssrc=<optimized out>) at ssrc.c:77
        ret = <optimized out>
        ret = <optimized out>
#3  get_ssrc (ssrc=<optimized out>, ht=0x0) at ssrc.c:110
        ent = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
#4  0x000055f07caee346 in __handler_func_sequencer (mp=0x7fddc92c5aa8, packet=0x7fddb847b200, h=<optimized out>) at codec.c:526
        ch = <optimized out>
        seq_next_packet = <optimized out>
#5  0x000055f07cae629d in stream_packet (phc=0x7fddc92c5a50) at media_socket.c:1664
        transcoder = <optimized out>
        ret = 0
        stun_ret = <optimized out>
        address_check = <optimized out>
        handler_ret = <optimized out>
        p = <optimized out>
        ret = <optimized out>
        handler_ret = <optimized out>
        stun_ret = <optimized out>
        address_check = <optimized out>
        p = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        __loglevel = <optimized out>
        transcoder = <optimized out>
        _g_boolean_var_ = <optimized out>
        __loglevel = <optimized out>
#6  stream_fd_readable (fd=<optimized out>, p=0x7fddb8402e50, u=<optimized out>) at media_socket.c:1791
        phc = {s = {s = 0x7fddc92c5bd0 "\200\345\267\061", len = 16}, sink = 0x7fddbc5a7030, decrypt_func = 0x0, encrypt_func = 0x0, rtcp_filter = 0x0, in_srtp = 0x7fddb86d1b90,
          out_srtp = 0x7fddbc5a7030, payload_type = 101, rtcp = 0, update = 0, unkernelize = 0, kernelize = 0, mp = {raw = {s = 0x7fddc92c5bd0 "\200\345\267\061", len = 16}, fsin = {address = {
                family = 0x55f07cd10d40 <__socket_families>, u = {ipv4 = {s_addr = 2324805327}, ipv6 = {__in6_u = {__u6_addr8 = "϶\221\212", '\000' <repeats 11 times>, __u6_addr16 = {46799, 35473,
                        0, 0, 0, 0, 0, 0}, __u6_addr32 = {2324805327, 0, 0, 0}}}}}, port = 30070}, tv = {tv_sec = 1531299573, tv_usec = 853345}, sfd = 0x7fddb8402e50, call = 0x7fddb83f4c60,
            stream = 0x7fddb86d1b90, media = 0x7fddb033c620, rtp = 0x7fddc92c5bd0, rtcp = 0x0, ssrc_in = 0x7fddb03a9850, ssrc_out = 0x7fddb03a9a70, payload = {s = 0x7fddc92c5bdc "\t\n", len = 4},
            packets_out = {head = 0x0, tail = 0x0, length = 0}}}
        sfd = 0x7fddb8402e50
        buf = '\000' <repeats 128 times>, "\200\345\267\061\000\006\"\240\tX\312\067\t\n\000\000", '\376' <repeats 156 times>...
        ret = <optimized out>
        iters = <optimized out>
        update = <optimized out>
        ca = <optimized out>
#7  0x000055f07cab2bb3 in poller_poll (p=p@entry=0x55f07ecfc690, timeout=timeout@entry=100) at poller.c:350
        ret = 4
---Type <return> to continue, or q <return> to quit---
        i = <optimized out>
        it = 0x7fddbc5d35e0
        evs = {{events = 1, data = {ptr = 0x40f, fd = 1039, u32 = 1039, u64 = 1039}}, {events = 1, data = {ptr = 0x480, fd = 1152, u32 = 1152, u64 = 1152}}, {events = 1, data = {ptr = 0x5f0,
              fd = 1520, u32 = 1520, u64 = 1520}}, {events = 1, data = {ptr = 0x215, fd = 533, u32 = 533, u64 = 533}}, {events = 1, data = {ptr = 0x56a, fd = 1386, u32 = 1386, u64 = 1386}}, {
            events = 1, data = {ptr = 0x61, fd = 97, u32 = 97, u64 = 97}}, {events = 1, data = {ptr = 0x5d2, fd = 1490, u32 = 1490, u64 = 1490}}, {events = 1, data = {ptr = 0x61, fd = 97, u32 = 97,
              u64 = 97}}, {events = 1, data = {ptr = 0x6a8, fd = 1704, u32 = 1704, u64 = 1704}}, {events = 1, data = {ptr = 0x33f, fd = 831, u32 = 831, u64 = 831}}, {events = 1, data = {ptr = 0x369,
              fd = 873, u32 = 873, u64 = 873}}, {events = 1, data = {ptr = 0x7f6, fd = 2038, u32 = 2038, u64 = 2038}}, {events = 1, data = {ptr = 0x3f2, fd = 1010, u32 = 1010, u64 = 1010}}, {
            events = 1, data = {ptr = 0x3bd, fd = 957, u32 = 957, u64 = 957}}, {events = 1, data = {ptr = 0x407, fd = 1031, u32 = 1031, u64 = 1031}}, {events = 1, data = {ptr = 0xe3, fd = 227,
              u32 = 227, u64 = 227}}, {events = 1, data = {ptr = 0x4fe, fd = 1278, u32 = 1278, u64 = 1278}}, {events = 1, data = {ptr = 0x467, fd = 1127, u32 = 1127, u64 = 1127}}, {events = 1,
            data = {ptr = 0x5fc, fd = 1532, u32 = 1532, u64 = 1532}}, {events = 1, data = {ptr = 0x6c0, fd = 1728, u32 = 1728, u64 = 1728}}, {events = 1, data = {ptr = 0x126, fd = 294, u32 = 294,
              u64 = 294}}, {events = 1, data = {ptr = 0xed, fd = 237, u32 = 237, u64 = 237}}, {events = 1, data = {ptr = 0x2ea, fd = 746, u32 = 746, u64 = 746}}, {events = 1, data = {ptr = 0x338,
              fd = 824, u32 = 824, u64 = 824}}, {events = 1, data = {ptr = 0x434, fd = 1076, u32 = 1076, u64 = 1076}}, {events = 1, data = {ptr = 0x634, fd = 1588, u32 = 1588, u64 = 1588}}, {
            events = 1, data = {ptr = 0x516, fd = 1302, u32 = 1302, u64 = 1302}}, {events = 1, data = {ptr = 0x33d, fd = 829, u32 = 829, u64 = 829}}, {events = 1, data = {ptr = 0xe1, fd = 225,
              u32 = 225, u64 = 225}}, {events = 1, data = {ptr = 0x2e1, fd = 737, u32 = 737, u64 = 737}}, {events = 1, data = {ptr = 0x132, fd = 306, u32 = 306, u64 = 306}}, {events = 1, data = {
              ptr = 0x3b1, fd = 945, u32 = 945, u64 = 945}}, {events = 1, data = {ptr = 0x5d2, fd = 1490, u32 = 1490, u64 = 1490}}, {events = 1, data = {ptr = 0x72, fd = 114, u32 = 114, u64 = 114}}, {
            events = 1, data = {ptr = 0x171, fd = 369, u32 = 369, u64 = 369}}, {events = 1, data = {ptr = 0x61, fd = 97, u32 = 97, u64 = 97}}, {events = 1, data = {ptr = 0x4e2, fd = 1250, u32 = 1250,
              u64 = 1250}}, {events = 1, data = {ptr = 0x39, fd = 57, u32 = 57, u64 = 57}}, {events = 1, data = {ptr = 0x6ca, fd = 1738, u32 = 1738, u64 = 1738}}, {events = 1, data = {ptr = 0x732,
              fd = 1842, u32 = 1842, u64 = 1842}}, {events = 1, data = {ptr = 0x2d, fd = 45, u32 = 45, u64 = 45}}, {events = 1, data = {ptr = 0x50e, fd = 1294, u32 = 1294, u64 = 1294}}, {events = 1,
            data = {ptr = 0x319, fd = 793, u32 = 793, u64 = 793}}, {events = 1, data = {ptr = 0x125, fd = 293, u32 = 293, u64 = 293}}, {events = 1, data = {ptr = 0x99, fd = 153, u32 = 153,
              u64 = 153}}, {events = 1, data = {ptr = 0x2a, fd = 42, u32 = 42, u64 = 42}}, {events = 1, data = {ptr = 0x178, fd = 376, u32 = 376, u64 = 376}}, {events = 1, data = {ptr = 0x65a,
              fd = 1626, u32 = 1626, u64 = 1626}}, {events = 1, data = {ptr = 0x99, fd = 153, u32 = 153, u64 = 153}}, {events = 1, data = {ptr = 0x178, fd = 376, u32 = 376, u64 = 376}}, {events = 1,
            data = {ptr = 0x2fd, fd = 765, u32 = 765, u64 = 765}}, {events = 1, data = {ptr = 0x2a, fd = 42, u32 = 42, u64 = 42}}, {events = 1, data = {ptr = 0x4cd, fd = 1229, u32 = 1229,
              u64 = 1229}}, {events = 1, data = {ptr = 0x28d, fd = 653, u32 = 653, u64 = 653}}, {events = 1, data = {ptr = 0x65a, fd = 1626, u32 = 1626, u64 = 1626}}, {events = 1, data = {
              ptr = 0x2d9, fd = 729, u32 = 729, u64 = 729}}, {events = 1, data = {ptr = 0x592, fd = 1426, u32 = 1426, u64 = 1426}}, {events = 1, data = {ptr = 0x204, fd = 516, u32 = 516, u64 = 516}},
          {events = 1, data = {ptr = 0x2c7, fd = 711, u32 = 711, u64 = 711}}, {events = 1, data = {ptr = 0x6e, fd = 110, u32 = 110, u64 = 110}}, {events = 1, data = {ptr = 0x2ad, fd = 685, u32 = 685,
              u64 = 685}}, {events = 1, data = {ptr = 0x271, fd = 625, u32 = 625, u64 = 625}}, {events = 1, data = {ptr = 0x7ea, fd = 2026, u32 = 2026, u64 = 2026}}, {events = 1, data = {ptr = 0x3d6,
              fd = 982, u32 = 982, u64 = 982}}, {events = 1, data = {ptr = 0x498, fd = 1176, u32 = 1176, u64 = 1176}}, {events = 1, data = {ptr = 0x22d, fd = 557, u32 = 557, u64 = 557}}, {events = 1,
            data = {ptr = 0x75a, fd = 1882, u32 = 1882, u64 = 1882}}, {events = 1, data = {ptr = 0x562, fd = 1378, u32 = 1378, u64 = 1378}}, {events = 1, data = {ptr = 0x7d6, fd = 2006, u32 = 2006,
              u64 = 2006}}, {events = 1, data = {ptr = 0x45d, fd = 1117, u32 = 1117, u64 = 1117}}, {events = 1, data = {ptr = 0x516, fd = 1302, u32 = 1302, u64 = 1302}}, {events = 1, data = {
              ptr = 0x321, fd = 801, u32 = 801, u64 = 801}}, {events = 1, data = {ptr = 0x9d, fd = 157, u32 = 157, u64 = 157}}, {events = 1, data = {ptr = 0x79a, fd = 1946, u32 = 1946, u64 = 1946}}, {
            events = 1, data = {ptr = 0x72e, fd = 1838, u32 = 1838, u64 = 1838}}, {events = 1, data = {ptr = 0x77e, fd = 1918, u32 = 1918, u64 = 1918}}, {events = 1, data = {ptr = 0x2c7, fd = 711,
              u32 = 711, u64 = 711}}, {events = 1, data = {ptr = 0x48d, fd = 1165, u32 = 1165, u64 = 1165}}, {events = 1, data = {ptr = 0x74e, fd = 1870, u32 = 1870, u64 = 1870}}, {events = 1,
            data = {ptr = 0x85, fd = 133, u32 = 133, u64 = 133}}, {events = 1, data = {ptr = 0x7f6, fd = 2038, u32 = 2038, u64 = 2038}}, {events = 1, data = {ptr = 0x7fa, fd = 2042, u32 = 2042,
              u64 = 2042}}, {events = 1, data = {ptr = 0x30d, fd = 781, u32 = 781, u64 = 781}}, {events = 1, data = {ptr = 0x171, fd = 369, u32 = 369, u64 = 369}}, {events = 1, data = {ptr = 0x70a,
              fd = 1802, u32 = 1802, u64 = 1802}}, {events = 1, data = {ptr = 0x481, fd = 1153, u32 = 1153, u64 = 1153}}, {events = 1, data = {ptr = 0x307, fd = 775, u32 = 775, u64 = 775}}, {
            events = 1, data = {ptr = 0xf9, fd = 249, u32 = 249, u64 = 249}}, {events = 1, data = {ptr = 0x594, fd = 1428, u32 = 1428, u64 = 1428}}, {events = 1, data = {ptr = 0x614, fd = 1556,
              u32 = 1556, u64 = 1556}}, {events = 1, data = {ptr = 0x6e9, fd = 1769, u32 = 1769, u64 = 1769}}, {events = 1, data = {ptr = 0x689, fd = 1673, u32 = 1673, u64 = 1673}}, {events = 1,
            data = {ptr = 0x120, fd = 288, u32 = 288, u64 = 288}}, {events = 1, data = {ptr = 0x17d, fd = 381, u32 = 381, u64 = 381}}, {events = 1, data = {ptr = 0x40e, fd = 1038, u32 = 1038,
              u64 = 1038}}, {events = 1, data = {ptr = 0x198, fd = 408, u32 = 408, u64 = 408}}, {events = 1, data = {ptr = 0x3ab, fd = 939, u32 = 939, u64 = 939}}, {events = 1, data = {ptr = 0x110,
              fd = 272, u32 = 272, u64 = 272}}, {events = 1, data = {ptr = 0x70d, fd = 1805, u32 = 1805, u64 = 1805}}, {events = 1, data = {ptr = 0x434, fd = 1076, u32 = 1076, u64 = 1076}}, {
            events = 1, data = {ptr = 0x68a, fd = 1674, u32 = 1674, u64 = 1674}}, {events = 1, data = {ptr = 0x22a, fd = 554, u32 = 554, u64 = 554}}, {events = 1, data = {ptr = 0x3f7, fd = 1015,
              u32 = 1015, u64 = 1015}}, {events = 1, data = {ptr = 0x306, fd = 774, u32 = 774, u64 = 774}}, {events = 1, data = {ptr = 0x8a0, fd = 2208, u32 = 2208, u64 = 2208}}, {events = 1, data = {
              ptr = 0x2f, fd = 47, u32 = 47, u64 = 47}}, {events = 1, data = {ptr = 0x2be, fd = 702, u32 = 702, u64 = 702}}, {events = 1, data = {ptr = 0x6be, fd = 1726, u32 = 1726, u64 = 1726}}, {
            events = 1, data = {ptr = 0x82a, fd = 2090, u32 = 2090, u64 = 2090}}, {events = 1, data = {ptr = 0x65a, fd = 1626, u32 = 1626, u64 = 1626}}, {events = 1, data = {ptr = 0x804, fd = 2052,
              u32 = 2052, u64 = 2052}}, {events = 1, data = {ptr = 0x532, fd = 1330, u32 = 1330, u64 = 1330}}, {events = 1, data = {ptr = 0x6e0, fd = 1760, u32 = 1760, u64 = 1760}}, {events = 1,
            data = {ptr = 0x8ac, fd = 2220, u32 = 2220, u64 = 2220}}, {events = 1, data = {ptr = 0x57, fd = 87, u32 = 87, u64 = 87}}, {events = 1, data = {ptr = 0x1ad, fd = 429, u32 = 429,
              u64 = 429}}, {events = 1, data = {ptr = 0xd2, fd = 210, u32 = 210, u64 = 210}}, {events = 1, data = {ptr = 0x329, fd = 809, u32 = 809, u64 = 809}}, {events = 1, data = {ptr = 0x12c,
              fd = 300, u32 = 300, u64 = 300}}, {events = 1, data = {ptr = 0x74d, fd = 1869, u32 = 1869, u64 = 1869}}, {events = 1, data = {ptr = 0x75a, fd = 1882, u32 = 1882, u64 = 1882}}, {
            events = 1, data = {ptr = 0x83a, fd = 2106, u32 = 2106, u64 = 2106}}, {events = 1, data = {ptr = 0x72c, fd = 1836, u32 = 1836, u64 = 1836}}, {events = 1, data = {ptr = 0x275, fd = 629,
              u32 = 629, u64 = 629}}, {events = 1, data = {ptr = 0x3a9, fd = 937, u32 = 937, u64 = 937}}, {events = 1, data = {ptr = 0x6d, fd = 109, u32 = 109, u64 = 109}}, {events = 1, data = {
              ptr = 0x4fe, fd = 1278, u32 = 1278, u64 = 1278}}, {events = 1, data = {ptr = 0x11d, fd = 285, u32 = 285, u64 = 285}}}
        ev = <optimized out>
        e = {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}
#8  0x000055f07cab2f9d in poller_loop (d=0x55f07ecfc690) at poller.c:505
        p = 0x55f07ecfc690
#9  0x000055f07cab30b3 in thread_detach_func (d=0x55f07ecfc880) at aux.c:209
        dt = 0x55f07ecfc880
        t = 0x7fddb8001aa0
---Type <return> to continue, or q <return> to quit---
        scheduler = <optimized out>
#10 0x00007fdde44276db in start_thread (arg=0x7fddc92c9700) at pthread_create.c:463
        pd = 0x7fddc92c9700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140590539642624, -34683867435270028, 140590539638208, 0, 94491408058496, 140733031255440, 17826853797855348, 17750173183737972},
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#11 0x00007fdde415088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
(gdb)
```

Regards
Rizwan

**Comment by rfuchs** [comment]
Fixed already in 08fc0090
