### ISSUE TITLE
Random crash on rtpengine 6.5

### ISSUE THREAD

**Issue by ZikiBe** [sipwise/rtpengine#622]
Hi,

I'm encountering some random crashes of rtpengine. Here's the GDB backtrace:

```
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/rtpengine...Reading symbols from /usr/lib/debug/.build-id/d4/635817fd09714b383dcaeae49e017db060f95c.debug...done.
done.
[New LWP 11986]
[New LWP 11977]
[New LWP 11980]
[New LWP 11981]
[New LWP 11982]
[New LWP 11983]
[New LWP 11984]
[New LWP 11985]
[New LWP 11987]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rtpengine -f -E --pidfile /var/run/ngcp-rtpengine-daemon.pid --config'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f5dceca4700 (LWP 11986))]
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {18446744067266837211, 3472328322906874981, 3472310980127322656, 3467824696600309808, 4121692098308094520, 2314885530819705144, 2314885530818453536, 2314885530818453536, 3907004821653777455, 8461816663211521631, 
            7236210882687479160, 8030813362246791725, 7378133570606741258, 7365405400577880929, 3486179077006910517, 2337418197644357680}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007f5de7df742a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x3030303332303030, sa_sigaction = 0x3030303332303030}, sa_mask = {__val = {3539883390318161952, 2314885612843841843, 2314885530818453536, 2314885530818453536, 8660248813382869024, 7596496373740942904, 
              3419760881481315694, 3329341198525359212, 7306023208628154227, 3256155514234889828, 7378695426128832055, 3276212736508309560, 3473456395157774448, 3544396919740575792, 2320261146666545440, 140040878033776}}, sa_flags = 89, 
          sa_restorer = 0x7f5dceca0b70}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007f5de7e33c00 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7f5de7f28d98 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
        ap = {{gp_offset = 40, fp_offset = 32605, overflow_arg_area = 0x7f5dceca0b80, reg_save_area = 0x7f5dceca0b10}}
        fd = 2
        on_2 = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
#3  0x00007f5de7e39fc6 in malloc_printerr (action=3, str=0x7f5de7f258de "corrupted size vs. prev_size", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5049
        buf = "00007f5dc80303f0"
        cp = <optimized out>
        ar_ptr = <optimized out>
        ptr = <optimized out>
        str = 0x7f5de7f258de "corrupted size vs. prev_size"
        action = 3
#4  0x00007f5de7e3d21d in _int_realloc (av=av@entry=0x7f5dc8000020, oldp=oldp@entry=0x7f5dc80303d0, oldsize=oldsize@entry=32, nb=nb@entry=80) at malloc.c:4336
        newp = 0x7f5dc80303d0
        newsize = 62840
        newmem = <optimized out>
        next = 0x7f5dc80303f0
        remainder = <optimized out>
        remainder_size = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        copysize = <optimized out>
        ncopies = <optimized out>
        s = <optimized out>
        d = <optimized out>
        errstr = 0x0
        __func__ = "_int_realloc"
        nextsize = <optimized out>
#5  0x00007f5de7e3e719 in __GI___libc_realloc (oldmem=0x7f5dc80303e0, bytes=64) at malloc.c:3083
        ar_ptr = 0x7f5dc8000020
        nb = 80
        newp = <optimized out>
        hook = <optimized out>
        oldp = 0x7f5dc80303d0
        oldsize = 32
        __func__ = "__libc_realloc"
#6  0x00007f5ded80aec8 in g_realloc () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#7  0x00007f5ded827507 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#8  0x00007f5ded828681 in g_string_append_vprintf () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#9  0x00007f5ded8288a4 in g_string_append_printf () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#10 0x0000558793ed8d03 in logging_start (ctx=0x7f5dceca0dc0, c=<optimized out>) at rtcp.c:1091
No locals.
#11 0x0000558793ed9151 in rtcp_parse (q=q@entry=0x7f5dceca0eb0, mp=mp@entry=0x7f5dceca0f48) at rtcp.c:665
        func = <optimized out>
        s = {s = 0x7f5dceca1070 "\201", <incomplete sequence \310>, len = 100}
        c = 0x7f5dc000d3c0
        log_ctx_s = {mp = 0x7f5dceca0f48, scratch = {rr = {from = 0, ssrc = 0, fraction_lost = 0 '\000', packets_lost = 0, high_seq_received = 0, jitter = 0, lsr = 0, dlsr = 0}, sr = {ssrc = 0, ntp_msw = 0, ntp_lsw = 0, timestamp = 0, packet_count = 0, 
              octet_count = 0}, xr_vm = {from = 0, ssrc = 0, loss_rate = 0 '\000', discard_rate = 0 '\000', burst_den = 0 '\000', gap_den = 0 '\000', burst_dur = 0, gap_dur = 0, rnd_trip_delay = 0, end_sys_delay = 0, signal_lvl = 0 '\000', 
              noise_lvl = 0 '\000', rerl = 0 '\000', gmin = 0 '\000', r_factor = 0 '\000', ext_r_factor = 0 '\000', mos_lq = 0 '\000', mos_cq = 0 '\000', rx_config = 0 '\000', jb_nom = 0, jb_max = 0, jb_abs_max = 0}, xr_rr = {ssrc = 0, ntp_msw = 0, 
              ntp_lsw = 0}, xr_dlrr = {from = 0, ssrc = 0, lrr = 0, dlrr = 0}}, scratch_common_ssrc = 0, log = 0x7f5dc8016220, log_init_len = 0, json = 0x0, json_init_len = 0}
        log_ctx = 0x7f5dceca0dc0
        len = <optimized out>
---Type <return> to continue, or q <return> to quit---
        ret = <optimized out>
        min_packet_size = <optimized out>
#12 0x0000558793ef129c in do_rtcp (phc=0x7f5dceca0ef0) at media_socket.c:1554
        ret = -1
        rtcp_list = {head = 0x0, tail = 0x0, length = 0}
#13 stream_packet (phc=0x7f5dceca0ef0) at media_socket.c:1658
        ret = 0
        handler_ret = <optimized out>
        p = <optimized out>
#14 stream_fd_readable (fd=<optimized out>, p=0x7f5dc002a840, u=<optimized out>) at media_socket.c:1791
        phc = {s = {s = 0x7f5dceca1070 "\201", <incomplete sequence \310>, len = 100}, sink = 0x7f5db8031600, decrypt_func = 0x0, encrypt_func = 0x0, rtcp_filter = 0x0, in_srtp = 0x7f5db8031000, out_srtp = 0x7f5db8031600, payload_type = -1, rtcp = 1, 
          update = 0, unkernelize = 0, kernelize = 0, mp = {raw = {s = 0x7f5dceca1070 "\201", <incomplete sequence \310>, len = 100}, fsin = {address = {family = 0x55879411db20 <__socket_families>, u = {ipv4 = {s_addr = 342272192}, ipv6 = {__in6_u = {
                      __u6_addr8 = "\300\250f\024", '\000' <repeats 11 times>, __u6_addr16 = {43200, 5222, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {342272192, 0, 0, 0}}}}}, port = 34023}, tv = {tv_sec = 1537792318, tv_usec = 858903}, sfd = 0x7f5dc002a840, 
            call = 0x7f5dc000d3c0, stream = 0x7f5db8031000, media = 0x7f5dc800f210, rtp = 0x0, rtcp = 0x7f5dceca1070, ssrc_in = 0x7f5dc8028c50, ssrc_out = 0x7f5dc8028e70, payload = {s = 0x0, len = 0}, packets_out = {head = 0x0, tail = 0x0, length = 0}}}
        sfd = 0x7f5dc002a840
        buf = '\000' <repeats 128 times>, "\201\310\000\f$\245\256\207\337SW\276\334n}\200\000\000\000\000\000\000\b\310\000\005}\000\"U\310\063\000\000\000\000\000\000\212\223\000\000\000\002\000\000\000\000\000\000\000\000\201\312\000\v$\245\256\207\001$f904851b-77"...
        ret = <optimized out>
        iters = 0
        update = <optimized out>
        ca = <optimized out>
#15 0x0000558793ebd548 in poller_poll (p=p@entry=0x5587941f2520, timeout=timeout@entry=100) at poller.c:350
        ret = 1
        i = <optimized out>
        it = 0x7f5db803c400
        evs = {{events = 1, data = {ptr = 0xd, fd = 13, u32 = 13, u64 = 13}}, {events = 1, data = {ptr = 0xa, fd = 10, u32 = 10, u64 = 10}}, {events = 1, data = {ptr = 0x12, fd = 18, u32 = 18, u64 = 18}}, {events = 0, data = {ptr = 0x6f, fd = 111, 
              u32 = 111, u64 = 111}}, {events = 3992860944, data = {ptr = 0xe8162f1800007f5d, fd = 32605, u32 = 32605, u64 = 16723606046412668765}}, {events = 32605, data = {ptr = 0x7f5de8164f10, fd = -401191152, u32 = 3893776144, 
              u64 = 140041302462224}}, {events = 3990735795, data = {ptr = 0x6f00007f5d, fd = 32605, u32 = 32605, u64 = 476741402461}}, {events = 0, data = {ptr = 0x7f5de8164f10, fd = -401191152, u32 = 3893776144, u64 = 140041302462224}}, {
            events = 3992860944, data = {ptr = 0xceca33d800007f5d, fd = 32605, u32 = 32605, u64 = 14900779319914692445}}, {events = 32605, data = {ptr = 0x7f5dceca33d4, fd = -825609260, u32 = 3469358036, u64 = 140040878044116}}, {events = 3990734123, 
            data = {ptr = 0x93eaf71600007f5d, fd = 32605, u32 = 32605, u64 = 10658603141987073885}}, {events = 21895, data = {ptr = 0x558793eabfb0, fd = -1813332048, u32 = 2481635248, u64 = 94040790581168}}, {events = 3469358040, data = {
              ptr = 0x5d8cc7600007f5d, fd = 32605, u32 = 32605, u64 = 421311372337381213}}, {events = 0, data = {ptr = 0x176331, fd = 1532721, u32 = 1532721, u64 = 1532721}}, {events = 3893776144, data = {ptr = 0xceca34b000007f5d, fd = 32605, 
              u32 = 32605, u64 = 14900780247627628381}}, {events = 32605, data = {ptr = 0x7f5de8162f18, fd = -401199336, u32 = 3893767960, u64 = 140041302454040}}, {events = 3469358036, data = {ptr = 0xceca34a000007f5d, fd = 32605, u32 = 32605, 
              u64 = 14900780178908151645}}, {events = 32605, data = {ptr = 0x7f5dedfb24f0, fd = -302308112, u32 = 3992659184, u64 = 140041401345264}}, {events = 157, data = {ptr = 0xedfe000000000000, fd = 0, u32 = 0, u64 = 17149144431073427456}}, {
            events = 0, data = {ptr = 0x7f5dceca3458, fd = -825609128, u32 = 3469358168, u64 = 140040878044248}}, {events = 3469358164, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7f5de81650b1, fd = -401190735, 
              u32 = 3893776561, u64 = 140041302462641}}, {events = 3992945864, data = {ptr = 0xceca354000007f5d, fd = 32605, u32 = 32605, u64 = 14900780866102919005}}, {events = 32605, data = {ptr = 0x7f5dedfb2a08, fd = -302306808, u32 = 3992660488, 
              u64 = 140041401346568}}, {events = 5, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7f5dceca3568, fd = -825608856, u32 = 3469358440, u64 = 140040878044520}}, {events = 3990737089, data = {ptr = 0x1d00007f5d, 
              fd = 32605, u32 = 32605, u64 = 124554084189}}, {events = 0, data = {ptr = 0x7f5dedfb2a08, fd = -302306808, u32 = 3992660488, u64 = 140041401346568}}, {events = 5, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {
              ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 3992945008, data = {ptr = 0x7f5d, fd = 32605, u32 = 32605, u64 = 32605}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0xedff84c800000000, fd = 0, 
              u32 = 0, u64 = 17149571900578463744}}, {events = 32605, data = {ptr = 0x7f5dceca34b0, fd = -825609040, u32 = 3469358256, u64 = 140040878044336}}, {events = 3992651912, data = {ptr = 0xedff817000000001, fd = 1, u32 = 1, 
              u64 = 17149568224086458369}}, {events = 32605, data = {ptr = 0x7f5dceca34a0, fd = -825609056, u32 = 3469358240, u64 = 140040878044320}}, {events = 2481649430, data = {ptr = 0x5d8cc7600005587, fd = 21895, u32 = 21895, 
              u64 = 421311372337370503}}, {events = 0, data = {ptr = 0xffffffff, fd = -1, u32 = 4294967295, u64 = 4294967295}}, {events = 3992651912, data = {ptr = 0xe816398000007f5d, fd = 32605, u32 = 32605, u64 = 16723617488205545309}}, {
            events = 32605, data = {ptr = 0x7f5dedfe3910, fd = -302106352, u32 = 3992860944, u64 = 140041401547024}}, {events = 1, data = {ptr = 0xedfe391000000000, fd = 0, u32 = 0, u64 = 17149207171955687424}}, {events = 32605, data = {ptr = 0x0, 
              fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7f5dedfe3c68, fd = -302105496, u32 = 3992861800, u64 = 140041401547880}}, {events = 3469358384, data = {ptr = 0x7f5d, 
              fd = 32605, u32 = 32605, u64 = 32605}}, {events = 1, data = {ptr = 0x7f5dedfe3910, fd = -302106352, u32 = 3992860944, u64 = 140041401547024}}, {events = 3469358368, data = {ptr = 0xe81650b100007f5d, fd = 32605, u32 = 32605, 
              u64 = 16723642987426381661}}, {events = 32605, data = {ptr = 0x55879411c428, fd = -1810775000, u32 = 2484192296, u64 = 94040793138216}}, {events = 2484941664, data = {ptr = 0x1ba2f05f00005587, fd = 21895, u32 = 21895, 
              u64 = 1991418276063761799}}, {events = 32767, data = {ptr = 0x5587941cfbc0, fd = -1810039872, u32 = 2484927424, u64 = 94040793873344}}, {events = 3992940608, data = {ptr = 0x7f5d, fd = 32605, u32 = 32605, u64 = 32605}}, {events = 0, data = {
              ptr = 0x7f5dedde1c54 <_dl_fixup+212>, fd = -304210860, u32 = 3990756436, u64 = 140041399442516}}, {events = 5, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 3893770624, 
            data = {ptr = 0xceca392000007f5d, fd = 32605, u32 = 32605, u64 = 14900785126710476637}}, {events = 32605, data = {ptr = 0x7f5dedde929a <_dl_runtime_resolve_xsave+138>, fd = -304180582, u32 = 3990786714, u64 = 140041399472794}}, {
            events = 2484927424, data = {ptr = 0xc00005587, fd = 21895, u32 = 21895, u64 = 51539629447}}, {events = 0, data = {ptr = 0x32, fd = 50, u32 = 50, u64 = 50}}, {events = 1, data = {ptr = 0xedace32000000000, fd = 0, u32 = 0, 
              u64 = 17126313209561612288}}, {events = 32605, data = {ptr = 0x7f5dc80014d0, fd = -939518768, u32 = 3355448528, u64 = 140040764134608}}, {events = 560, data = {ptr = 0xedff704000000000, fd = 0, u32 = 0, u64 = 17149549326230355968}}, {
            events = 32605, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 3990756436, data = {ptr = 0x500007f5d, fd = 32605, u32 = 32605, u64 = 21474869085}}, {events = 0, data = {ptr = 0xffff00001fa0, fd = 8096, u32 = 8096, 
              u64 = 281470681751456}}, {events = 0, data = {ptr = 0xe7dcca6000000000, fd = 0, u32 = 0, u64 = 16707451231303368704}}, {events = 32605, data = {ptr = 0x7f5dceca3980, fd = -825607808, u32 = 3469359488, u64 = 140040878045568}}, {
            events = 3990786714, data = {ptr = 0x7f5d, fd = 32605, u32 = 32605, u64 = 32605}}, {events = 0, data = {ptr = 0x7f5de8169434 <start_thread+100>, fd = -401173452, u32 = 3893793844, u64 = 140041302479924}}, {events = 4294966648, data = {
              ptr = 0x18ffffffff, fd = -1, u32 = 4294967295, u64 = 107374182399}}, {events = 0, data = {ptr = 0x7f5dceca39b0, fd = -825607760, u32 = 3469359536, u64 = 140040878045616}}, {events = 3469362944, data = {ptr = 0xceca470000007f5d, fd = 32605, 
              u32 = 32605, u64 = 14900800382434312029}}, {events = 32605, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {
            events = 8096, data = {ptr = 0xffff, fd = 65535, u32 = 65535, u64 = 65535}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 4294967295, data = {ptr = 0xffffffffffffffff, fd = -1, u32 = 4294967295, 
              u64 = 18446744073709551615}}, {events = 4294967295, data = {ptr = 0xffffffffffffffff, fd = -1, u32 = 4294967295, u64 = 18446744073709551615}}, {events = 4294967295, data = {ptr = 0xffffffffffffffff, fd = -1, u32 = 4294967295, 
              u64 = 18446744073709551615}}, {events = 4294967295, data = {ptr = 0xffffffffffffffff, fd = -1, u32 = 4294967295, u64 = 18446744073709551615}}, {events = 4278190080, data = {ptr = 0xffff0000, fd = -65536, u32 = 4294901760, 
              u64 = 4294901760}}, {events = 4294901760, data = {ptr = 0xdf00000000000, fd = 0, u32 = 0, u64 = 3923057487904768}}, {events = 3670016, data = {ptr = 0xe0000004c600, fd = 312832, u32 = 312832, u64 = 246290604934656}}, {events = 7400960, 
            data = {ptr = 0x369e00000ee000, fd = 974848, u32 = 974848, u64 = 15373371580538880}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {
              ptr = 0xca62c1d600000000, fd = 0, u32 = 0, u64 = 14583431668246249472}}, {events = 3629339094, data = {ptr = 0xcf2a35d60263a1d6, fd = 40083926, u32 = 40083926, u64 = 14927803108152287702}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, 
              u64 = 0}}, {events = 0, data = {ptr = 0xca62c1d6ca62c1d6, fd = -899497514, u32 = 3395469782, u64 = 14583431671641719254}}, {events = 3395469782, data = {ptr = 0xca62c1d6, fd = -899497514, u32 = 3395469782, u64 = 3395469782}}, {events = 0, 
            data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, 
            data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 3355443312, data = {ptr = 0x7f5d, fd = 32605, u32 = 32605, u64 = 32605}}, {events = 0, data = {ptr = 0xd85351d6ca62c1d6, fd = -899497514, u32 = 3395469782, u64 = 15587892718219739606}}, 
          {events = 64, data = {ptr = 0x42000007f5d, fd = 32605, u32 = 32605, u64 = 4535485497181}}, {events = 0, data = {ptr = 0x450, fd = 1104, u32 = 1104, u64 = 1104}}, {events = 16, data = {ptr = 0x4300000000, fd = 0, u32 = 0, u64 = 287762808832}}, {
            events = 64, data = {ptr = 0x20000, fd = 131072, u32 = 131072, u64 = 131072}}, {events = 4096, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 110, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {
              ptr = 0x7700000000, fd = 0, u32 = 0, u64 = 511101108224}}, {events = 124, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 517, data = {ptr = 0xc800002000000000, fd = 0, u32 = 0, u64 = 14411518945024540672}}, {events = 32605, 
            data = {ptr = 0x200, fd = 512, u32 = 512, u64 = 512}}, {events = 2484768840, data = {ptr = 0x1000005587, fd = 21895, u32 = 21895, u64 = 68719498631}}, {events = 0, data = {ptr = 0x27, fd = 39, u32 = 39, u64 = 39}}, {events = 3890465407, 
            data = {ptr = 0x7f5d, fd = 32605, u32 = 32605, u64 = 32605}}, {events = 0, data = {ptr = 0x7f5dc8001a00, fd = -939517440, u32 = 3355449856, u64 = 140040764135936}}, {events = 512, data = {ptr = 0xc800002000000000, fd = 0, u32 = 0, 
              u64 = 14411518945024540672}}, {events = 32605, data = {ptr = 0x1f0, fd = 496, u32 = 496, u64 = 496}}, {events = 2484768840, data = {ptr = 0x1000005587, fd = 21895, u32 = 21895, u64 = 68719498631}}, {events = 0, data = {
---Type <return> to continue, or q <return> to quit---
              ptr = 0x7f5de7e3e35f <_mid_memalign+159>, fd = -404495521, u32 = 3890471775, u64 = 140041299157855}}, {events = 3469359232, data = {ptr = 0x2000007f5d, fd = 32605, u32 = 32605, u64 = 137438986077}}, {events = 0, data = {ptr = 0x200, 
              fd = 512, u32 = 512, u64 = 512}}, {events = 3890479087, data = {ptr = 0x941d2dd000007f5d, fd = 32605, u32 = 32605, u64 = 10672737063314423645}}, {events = 21895, data = {ptr = 0x7f5ded822c72, fd = -310236046, u32 = 3984731250, 
              u64 = 140041393417330}}, {events = 3355449856, data = {ptr = 0x2a8fa30000007f5d, fd = 32605, u32 = 32605, u64 = 3066849091657957213}}, {events = 68651177, data = {ptr = 0x7f5dc8001b60, fd = -939517088, u32 = 3355450208, 
              u64 = 140040764136288}}, {events = 3355445472, data = {ptr = 0x1800007f5d, fd = 32605, u32 = 32605, u64 = 103079247709}}, {events = 0, data = {ptr = 0x7f5dc80008c0, fd = -939521856, u32 = 3355445440, u64 = 140040764131520}}, {events = 16, 
            data = {ptr = 0xed82394000000000, fd = 0, u32 = 0, u64 = 17114304481001996288}}, {events = 32605, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 2485102208, data = {ptr = 0x2000005587, fd = 21895, u32 = 21895, u64 = 137438975367}}, {
            events = 0, data = {ptr = 0x33, fd = 51, u32 = 51, u64 = 51}}}
        e = {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}
#16 0x0000558793ebd8ed in poller_loop (d=0x5587941f2520) at poller.c:505
        p = 0x5587941f2520
#17 0x0000558793ebda09 in thread_detach_func (d=0x5587941d3360) at aux.c:209
        dt = 0x5587941d3360
        t = 0x5587941cfbc0
        scheduler = <optimized out>
#18 0x00007f5de8169494 in start_thread (arg=0x7f5dceca4700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f5dceca4700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140040878049024, 3422564418479138662, 0, 140733657051231, 0, 140041401626688, -3331263354678859930, -3331339802046027930}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, 
              cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#19 0x00007f5de7eabacf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
No locals.
```

Can anyone help me on this?

Thank you,

Cyrille

**Comment by rfuchs** [comment]
Which version/build/commit is this from?
