### ISSUE TITLE
Random crash on Version: 7.1.0.0+0~mr7.1.0.0 git-master-fb1083f

### ISSUE THREAD

**Issue by formater** [sipwise/rtpengine#684]
Hi,
 We encounter a segfault, we are using TCP connections, for example CLI a lot, if that helps.

Here is the backtrace:
root@rtpe-glo-did02  /  gdb rtpengine core
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from rtpengine...Reading symbols from /usr/lib/debug/.build-id/2b/d83377789cc0619914ba089523aa9a40256852.debug...done.
done.
[New LWP 768]
[New LWP 766]
[New LWP 765]
[New LWP 764]
[New LWP 767]
[New LWP 714]
[New LWP 769]
[New LWP 770]
[New LWP 771]
[New LWP 772]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rtpengine -f -E --pidfile /var/run/ngcp-rtpengine-daemon.pid --config'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f101f861700 (LWP 768))]
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {18446744067266837211, 0, 14583431671641719254, 14583431671641719254, 0, 9026692772936010231, 0, 0, 0, 0, 0, 0, 0, 139707717290618, 0, 139707626554361}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007f10373c542a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 13 times>, 140724118482262, 0, 8251213320}}, sa_flags = -338721280, sa_restorer = 0x5625ebcf8600}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00005625eb424785 in poller_poll (p=p@entry=0x5625ebcf8600, timeout=timeout@entry=100) at poller.c:344
        ret = 1
        i = <optimized out>
        it = 0x7f0ff804d180
        evs = {{events = 4, data = {ptr = 0xaff, fd = 2815, u32 = 2815, u64 = 2815}}, {events = 1, data = {ptr = 0x564, fd = 1380, u32 = 1380, u64 = 1380}}, {events = 1, data = {ptr = 0xaeb, fd = 2795, u32 = 2795, u64 = 2795}}, {events = 1, data = {ptr = 0x1db, fd = 475, u32 = 475, u64 = 475}}, {events = 1,
            data = {ptr = 0x7be, fd = 1982, u32 = 1982, u64 = 1982}}, {events = 1, data = {ptr = 0x9d9, fd = 2521, u32 = 2521, u64 = 2521}}, {events = 1, data = {ptr = 0x370, fd = 880, u32 = 880, u64 = 880}}, {events = 1, data = {ptr = 0xef, fd = 239, u32 = 239, u64 = 239}}, {events = 1, data = {ptr = 0x4d7,
              fd = 1239, u32 = 1239, u64 = 1239}}, {events = 1, data = {ptr = 0x3b5, fd = 949, u32 = 949, u64 = 949}}, {events = 1, data = {ptr = 0x18b, fd = 395, u32 = 395, u64 = 395}}, {events = 1, data = {ptr = 0x6e7, fd = 1767, u32 = 1767, u64 = 1767}}, {events = 1, data = {ptr = 0x662, fd = 1634, u32 = 1634,
              u64 = 1634}}, {events = 1, data = {ptr = 0x22d, fd = 557, u32 = 557, u64 = 557}}, {events = 1, data = {ptr = 0x89f, fd = 2207, u32 = 2207, u64 = 2207}}, {events = 1, data = {ptr = 0x9f7, fd = 2551, u32 = 2551, u64 = 2551}}, {events = 1, data = {ptr = 0x370, fd = 880, u32 = 880, u64 = 880}}, {
            events = 1, data = {ptr = 0xae, fd = 174, u32 = 174, u64 = 174}}, {events = 1, data = {ptr = 0x12b, fd = 299, u32 = 299, u64 = 299}}, {events = 1, data = {ptr = 0x73e, fd = 1854, u32 = 1854, u64 = 1854}}, {events = 1, data = {ptr = 0xa2f, fd = 2607, u32 = 2607, u64 = 2607}}, {events = 1, data = {
              ptr = 0x578, fd = 1400, u32 = 1400, u64 = 1400}}, {events = 1, data = {ptr = 0x309, fd = 777, u32 = 777, u64 = 777}}, {events = 1, data = {ptr = 0xec, fd = 236, u32 = 236, u64 = 236}}, {events = 1, data = {ptr = 0x765, fd = 1893, u32 = 1893, u64 = 1893}}, {events = 1, data = {ptr = 0x14a, fd = 330,
              u32 = 330, u64 = 330}}, {events = 1, data = {ptr = 0x8cb, fd = 2251, u32 = 2251, u64 = 2251}}, {events = 1, data = {ptr = 0x1db, fd = 475, u32 = 475, u64 = 475}}, {events = 1, data = {ptr = 0xaa9, fd = 2729, u32 = 2729, u64 = 2729}}, {events = 1, data = {ptr = 0x58f, fd = 1423, u32 = 1423,
              u64 = 1423}}, {events = 1, data = {ptr = 0x4d7, fd = 1239, u32 = 1239, u64 = 1239}}, {events = 1, data = {ptr = 0x197, fd = 407, u32 = 407, u64 = 407}}, {events = 1, data = {ptr = 0x354, fd = 852, u32 = 852, u64 = 852}}, {events = 1, data = {ptr = 0x7d6, fd = 2006, u32 = 2006, u64 = 2006}}, {
            events = 1, data = {ptr = 0x52, fd = 82, u32 = 82, u64 = 82}}, {events = 1, data = {ptr = 0x2bd, fd = 701, u32 = 701, u64 = 701}}, {events = 1, data = {ptr = 0x9e7, fd = 2535, u32 = 2535, u64 = 2535}}, {events = 1, data = {ptr = 0xef, fd = 239, u32 = 239, u64 = 239}}, {events = 1, data = {ptr = 0x52d,
              fd = 1325, u32 = 1325, u64 = 1325}}, {events = 1, data = {ptr = 0x2a0, fd = 672, u32 = 672, u64 = 672}}, {events = 1, data = {ptr = 0x25a, fd = 602, u32 = 602, u64 = 602}}, {events = 1, data = {ptr = 0x2b3, fd = 691, u32 = 691, u64 = 691}}, {events = 1, data = {ptr = 0x3a9, fd = 937, u32 = 937,
              u64 = 937}}, {events = 1, data = {ptr = 0x601, fd = 1537, u32 = 1537, u64 = 1537}}, {events = 1, data = {ptr = 0x530, fd = 1328, u32 = 1328, u64 = 1328}}, {events = 1, data = {ptr = 0x89f, fd = 2207, u32 = 2207, u64 = 2207}}, {events = 1, data = {ptr = 0x9dd, fd = 2525, u32 = 2525, u64 = 2525}}, {
            events = 1, data = {ptr = 0x2d7, fd = 727, u32 = 727, u64 = 727}}, {events = 1, data = {ptr = 0x5a9, fd = 1449, u32 = 1449, u64 = 1449}}, {events = 1, data = {ptr = 0x999, fd = 2457, u32 = 2457, u64 = 2457}}, {events = 1, data = {ptr = 0x854, fd = 2132, u32 = 2132, u64 = 2132}}, {events = 1, data = {
              ptr = 0x5d4, fd = 1492, u32 = 1492, u64 = 1492}}, {events = 1, data = {ptr = 0x9cb, fd = 2507, u32 = 2507, u64 = 2507}}, {events = 1, data = {ptr = 0x921, fd = 2337, u32 = 2337, u64 = 2337}}, {events = 1, data = {ptr = 0x29b, fd = 667, u32 = 667, u64 = 667}}, {events = 1, data = {ptr = 0x63e,
              fd = 1598, u32 = 1598, u64 = 1598}}, {events = 1, data = {ptr = 0x2ad, fd = 685, u32 = 685, u64 = 685}}, {events = 1, data = {ptr = 0x8b8, fd = 2232, u32 = 2232, u64 = 2232}}, {events = 1, data = {ptr = 0x335, fd = 821, u32 = 821, u64 = 821}}, {events = 1, data = {ptr = 0x2f8, fd = 760, u32 = 760,
              u64 = 760}}, {events = 1, data = {ptr = 0xa43, fd = 2627, u32 = 2627, u64 = 2627}}, {events = 1, data = {ptr = 0x763, fd = 1891, u32 = 1891, u64 = 1891}}, {events = 1, data = {ptr = 0x8ff, fd = 2303, u32 = 2303, u64 = 2303}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0,
              u64 = 0}} <repeats 31 times>, {events = 0, data = {ptr = 0x400007000000000, fd = 0, u32 = 0, u64 = 288230857188048896}}, {events = 32528, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 67108976, data = {ptr = 0x7f10, fd = 32528, u32 = 32528, u64 = 32528}}, {events = 0, data = {ptr = 0x0,
              fd = 0, u32 = 0, u64 = 0}}, {events = 64, data = {ptr = 0x42000007f10, fd = 32528, u32 = 32528, u64 = 4535485497104}}, {events = 0, data = {ptr = 0x450, fd = 1104, u32 = 1104, u64 = 1104}}, {events = 16, data = {ptr = 0x4300000000, fd = 0, u32 = 0, u64 = 287762808832}}, {events = 64, data = {
              ptr = 0x20000, fd = 131072, u32 = 131072, u64 = 131072}}, {events = 4096, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 110, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7700000000, fd = 0, u32 = 0, u64 = 511101108224}}, {events = 124, data = {
              ptr = 0x6e00000000, fd = 0, u32 = 0, u64 = 472446402560}}, {events = 517, data = {ptr = 0x400002000000000, fd = 0, u32 = 0, u64 = 288230513590665216}}, {events = 32528, data = {ptr = 0x200, fd = 512, u32 = 512, u64 = 512}}, {events = 3955961928, data = {ptr = 0x1000005625, fd = 22053, u32 = 22053,
              u64 = 68719498789}}, {events = 0, data = {ptr = 0x28, fd = 40, u32 = 40, u64 = 40}}, {events = 926984831, data = {ptr = 0xebcb304000007f10, fd = 32528, u32 = 32528, u64 = 16990727070621400848}}, {events = 22053, data = {ptr = 0x7f1004001a00, fd = 67115520, u32 = 67115520, u64 = 139706763319808}}, {
            events = 512, data = {ptr = 0x400002000000000, fd = 0, u32 = 0, u64 = 288230513590665216}}, {events = 32528, data = {ptr = 0x1f0, fd = 496, u32 = 496, u64 = 496}}, {events = 3955961928, data = {ptr = 0x1000005625, fd = 22053, u32 = 22053, u64 = 68719498789}}, {events = 0, data = {
              ptr = 0x7f103740c35f <_mid_memalign+159>, fd = 926991199, u32 = 926991199, u64 = 139707623195487}}, {events = 528877504, data = {ptr = 0x2000007f10, fd = 32528, u32 = 32528, u64 = 137438986000}}, {events = 0, data = {ptr = 0x200, fd = 512, u32 = 512, u64 = 512}}, {events = 926998511, data = {
              ptr = 0xebcdcfd000007f10, fd = 32528, u32 = 32528, u64 = 16991465461398929168}}, {events = 22053, data = {ptr = 0x7f103cdf7c72, fd = 1021279346, u32 = 1021279346, u64 = 139707717483634}}, {events = 67115520, data = {ptr = 0x8743a90000007f10, fd = 32528, u32 = 32528, u64 = 9746819836025011984}}, {
            events = 4188343906, data = {ptr = 0x7f1004001b40, fd = 67115840, u32 = 67115840, u64 = 139706763320128}}, {events = 67111136, data = {ptr = 0x1800007f10, fd = 32528, u32 = 32528, u64 = 103079247632}}, {events = 0, data = {ptr = 0x7f10040008c0, fd = 67111104, u32 = 67111104, u64 = 139706763315392}}, {
            events = 16, data = {ptr = 0x3cdf894000000000, fd = 0, u32 = 0, u64 = 4386375470053064704}}, {events = 32528, data = {ptr = 0x8, fd = 8, u32 = 8, u64 = 8}}, {events = 7264, data = {ptr = 0x2000007f10, fd = 32528, u32 = 32528, u64 = 137438986000}}, {events = 0, data = {ptr = 0x33, fd = 51, u32 = 51,
              u64 = 51}}}
        e = {events = 2147483673, data = {ptr = 0xaff, fd = 2815, u32 = 2815, u64 = 2815}}
#3  0x00005625eb424b0d in poller_loop (d=0x5625ebcf8600) at poller.c:507
        p = 0x5625ebcf8600
#4  0x00005625eb424c29 in thread_detach_func (d=0x5625ebcdd020) at aux.c:209
        dt = 0x5625ebcdd020
        t = 0x7f1000001480
        scheduler = <optimized out>
#5  0x00007f1037737494 in start_thread (arg=0x7f101f861700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f101f861700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139707225085696, -7570873400013611898, 0, 140724117930671, 0, 139707725692992, 7552226295145045126, 7552171707562597510}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007f1037479acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
No locals.

It is rtpengine 7.1.0.0+0~mr7.1.0.0 git-master-fb1083f, Debian 9.6, kernel 4.9.0-8-amd64

Any idea? :)
Thanks in advance, 
 Joseph

**Comment by formater** [comment]
Maybe it is still the same as last one:
https://github.com/sipwise/rtpengine/issues/669

But that patch is applied in this version, and seems it does not help.
