### ISSUE TITLE
Core dump signal: 8 (FPE) when DTMF is processed

### ISSUE THREAD

**Issue by amessina** [sipwise/rtpengine#730]
```
Mar 10 10:22:32 rtpengine[31238]: DEBUG: [0_1274856370@10.77.79.116 port 30016]: bubble up pt 101 from idx 2 to 1
Mar 10 10:22:32 rtpengine[31238]: DEBUG: [0_1274856370@10.77.79.116 port 30016]: Received DTMF RTP packet: SSRC 723b56fd, PT 229, seq 7914, TS 815128588, len 4
Mar 10 10:22:32 rtpengine[31238]: DEBUG: [0_1274856370@10.77.79.116 port 30016]: Primary RTP payload type for handling DTMF event is 9
Mar 10 10:22:32 rtpengine[31238]: DEBUG: [0_1274856370@10.77.79.116 port 30016]: Decoding RTP packet: seq 7914, TS 815128588
Mar 10 10:22:32 rtpengine[31238]: DEBUG: [0_1274856370@10.77.79.116 port 30016]: DTMF event: event 5, volume 10, end 0, duration 40960
Mar 10 10:22:32 rtpengine[31238]: DEBUG: [0_1274856370@10.77.79.116 port 30016]: bubble up pt 101 from idx 2 to 1
Mar 10 10:22:32 rtpengine[31238]: DEBUG: [0_1274856370@10.77.79.116 port 30016]: Scheduling to send RTP packet (seq 7914 TS 815128588) at 1552231352.009273
Mar 10 10:22:32 rtpengine[31238]: DEBUG: [0_1274856370@10.77.79.116 port 30016]: Forward to sink endpoint: 10.1.10.2:37021 (RTP seq 7914 TS 815128588)
Mar 10 10:22:32 rtpengine[31238]: DEBUG: [0_1274856370@10.77.79.116 port 30016]: Received DTMF RTP packet: SSRC 723b56fd, PT 101, seq 7915, TS 815128588, len 4
Mar 10 10:22:32 rtpengine[31238]: DEBUG: [0_1274856370@10.77.79.116 port 30016]: Primary RTP payload type for handling DTMF event is 9
Mar 10 10:22:32 rtpengine[31238]: DEBUG: [0_1274856370@10.77.79.116 port 30016]: Decoding RTP packet: seq 7915, TS 815128588
Mar 10 10:22:32 rtpengine[31238]: DEBUG: [0_1274856370@10.77.79.116 port 30016]: DTMF event: event 5, volume 10, end 0, duration 16385
Mar 10 10:22:32 systemd[1]: rtpengine.service: Main process exited, code=killed, status=8/FPE
Mar 10 10:22:32 systemd[1]: rtpengine.service: Failed with result 'signal'.
```

```
~]# coredumpctl info 31238
           PID: 31238 (rtpengine)
           UID: 981 (rtpengine)
           GID: 979 (rtpengine)
        Signal: 8 (FPE)
     Timestamp: Sun 2019-03-10 10:22:32 CDT (28s ago)
  Command Line: /usr/sbin/rtpengine -f --config-file=/etc/rtpengine/rtpengine.conf --config-section=rtpengine --pidfile=/run/rtpengine/rtpengine.pid
    Executable: /usr/sbin/rtpengine
 Control Group: /system.slice/rtpengine.service
          Unit: rtpengine.service
         Slice: system.slice
       Message: Process 31238 (rtpengine) of user 981 dumped core.
                
                Stack trace of thread 31249:
                #0  0x000000000044dbe4 __output_rtp (rtpengine)
                #1  0x000000000044e7f8 packet_dtmf_fwd.constprop.8 (rtpengine)
                #2  0x000000000044e8d2 packet_dtmf (rtpengine)
                #3  0x000000000044e39d __handler_func_sequencer (rtpengine)
                #4  0x0000000000445821 stream_fd_readable (rtpengine)
                #5  0x000000000040ee41 poller_poll (rtpengine)
                #6  0x000000000040f3dd poller_loop (rtpengine)
                #7  0x000000000040f5be thread_detach_func (rtpengine)
                #8  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #9  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31241:
                #0  0x00007fbd8f36e828 __nanosleep (libc.so.6)
                #1  0x00007fbd8f39a598 usleep (libc.so.6)
                #2  0x0000000000451c90 load_thread (rtpengine)
                #3  0x000000000040f5be thread_detach_func (rtpengine)
                #4  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #5  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31238:
                #0  0x00007fbd8f36e828 __nanosleep (libc.so.6)
                #1  0x00007fbd8f39a598 usleep (libc.so.6)
                #2  0x000000000040b2da main (rtpengine)
                #3  0x00007fbd8f2c9413 __libc_start_main (libc.so.6)
                #4  0x000000000040b85e _start (rtpengine)
                
                Stack trace of thread 31239:
                #0  0x00007fbd8f2de30c __sigtimedwait (libc.so.6)
                #1  0x000000000040ba7d sighandler (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31240:
                #0  0x00007fbd8f36e828 __nanosleep (libc.so.6)
                #1  0x00007fbd8f39a598 usleep (libc.so.6)
                #2  0x000000000040f3aa poller_timer_loop (rtpengine)
                #3  0x000000000040f5be thread_detach_func (rtpengine)
                #4  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #5  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31245:
                #0  0x00007fbd8f3a29d7 epoll_wait (libc.so.6)
                #1  0x000000000040edca poller_poll (rtpengine)
                #2  0x000000000040f3dd poller_loop (rtpengine)
                #3  0x000000000040f5be thread_detach_func (rtpengine)
                #4  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #5  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31262:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31261:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31273:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31247:
                #0  0x00007fbd8f3a29d7 epoll_wait (libc.so.6)
                #1  0x000000000040edca poller_poll (rtpengine)
                #2  0x000000000040f3dd poller_loop (rtpengine)
                #3  0x000000000040f5be thread_detach_func (rtpengine)
                #4  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #5  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31266:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31246:
                #0  0x00007fbd8f3a29d7 epoll_wait (libc.so.6)
                #1  0x000000000040edca poller_poll (rtpengine)
                #2  0x000000000040f3dd poller_loop (rtpengine)
                #3  0x000000000040f5be thread_detach_func (rtpengine)
                #4  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #5  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31257:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31271:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31260:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31264:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31254:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31248:
                #0  0x00007fbd8f3a29d7 epoll_wait (libc.so.6)
                #1  0x000000000040edca poller_poll (rtpengine)
                #2  0x000000000040f3dd poller_loop (rtpengine)
                #3  0x000000000040f5be thread_detach_func (rtpengine)
                #4  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #5  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31274:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31243:
                #0  0x00007fbd8f3a29d7 epoll_wait (libc.so.6)
                #1  0x000000000040edca poller_poll (rtpengine)
                #2  0x000000000040f3dd poller_loop (rtpengine)
                #3  0x000000000040f5be thread_detach_func (rtpengine)
                #4  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #5  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31259:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31270:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31250:
                #0  0x00007fbd8f3a29d7 epoll_wait (libc.so.6)
                #1  0x000000000040edca poller_poll (rtpengine)
                #2  0x000000000040f3dd poller_loop (rtpengine)
                #3  0x000000000040f5be thread_detach_func (rtpengine)
                #4  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #5  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31268:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31265:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31258:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31275:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31272:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31251:
                #0  0x00007fbd8f3a29d7 epoll_wait (libc.so.6)
                #1  0x000000000040edca poller_poll (rtpengine)
                #2  0x000000000040f3dd poller_loop (rtpengine)
                #3  0x000000000040f5be thread_detach_func (rtpengine)
                #4  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #5  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31256:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31269:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31244:
                #0  0x00007fbd8f3a29d7 epoll_wait (libc.so.6)
                #1  0x000000000040edca poller_poll (rtpengine)
                #2  0x000000000040f3dd poller_loop (rtpengine)
                #3  0x000000000040f5be thread_detach_func (rtpengine)
                #4  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #5  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31263:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31267:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31253:
                #0  0x00007fbd8f3a29d7 epoll_wait (libc.so.6)
                #1  0x000000000040edca poller_poll (rtpengine)
                #2  0x000000000040f3dd poller_loop (rtpengine)
                #3  0x000000000040f5be thread_detach_func (rtpengine)
                #4  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #5  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31252:
                #0  0x00007fbd8f3a29d7 epoll_wait (libc.so.6)
                #1  0x000000000040edca poller_poll (rtpengine)
                #2  0x000000000040f3dd poller_loop (rtpengine)
                #3  0x000000000040f5be thread_detach_func (rtpengine)
                #4  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #5  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31242:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
                
                Stack trace of thread 31255:
                #0  0x00007fbd8f520a8a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00000000004522a0 timerthread_run (rtpengine)
                #2  0x000000000040f5be thread_detach_func (rtpengine)
                #3  0x00007fbd8f51a58e start_thread (libpthread.so.0)
                #4  0x00007fbd8f3a26a3 __clone (libc.so.6)
```
```
Program terminated with signal SIGFPE, Arithmetic exception.
#0  __output_rtp (mp=mp@entry=0x7fbd6e7f8b18, ch=ch@entry=0x7fbd3000de40, handler=0x7fbd30012690, buf=buf@entry=0x7fbd5c005a80 "\200e\036\353\060\225\340\fr;V\375\005\n\001@", payload_len=<optimized out>, payload_ts=815128588, marker=0, seq=7915, 
    seq_inc=-1) at ../lib/auxlib.h:236
236             timeval_from_us(tv, timeval_us(tv) + usec);
[Current thread is 1 (Thread 0x7fbd6e7fc700 (LWP 31249))]
(gdb) bt full
#0  __output_rtp (mp=mp@entry=0x7fbd6e7f8b18, ch=ch@entry=0x7fbd3000de40, handler=0x7fbd30012690, buf=buf@entry=0x7fbd5c005a80 "\200e\036\353\060\225\340\fr;V\375\005\n\001@", payload_len=<optimized out>, payload_ts=815128588, marker=0, seq=7915, 
    seq_inc=-1) at ../lib/auxlib.h:236
        ts_diff = 0
        ts_diff_us = <error reading variable ts_diff_us (Division by zero)>
        rh = 0x7fbd5c005a80
        ssrc_out = 0x7fbd60002f10
        ssrc_out_p = <optimized out>
        ts = 815128588
        p = 0x7fbd5c003840
#1  0x000000000044e7f8 in packet_dtmf_fwd (ch=ch@entry=0x7fbd3000de40, packet=packet@entry=0x7fbd5c003880, mp=mp@entry=0x7fbd6e7f8b18, seq_inc=0) at codec.c:758
        buf = 0x7fbd5c005a80 "\200e\036\353\060\225\340\fr;V\375\005\n\001@"
#2  0x000000000044e8d2 in packet_dtmf (mp=0x7fbd6e7f8b18, packet=0x7fbd5c003880, ch=0x7fbd3000de40) at codec.c:777
        ret = <optimized out>
        _g_boolean_var_ = <optimized out>
#3  packet_dtmf (ch=0x7fbd3000de40, packet=0x7fbd5c003880, mp=0x7fbd6e7f8b18) at codec.c:764
        ret = <optimized out>
        _g_boolean_var_ = <optimized out>
#4  0x000000000044e39d in __handler_func_sequencer (h=<optimized out>, mp=0x7fbd6e7f8b18, packet=0x7fbd5c003880) at codec.c:673
        ssrc_in = 0x7fbd60002cf0
        ssrc_in_p = 0x7fbd60002ca0
        ssrc_out = <optimized out>
        ssrc_out_p = <optimized out>
        ch = <optimized out>
        seq_next_packet = <optimized out>
        seq_ori = <optimized out>
        seq_ret = 0
#5  0x0000000000445821 in stream_packet (phc=0x7fbd6e7f8ac0) at media_socket.c:1754
        transcoder = <optimized out>
        ret = 0
        stun_ret = <optimized out>
        address_check = <optimized out>
        handler_ret = 0
        ret = <optimized out>
        handler_ret = <optimized out>
        stun_ret = <optimized out>
        address_check = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        __loglevel = <optimized out>
        transcoder = <optimized out>
        _g_boolean_var_ = <optimized out>
        __loglevel = <optimized out>
#6  stream_fd_readable (fd=<optimized out>, p=<optimized out>, u=<optimized out>) at media_socket.c:1869
        phc = {s = {
            s = 0x7fbd6e7f8c50 "\200e\036\353\060\225\340\fr;V\375\005\n\001@\201\316\065\230\347}\205\n\254%\243\017\341\330\064Iŷ\320\367In\303F\275\246\275\067\331\334\322n\274\211,Y\236\306\032\263\255/\213\032\177\251\263\221\315\342\300\303ˍ\375\177\260Z\372\243ގ\n\232\225\213\255\244\324\024\306\323\334t\201\231\376\352\354C/\265މ\004#\346ܐ&\004\331\373&f\033\326\r\326uP\376\341y\274(\235\341\330|_\240\262\223\374T\212\254\370\303cгB7:\320\b[\236\217\"\035D\017\273CJ\270B]va\214\a\234o\325'\025G\002a\005\362\345\354g\222Qf\004\071A`\202", len = 16}, sink = 0x7fbd3001a0c0, decrypt_func = 0x443140 <call_savp2avp_rtp>, encrypt_func = 0x443110 <call_avp2savp_rtp>, rtcp_filter = 0x0, in_srtp = 0x7fbd3001a6c0, 
          out_srtp = 0x7fbd3001a0c0, payload_type = 101, rtcp = 0, update = 0, unkernelize = 0, kernelize = 0, mp = {raw = {
              s = 0x7fbd6e7f8c50 "\200e\036\353\060\225\340\fr;V\375\005\n\001@\201\316\065\230\347}\205\n\254%\243\017\341\330\064Iŷ\320\367In\303F\275\246\275\067\331\334\322n\274\211,Y\236\306\032\263\255/\213\032\177\251\263\221\315\342\300\303ˍ\375\177\260Z\372\243ގ\n\232\225\213\255\244\324\024\306\323\334t\201\231\376\352\354C/\265މ\004#\346ܐ&\004\331\373&f\033\326\r\326uP\376\341y\274(\235\341\330|_\240\262\223\374T\212\254\370\303cгB7:\320\b[\236\217\"\035D\017\273CJ\270B]va\214\a\234o\325'\025G\002a\005\362\345\354g\222Qf\004\071A`\202", len = 16}, fsin = {address = {family = 0x47b820 <__socket_families>, u = {ipv4 = {s_addr = 34210058}, ipv6 = {__in6_u = {__u6_addr8 = "\n\001\n\002", '\000' <repeats 11 times>, __u6_addr16 = {
                        266, 522, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {34210058, 0, 0, 0}}}}}, port = 10365}, tv = {tv_sec = 1552231352, tv_usec = 30160}, sfd = 0x7fbd3000a700, call = 0x7fbd3000c040, stream = 0x7fbd3001a6c0, media = 0x7fbd3000e1e0, 
            rtp = 0x7fbd6e7f8c50, rtcp = 0x0, ssrc_in = 0x7fbd60002cf0, ssrc_out = 0x7fbd60002f10, payload = {
              s = 0x7fbd6e7f8c5c "\005\n\001@\201\316\065\230\347}\205\n\254%\243\017\341\330\064Iŷ\320\367In\303F\275\246\275\067\331\334\322n\274\211,Y\236\306\032\263\255/\213\032\177\251\263\221\315\342\300\303ˍ\375\177\260Z\372\243ގ\n\232\225\213\255\244\324\024\306\323\334t\201\231\376\352\354C/\265މ\004#\346ܐ&\004\331\373&f\033\326\r\326uP\376\341y\274(\235\341\330|_\240\262\223\374T\212\254\370\303cгB7:\320\b[\236\217\"\035D\017\273CJ\270B]va\214\a\234o\325'\025G\002a\005\362\345\354g\222Qf\004\071A`\202", len = 4}, packets_out = {head = 0x0, tail = 0x0, length = 0}, iter = 0}}
        _g_boolean_var_ = <optimized out>
        __loglevel = <optimized out>
        sfd = <optimized out>
        buf = '\000' <repeats 128 times>, "\200e\036\353\060\225\340\fr;V\375\005\n\001@\201\316\065\230\347}\205\n\254%\243\017\341\330\064Iŷ\320\367In\303F\275\246\275\067\331\334\322n\274\211,Y\236\306\032\263\255/\213\032\177\251\263\221\315\342\300\303ˍ\375\177\260Z"...
        ret = <optimized out>
        iters = <optimized out>
        update = 0
        ca = <optimized out>
#7  0x000000000040ee41 in poller_poll (p=0xcfbd10, timeout=<optimized out>) at poller.c:351
        ret = 1
--Type <RET> for more, q to quit, c to continue without paging--c
        i = <optimized out>
        it = 0x7fbd30010b00
        evs = {{events = 1, data = {ptr = 0xc, fd = 12, u32 = 12, u64 = 12}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}} <repeats 91 times>, {events = 1056, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7, fd = 7, u32 = 7, u64 = 7}}, {events = 0, data = {ptr = 0x4000000000, fd = 0, u32 = 0, u64 = 274877906944}}, {events = 0, data = {ptr = 0x7fbd5c000ad8, fd = 1543506648, u32 = 1543506648, u64 = 140451269053144}}, {events = 1055, data = {ptr = 0x45000000000, fd = 0, u32 = 0, u64 = 4741643894784}}, {events = 0, data = {ptr = 0xfffffffffffffcf0, fd = -784, u32 = 4294966512, u64 = 18446744073709550832}}, {events = 16, data = {ptr = 0x4300000000, fd = 0, u32 = 0, u64 = 287762808832}}, {events = 64, data = {ptr = 0x2, fd = 2, u32 = 2, u64 = 2}}, {events = 0, data = {ptr = 0x5d00000000, fd = 0, u32 = 0, u64 = 399431958528}}, {events = 119, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 2209547776, data = {ptr = 0xd90d5bf5, fd = -653435915, u32 = 3641531381, u64 = 3641531381}}, {events = 0, data = {ptr = 0x205, fd = 517, u32 = 517, u64 = 517}}, {events = 1543514624, data = {ptr = 0x20000007fbd, fd = 32701, u32 = 32701, u64 = 2199023288253}}, {events = 0, data = {ptr = 0x7fbd5c0029f0, fd = 1543514608, u32 = 1543514608, u64 = 140451269061104}}, {events = 1543503904, data = {ptr = 0x2a000007fbd, fd = 32701, u32 = 32701, u64 = 2886218055613}}, {events = 0, data = {ptr = 0x7fbd8f32ade5 <_int_memalign+197>, fd = -1892504091, u32 = 2402463205, u64 = 140452128009701}}, {events = 1543510512, data = {ptr = 0x20000007fbd, fd = 32701, u32 = 32701, u64 = 2199023288253}}, {events = 0, data = {ptr = 0x1f0, fd = 496, u32 = 496, u64 = 496}}, {events = 1543503904, data = {ptr = 0x100007fbd, fd = 32701, u32 = 32701, u64 = 4294999997}}, {events = 0, data = {ptr = 0xc775b8, fd = 13071800, u32 = 13071800, u64 = 13071800}}, {events = 1476405056, data = {ptr = 0x8f32bf7a00007fbd, fd = 32701, u32 = 32701, u64 = 10318520226966175677}}, {events = 32701, data = {ptr = 0x7fbd6e7fb430, fd = 1853862960, u32 = 1853862960, u64 = 140451579409456}}, {events = 8, data = {ptr = 0x2000000000, fd = 0, u32 = 0, u64 = 137438953472}}, {events = 0, data = {ptr = 0x7fbd8f32d52c <__posix_memalign+60>, fd = -1892494036, u32 = 2402473260, u64 = 140452128019756}}, {events = 512, data = {ptr = 0x915cdc7700000000, fd = 0, u32 = 0, u64 = 10474489237016150016}}, {events = 32701, data = {ptr = 0x7fbd5c002a00, fd = 1543514624, u32 = 1543514624, u64 = 140451269061120}}, {events = 2209547776, data = {ptr = 0x100d90d5bf5, fd = -653435915, u32 = 3641531381, u64 = 1103153159157}}, {events = 0, data = {ptr = 0x33, fd = 51, u32 = 51, u64 = 51}}, {events = 1543506752, data = {ptr = 0x1800007fbd, fd = 32701, u32 = 32701, u64 = 103079247805}}, {events = 0, data = {ptr = 0x7fbd5c000b20, fd = 1543506720, u32 = 1543506720, u64 = 140451269053216}}, {events = 16, data = {ptr = 0x5800274000000000, fd = 0, u32 = 0, u64 = 6341111431169048576}}, {events = 32701, data = {ptr = 0x7fbd915ce9c0 <g_slice_alloc+1648>, fd = -1856181824, u32 = 2438785472, u64 = 140452164331968}}, {events = 1543506720, data = {ptr = 0x5c002a6000007fbd, fd = 32701, u32 = 32701, u64 = 6629345243294629821}}, {events = 32701, data = {ptr = 0x20, fd = 32, u32 = 32, u64 = 32}}, {events = 51, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7fbd64002a20, fd = 1677732384, u32 = 1677732384, u64 = 140451403278880}}}
        ev = <optimized out>
        e = {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}
#8  0x000000000040f3dd in poller_loop (d=0xcfbd10) at poller.c:508
        p = 0xcfbd10
#9  0x000000000040f5be in thread_detach_func (d=0xcef520) at aux.c:207
        dt = 0xcef520
        t = 0x7fbd58001a20
        scheduler = <optimized out>
#10 0x00007fbd8f51a58e in start_thread (arg=<optimized out>) at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140451579414272, 7644863839561058267, 140730166349582, 140730166349583, 140730166349760, 140451579409920, -7682331899766503461, -7682264055937103909}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#11 0x00007fbd8f3a26a3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```

**Comment by rfuchs** [comment]
Hm I seem unable to reproduce this. Can you share some more details about the call scenario here? What codecs in/out, transcoding to/from what? The full debug log would be ideal.

**Comment by amessina** [comment]
Debug attached.
[rtpengine.dtmf.log](https://github.com/sipwise/rtpengine/files/2956711/rtpengine.dtmf.log)

**Comment by amessina** [comment]
Thank you for the super-quick fix @rfuchs.
