### ISSUE TITLE
Segfault in rtpengine 3.3.0.0 mr 3.8.0 git-master-98e0b6d

### ISSUE THREAD

**Issue by uloyulocas** [sipwise/rtpengine#78]
Hello. 
Unfortunately I got segfault after "offer":

kernel: [23795.722200] rtpengine[12334]: segfault at 0 ip 000000000041d1ca sp 00007f846efec1a0 error 4 in rtpengine[400000+3e000]

From syslog:

Mar  2 16:17:22 voip rtpengine[12327]: [6b693c98-470a-2b04-67ed-1c934da818c4] Received command 'offer' from 127.0.0.1:57800
Mar  2 16:17:22 voip rtpengine[12327]: [6b693c98-470a-2b04-67ed-1c934da818c4] Dump for 'offer' from 127.0.0.1:57800: { "sdp": "v=0#015#012o=- 3602363925848254500 2 IN IP4 127.0.0.1#015#012s=Doubango Telecom - chrome#015#012t=0 0#015#012a=group:BUNDLE audio#015#012a=msid-semantic: WMS hdqPxqpz1GMF2IIH8pPdesJRoPf0viNQJPOc#015#012m=audio 52363 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126#015#012c=IN IP4 212.90.61.96#015#012a=rtcp:52363 IN IP4 212.90.61.96#015#012a=candidate:1371579674 1 udp 2122194687 172.17.1.8 52363 typ host generation 0#015#012a=candidate:1371579674 2 udp 2122194687 172.17.1.8 52363 typ host generation 0#015#012a= ...
Mar  2 16:17:22 voip rtpengine[12327]: [6b693c98-470a-2b04-67ed-1c934da818c4] ... candidate:3001099254 1 udp 1685987071 212.90.61.96 52363 typ srflx raddr 172.17.1.8 rport 52363 generation 0#015#012a=candidate:3001099254 2 udp 1685987071 212.90.61.96 52363 typ srflx raddr 172.17.1.8 rport 52363 generation 0#015#012a=candidate:524507626 1 tcp 1518214911 172.17.1.8 0 typ host tcptype active generation 0#015#012a=candidate:524507626 2 tcp 1518214911 172.17.1.8 0 typ host tcptype active generation 0#015#012a=ice-ufrag:t5eBa2lbpWcBzrHc#015#012a=ice-pwd:3/3GFlC79G+SifgavftzABQK#015#012a=ice-options:google-ice#015#012a=fing ...
Mar  2 16:17:22 voip rtpengine[12327]: [6b693c98-470a-2b04-67ed-1c934da818c4] ... erprint:sha-256 FF:53:88:A5:58:B2:D7:D3:41:C7:76:69:E6:BF:E6:3C:75:D7:63:3D:9B:4E:D3:23:CE:FA:05:20:F9:06:83:FD#015#012a=setup:actpass#015#012a=mid:audio#015#012a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level#015#012a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time#015#012a=sendrecv#015#012a=rtcp-mux#015#012a=rtpmap:111 opus/48000/2#015#012a=fmtp:111 minptime=10#015#012a=rtpmap:103 ISAC/16000#015#012a=rtpmap:104 ISAC/32000#015#012a=rtpmap:9 G722/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:106 CN/32000#015#012a=rtpmap:105 CN/ ...
Mar  2 16:17:22 voip rtpengine[12327]: [6b693c98-470a-2b04-67ed-1c934da818c4] ... 16000#015#012a=rtpmap:13 CN/8000#015#012a=rtpmap:126 telephone-event/8000#015#012a=maxptime:60#015#012a=ssrc:364782800 cname:BT3Wb9bmRZsIgs6Z#015#012a=ssrc:364782800 msid:hdqPxqpz1GMF2IIH8pPdesJRoPf0viNQJPOc 0cead8a9-56f6-4529-8dc6-fd41e0957703#015#012a=ssrc:364782800 mslabel:hdqPxqpz1GMF2IIH8pPdesJRoPf0viNQJPOc#015#012a=ssrc:364782800 label:0cead8a9-56f6-4529-8dc6-fd41e0957703#015#012", "ICE": "remove", "flags": [ "trust-address", "asymmetric" ], "replace": [ "origin", "session-connection" ], "transport-protocol": "RTP/SAVPF", "call-id": "6b ...
Mar  2 16:17:22 voip rtpengine[12327]: [6b693c98-470a-2b04-67ed-1c934da818c4] ... 693c98-470a-2b04-67ed-1c934da818c4", "received-from": [ "IP4", "10.0.1.1" ], "from-tag": "dxuy6gkwxPtrzJlcnWhr", "command": "offer" }
Mar  2 16:17:22 voip kernel: [23795.722200] rtpengine[12334]: segfault at 0 ip 000000000041d1ca sp 00007f846efec1a0 error 4 in rtpengine[400000+3e000]
Mar  2 16:17:23 voip /usr/local/sbin/kamailio[12092]: ERROR: rtpengine [rtpengine.c:1630]: send_rtpp_command(): can't send command to a RTP proxy
Mar  2 16:17:23 voip /usr/local/sbin/kamailio[12092]: ERROR: rtpengine [rtpengine.c:1666]: send_rtpp_command(): proxy <udp:127.0.0.1:7722> does not respond, disable it
Mar  2 16:17:23 voip /usr/local/sbin/kamailio[12092]: ERROR: rtpengine [rtpengine.c:1442]: rtpp_function_call(): no available proxies

From gdb:

Reading symbols from /usr/lib/debug/usr/sbin/rtpengine...done.

warning: core file may not match specified executable file.
[New LWP 10200]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/sbin/kamailio -f /usr/local/etc/kamailio/kamailio.cfg -P /var/run/ka'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fc451c7056a in __strcpy_sse2 () at ../sysdeps/x86_64/multiarch/../strcpy.S:49
49      ../sysdeps/x86_64/multiarch/../strcpy.S: No such file or directory.
(gdb) thread apply all bt

Thread 1 (Thread 0x7fc4525e1740 (LWP 10200)):
#0  0x00007fc451c7056a in __strcpy_sse2 () at ../sysdeps/x86_64/multiarch/../strcpy.S:49
#1  0x00007fc44f24330f in uac_init () at uac.c:121
#2  0x00007fc44f1efe48 in mod_init () at tm.c:862
#3  0x000000000059648a in ?? ()
#4  0x0000000001628010 in ?? ()
#5  0x0000000001628010 in ?? ()
#6  0x00000000016282c0 in ?? ()
#7  0x0000000000000000 in ?? ()

Version of kamailio is 4.2.3

Daemon start argumets are:

/usr/sbin/rtpengine --interface=internal/private_ip --interface=external/public_ip --listen-ng=127.0.0.1:7722 --timeout=60 --silent-timeout=3600 --pidfile=/var/run/ngcp-rtpengine-daemon.pid --tos=184 --port-min=10000 --port-max=30000 --table=0 --log-level=7 --log-facility=daemon

--dtls-passive - does not affected.

**Comment by uloyulocas** [comment]
Thank you.
