### ISSUE TITLE
Coredump when transcoding between G729 and PCMA

### ISSUE THREAD

**Issue by SipSeb** [sipwise/rtpengine#941]
We just enabled transcoding between G729 and PCMA, and within minutes multiple machines crashed.

This is the coredump, it looks basically the same on all machines.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000555afa475d42 in packet_dtmf_fwd (ch=ch@entry=0x7f5400261da0, packet=packet@entry=0x7f54003b8e30, mp=mp@entry=0x7f5423ffb6f8, seq_inc=0) at codec.c:949
949	codec.c: No such file or directory.
[Current thread is 1 (Thread 0x7f5423fff700 (LWP 1041))]
(gdb) bt
#0  0x0000555afa475d42 in packet_dtmf_fwd (ch=ch@entry=0x7f5400261da0, packet=packet@entry=0x7f54003b8e30, mp=mp@entry=0x7f5423ffb6f8, seq_inc=0) at codec.c:949
#1  0x0000555afa475f22 in packet_dtmf (mp=0x7f5423ffb6f8, packet=0x7f54003b8e30, ch=0x7f5400261da0) at codec.c:997
#2  packet_dtmf (ch=0x7f5400261da0, packet=0x7f54003b8e30, mp=0x7f5423ffb6f8) at codec.c:984
#3  0x0000555afa4753d2 in __handler_func_sequencer (mp=0x7f5423ffb6f8, packet=0x7f54003b8e30) at codec.c:823
#4  0x0000555afa46c2a1 in stream_packet (phc=0x7f5423ffb6a0) at media_socket.c:1779
#5  stream_fd_readable (fd=<optimized out>, p=0x7f541096c420, u=<optimized out>) at media_socket.c:1892
#6  0x0000555afa437393 in poller_poll (p=0x555afb23a9f0, timeout=<optimized out>) at poller.c:351
#7  0x0000555afa43780d in poller_loop (d=0x555afb23a9f0) at poller.c:508
#8  0x0000555afa437922 in thread_detach_func (d=0x555afb2398e0) at aux.c:207
#9  0x00007f5447b0cfa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#10 0x00007f5447a3d4cf in clone () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) frame 0
#0  0x0000555afa475d42 in packet_dtmf_fwd (ch=ch@entry=0x7f5400261da0, packet=packet@entry=0x7f54003b8e30, mp=mp@entry=0x7f5423ffb6f8, seq_inc=0) at codec.c:949
949	in codec.c
(gdb) p *ch
$1 = {h = {obj = {ref = 3, free_func = 0x555afa474890 <__free_ssrc_handler>, size = 272}, lock = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0,
        __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, ssrc = 90614332, last_used = 1582557013}, handler = 0x7f541890c740, decoder = 0x7f5400209020,
  encoder = 0x7f54280b66b0, encoder_format = {clockrate = 8000, channels = 1, format = 1}, bitrate = 0, ptime = 20, bytes_per_packet = 160, first_ts = 0, ts_in = 0, first_send = {tv_sec = 0,
    tv_usec = 0}, first_send_ts = 0, sample_buffer = 0x7f53c6312640, dtmf_dsp = 0x7f54108a3f80, dtmf_resampler = {swresample = 0x0}, dtmf_format = {clockrate = 8000, channels = 1, format = 1},
  dtmf_ts = 1863336944, last_dtmf_event_ts = 0, dtmf_events = {head = 0x0, tail = 0x0, length = 0}, dtmf_event = {code = 0, volume = 0, ts = 0}, rtp_mark = 0}
(gdb) p *packet
$2 = {p = {seq = 43897}, ts = 1863336944, payload = 0x7f54085dc760, handler = 0x7f541890c740, marker = -1, ignore_seq = 0, func = 0x555afa475e90 <packet_dtmf>,
  dup_func = 0x555afa475f30 <packet_dtmf_dup>, rtp = {v_p_x_cc = 128 '\200', m_pt = 229 '\345', seq_num = 31147, timestamp = 4030926959, ssrc = 1017800197, csrc = 0x7f54003b8e74}}
(gdb) p *mp
$3 = {raw = {s = 0x7f5423ffb820 "\200\345\253yo\020C\360\005f\252<6\f", len = 16}, fsin = {address = {family = 0x555afa4a5860 <__socket_families>, u = {ipv4 = {s_addr = 760023769}, ipv6 = {__in6_u = {
            __u6_addr8 = "\331\nM-", '\000' <repeats 11 times>, __u6_addr16 = {2777, 11597, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {760023769, 0, 0, 0}}}}}, port = 21046}, tv = {tv_sec = 1582557013,
    tv_usec = 988176}, sfd = 0x7f541096c420, call = 0x7f54185a65c0, stream = 0x7f5418f57bf0, media = 0x7f54182cbd80, rtp = 0x7f54003b8e68, rtcp = 0x0, ssrc_in = 0x7f54103cb850,
  ssrc_out = 0x7f53f8c69270, payload = {s = 0x7f5423ffb82c "6\f", len = 4}, packets_out = {head = 0x0, tail = 0x0, length = 0}}
```

The version we used on these machines is: `7.5.2.2+0~mr7.5.2.2`

**Comment by SipSeb** [comment]
After digging more into the logs and traces, it looks like it does not have to do anything specifically with G729. We enabled transcoding about an hour before the first crash, and we called rtpengine with one of these option lines:

- `trust-address ICE=remove via-branch=extra codec-mask-G729a codec-mask-G729 codec-transcode-PCMA`
- trust-address ICE=remove via-branch=extra codec-transcode-G729`

**Comment by rfuchs** [comment]
What's the exact commit you're on?

**Comment by SipSeb** [comment]
We are using the debian packages from sipwise. So it's the release version 7.5.2.2.

**Comment by rfuchs** [comment]
Ok, then that's already fixed in 4789336 but I just noticed another issue with that patch that I'll push a fix for now.

**Comment by SipSeb** [comment]
Thanks. Can you explain shortly, what causes this error? Does one side speak a codec which rtpengine can't encode? We only have encoding for G729 turned on, and from the build and runtime dependencies, the appropriate library should be included for de- and encoding from and to this codec. 

Can you already say, when a release including this bugfix will be available?

**Comment by rfuchs** [comment]
It can happen when there's a codec change during a running call, for example through a re-invite, and the codec in use changes from transcoding to non transcoding.

**Comment by rfuchs** [comment]
Cleaning up old tickets
