### ISSUE TITLE
Daemon segfault

### ISSUE THREAD

**Issue by krieger-od** [sipwise/rtpengine#95]
rtpengine is built from today's git master HEAD 3a45a169ef261f9ad8c7516b365983ac79feca2c.

Result of ``` echo -en "bt\n info threads\n thread apply all bt\n thread apply all bt full\n" | gdb ./rtpengine core > /tmp/rtpengine.gdb_out```:
```
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./rtpengine...done.
[New LWP 18865]
[New LWP 18861]
[New LWP 18866]
[New LWP 18862]
[New LWP 18863]
[New LWP 18864]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/rtpengine --table=0 --interface=172.31.4.102!54.93.84.92 --liste'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f9015f0e1ad in __memcmp_sse2 () at ../sysdeps/x86_64/multiarch/../memcmp.S:200
(gdb) #0  0x00007f9015f0e1ad in __memcmp_sse2 () at ../sysdeps/x86_64/multiarch/../memcmp.S:200
#1  0x00007f9017551cca in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f90175529a1 in g_hash_table_remove_all () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f9017552a0e in g_hash_table_destroy () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x0000000000437e91 in __ice_agent_free_components (ag=0x7f9000026c90) at ice.c:477
#5  0x0000000000437688 in __ice_reset (ag=0x7f9000026c90) at ice.c:287
#6  0x000000000043776c in __ice_restart (ag=0x7f9000026c90) at ice.c:301
#7  0x000000000043787e in ice_update (ag=0x7f9000026c90, sp=0x7f9000014010) at ice.c:333
#8  0x000000000041a2fa in monologue_offer_answer (other_ml=0x7f9008063680, streams=0x7f900fedc2f0, flags=0x7f900fedc310)
    at call.c:2557
#9  0x000000000042e995 in call_offer_answer_ng (input=0x7f900003c8d8, m=0x24e9c00, output=0x7f900003c878, opmode=OP_ANSWER, 
    addr=0x0, sin=0x0) at call_interfaces.c:665
#10 0x000000000042eb60 in call_answer_ng (input=0x7f900003c8d8, m=0x24e9c00, output=0x7f900003c878) at call_interfaces.c:698
#11 0x0000000000420d6b in control_ng_incoming (obj=0x24ec030, buf=0x7f900fedc5a0, sin=0x7f900fedc5b0, 
    addr=0x7f900fedc5d0 "127.0.0.1:42871") at control_ng.c:145
#12 0x000000000041fd5f in udp_listener_incoming (fd=6, p=0x24e86a0, x=0) at udp_listener.c:52
#13 0x00000000004101ae in poller_poll (p=0x24e6d60, timeout=100) at poller.c:348
#14 0x0000000000410764 in poller_loop (d=0x24e6d60) at poller.c:502
#15 0x0000000000410c30 in thread_detach_func (d=0x24e8a50) at aux.c:143
#16 0x00007f901624f182 in start_thread (arg=0x7f900feed700) at pthread_create.c:312
#17 0x00007f9015f7c00d in __qfcvt_r (value=0, ndigit=0, decpt=0x7f900feed9c0, sign=0x0, buf=0x0, len=0) at efgcvt_r.c:100
#18 0x0000000000000000 in ?? ()
(gdb)   Id   Target Id         Frame 
  6    Thread 0x7f90106ee700 (LWP 18864) pthread_rwlock_rdlock ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_rdlock.S:87
  5    Thread 0x7f9010eef700 (LWP 18863) 0x00007f9015f42acd in __libc_wait (stat_loc=0x0) at ../sysdeps/unix/sysv/linux/wait.c:28
  4    Thread 0x7f90116f0700 (LWP 18862) 0x00007f9015eb8d90 in __GI___libc_sigaction (sig=292486160, act=0x0, oact=0x0)
    at ../sysdeps/unix/sysv/linux/x86_64/sigaction.c:56
  3    Thread 0x7f900f6ec700 (LWP 18866) 0x00007f9015f7c6a3 in __GI_epoll_pwait (epfd=5, events=0x7f900f6eb670, maxevents=128, 
    timeout=-1, set=0x0) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:48
  2    Thread 0x7f9017f22980 (LWP 18861) 0x00007f9015f42acd in __libc_wait (stat_loc=0x0) at ../sysdeps/unix/sysv/linux/wait.c:28
* 1    Thread 0x7f900feed700 (LWP 18865) 0x00007f9015f0e1ad in __memcmp_sse2 () at ../sysdeps/x86_64/multiarch/../memcmp.S:200
(gdb) 
Thread 6 (Thread 0x7f90106ee700 (LWP 18864)):
#0  pthread_rwlock_rdlock () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_rdlock.S:87
#1  0x000000000043a4ef in ice_thread_run (p=0x0) at ice.c:1309
#2  0x0000000000410c30 in thread_detach_func (d=0x24e8a40) at aux.c:143
#3  0x00007f901624f182 in start_thread (arg=0x7f90106ee700) at pthread_create.c:312
#4  0x00007f9015f7c00d in __qfcvt_r (value=0, ndigit=0, decpt=0x7f90106ee9c0, sign=0x0, buf=0x0, len=0) at efgcvt_r.c:100
#5  0x0000000000000000 in ?? ()

Thread 5 (Thread 0x7f9010eef700 (LWP 18863)):
#0  0x00007f9015f42acd in __libc_wait (stat_loc=0x0) at ../sysdeps/unix/sysv/linux/wait.c:28
#1  0x00007f9015f74034 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000000000000000 in ?? ()

Thread 4 (Thread 0x7f90116f0700 (LWP 18862)):
#0  0x00007f9015eb8d90 in __GI___libc_sigaction (sig=292486160, act=0x0, oact=0x0)
    at ../sysdeps/unix/sysv/linux/x86_64/sigaction.c:56
#1  0x0000000000000000 in ?? ()

Thread 3 (Thread 0x7f900f6ec700 (LWP 18866)):
#0  0x00007f9015f7c6a3 in __GI_epoll_pwait (epfd=5, events=0x7f900f6eb670, maxevents=128, timeout=-1, set=0x0)
    at ../sysdeps/unix/sysv/linux/epoll_pwait.c:48
#1  0x00007f90080074c0 in ?? ()
#2  0x0000000000000000 in ?? ()

Thread 2 (Thread 0x7f9017f22980 (LWP 18861)):
#0  0x00007f9015f42acd in __libc_wait (stat_loc=0x0) at ../sysdeps/unix/sysv/linux/wait.c:28
#1  0x00007f9015f74034 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7f900feed700 (LWP 18865)):
#0  0x00007f9015f0e1ad in __memcmp_sse2 () at ../sysdeps/x86_64/multiarch/../memcmp.S:200
#1  0x00007f9017551cca in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f90175529a1 in g_hash_table_remove_all () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f9017552a0e in g_hash_table_destroy () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x0000000000437e91 in __ice_agent_free_components (ag=0x7f9000026c90) at ice.c:477
#5  0x0000000000437688 in __ice_reset (ag=0x7f9000026c90) at ice.c:287
#6  0x000000000043776c in __ice_restart (ag=0x7f9000026c90) at ice.c:301
#7  0x000000000043787e in ice_update (ag=0x7f9000026c90, sp=0x7f9000014010) at ice.c:333
#8  0x000000000041a2fa in monologue_offer_answer (other_ml=0x7f9008063680, streams=0x7f900fedc2f0, flags=0x7f900fedc310)
    at call.c:2557
#9  0x000000000042e995 in call_offer_answer_ng (input=0x7f900003c8d8, m=0x24e9c00, output=0x7f900003c878, opmode=OP_ANSWER, 
    addr=0x0, sin=0x0) at call_interfaces.c:665
#10 0x000000000042eb60 in call_answer_ng (input=0x7f900003c8d8, m=0x24e9c00, output=0x7f900003c878) at call_interfaces.c:698
#11 0x0000000000420d6b in control_ng_incoming (obj=0x24ec030, buf=0x7f900fedc5a0, sin=0x7f900fedc5b0, 
    addr=0x7f900fedc5d0 "127.0.0.1:42871") at control_ng.c:145
#12 0x000000000041fd5f in udp_listener_incoming (fd=6, p=0x24e86a0, x=0) at udp_listener.c:52
#13 0x00000000004101ae in poller_poll (p=0x24e6d60, timeout=100) at poller.c:348
#14 0x0000000000410764 in poller_loop (d=0x24e6d60) at poller.c:502
#15 0x0000000000410c30 in thread_detach_func (d=0x24e8a50) at aux.c:143
#16 0x00007f901624f182 in start_thread (arg=0x7f900feed700) at pthread_create.c:312
#17 0x00007f9015f7c00d in __qfcvt_r (value=0, ndigit=0, decpt=0x7f900feed9c0, sign=0x0, buf=0x0, len=0) at efgcvt_r.c:100
#18 0x0000000000000000 in ?? ()
(gdb) 
Thread 6 (Thread 0x7f90106ee700 (LWP 18864)):
#0  pthread_rwlock_rdlock () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_rdlock.S:87
No locals.
#1  0x000000000043a4ef in ice_thread_run (p=0x0) at ice.c:1309
        ag = 0x7f9000026c90
        call = 0x7f90000686c0
        sleeptime = 100000
        tv = {tv_sec = 1428074021, tv_usec = 914222}
#2  0x0000000000410c30 in thread_detach_func (d=0x24e8a40) at aux.c:143
        dt = 0x24e8a40
        t = 0x7f90000014a0
#3  0x00007f901624f182 in start_thread (arg=0x7f90106ee700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f90106ee700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140256727721728, -2640881265775207578, 0, 0, 140256727722432, 140256727721728, 
                2628295301097331558, 2628299202121571174}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {
              prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#4  0x00007f9015f7c00d in __qfcvt_r (value=0, ndigit=0, decpt=0x7f90106ee9c0, sign=0x0, buf=0x0, len=0) at efgcvt_r.c:100
        n = <optimized out>
        i = <optimized out>
        left = 275703552
#5  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 5 (Thread 0x7f9010eef700 (LWP 18863)):
#0  0x00007f9015f42acd in __libc_wait (stat_loc=0x0) at ../sysdeps/unix/sysv/linux/wait.c:28
        oldtype = 97685999
#1  0x00007f9015f74034 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 4 (Thread 0x7f90116f0700 (LWP 18862)):
#0  0x00007f9015eb8d90 in __GI___libc_sigaction (sig=292486160, act=0x0, oact=0x0)
    at ../sysdeps/unix/sysv/linux/x86_64/sigaction.c:56
        result = <optimized out>
        kact = {k_sa_handler = 0x7f9017f33000, sa_flags = 16, sa_restorer = 0x40, sa_mask = {__val = {140256744504112, 2, 
              399431958536, 0, 0, 511101108334, 0, 140256744504111, 1, 6599200, 0, 140256819776864, 140256744504336, 
              140256744504320, 140256744504480, 140256851768663}}}
        koact = {k_sa_handler = 0x0, sa_flags = 140256384915952, sa_restorer = 0x7f9015e90920, sa_mask = {__val = {140256744507136, 
              140256744504480, 0, 140256851797269, 140256744504336, 11, 140256744504320, 0, 140256744504336, 0, 16, 140256744507136, 
              140256744504480, 4230717, 32, 0}}}
#1  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 3 (Thread 0x7f900f6ec700 (LWP 18866)):
#0  0x00007f9015f7c6a3 in __GI_epoll_pwait (epfd=5, events=0x7f900f6eb670, maxevents=128, timeout=-1, set=0x0)
    at ../sysdeps/unix/sysv/linux/epoll_pwait.c:48
        _a5 = 0
        _a2 = 140256710932080
        _a6 = 140256586594416
        _a3 = 128
        _a4 = 100
        _a1 = 5
        resultvar = 140256710933616
        oldtype = 258918144
#1  0x00007f90080074c0 in ?? ()
No symbol table info available.
#2  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 2 (Thread 0x7f9017f22980 (LWP 18861)):
#0  0x00007f9015f42acd in __libc_wait (stat_loc=0x0) at ../sysdeps/unix/sysv/linux/wait.c:28
        oldtype = 0
#1  0x00007f9015f74034 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (Thread 0x7f900feed700 (LWP 18865)):
#0  0x00007f9015f0e1ad in __memcmp_sse2 () at ../sysdeps/x86_64/multiarch/../memcmp.S:200
No locals.
#1  0x00007f9017551cca in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f90175529a1 in g_hash_table_remove_all () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f9017552a0e in g_hash_table_destroy () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x0000000000437e91 in __ice_agent_free_components (ag=0x7f9000026c90) at ice.c:477
No locals.
#5  0x0000000000437688 in __ice_reset (ag=0x7f9000026c90) at ice.c:287
No locals.
#6  0x000000000043776c in __ice_restart (ag=0x7f9000026c90) at ice.c:301
No locals.
#7  0x000000000043787e in ice_update (ag=0x7f9000026c90, sp=0x7f9000014010) at ice.c:333
        l = 0x200000040
        k = 0x7f9000014010
        cand = 0x0
        dup = 0x7f90000157e0
        media = 0x7f9000015930
        call = 0x7f90000686c0
        recalc = 0
        comps = 0
        components = {0x7f900000a300, 0x7f900000a130}
        ps = 0x7f900000a6a0
        candidates = 0x7f9000015930
#8  0x000000000041a2fa in monologue_offer_answer (other_ml=0x7f9008063680, streams=0x7f900fedc2f0, flags=0x7f900fedc310)
    at call.c:2557
        sp = 0x7f9000014010
        media_iter = 0x7f8ff80016c0
        ml_media = 0x7f9000005620
        other_ml_media = 0x7f9008005560
        media = 0x7f90000157e0
        other_media = 0x7f9000015930
        num_ports = 2
        monologue = 0x7f9008063600
        em = 0x7f9000090080
        call = 0x7f90000686c0
#9  0x000000000042e995 in call_offer_answer_ng (input=0x7f900003c8d8, m=0x24e9c00, output=0x7f900003c878, opmode=OP_ANSWER, 
    addr=0x0, sin=0x0) at call_interfaces.c:665
        sdp = {
          s = 0x7f900fedc624 "v=0\r\no=- 5427046385408022074 3 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS C1yO3MBdwjtpVn2vBECEbjs25npSFvQuwwUh\r\nm=audio 46656 RTP/SAVPF 124 0 8 101\r\nc=IN IP4 192.168.10.160\r\na=rtcp:56212 IN IP"..., len = 1638}
        fromtag = {s = 0x7f900fedcd48 "K4O~1wW326:to-tag10:cvjgbp7n6g7:command6:answere", len = 9}
        totag = {s = 0x7f900fedcd5c "cvjgbp7n6g7:command6:answere", len = 10}
        callid = {
          s = 0x7f900fedcd0a "1WIp53JB2F13:received-froml3:IP414:89.209.124.148e8:from-tag9:K4O~1wW326:to-tag10:cvjgbp7n6g7:command6:answere", len = 10}
        errstr = 0x440425 "Invalid dialogue association"
        parsed = {head = 0x7f9000025c60, tail = 0x7f9000025c60, length = 1}
        streams = {head = 0x7f8ff80016c0, tail = 0x7f900001bfa0, length = 2}
        call = 0x7f90000686c0
        monologue = 0x7f9008063680
        ret = 32656
        flags = {opmode = OP_ANSWER, received_from_family = {
            s = 0x7f900fedcd27 "IP414:89.209.124.148e8:from-tag9:K4O~1wW326:to-tag10:cvjgbp7n6g7:command6:answere", len = 3}, 
          received_from_address = {s = 0x7f900fedcd2d "89.209.124.148e8:from-tag9:K4O~1wW326:to-tag10:cvjgbp7n6g7:command6:answere", 
            len = 14}, media_address = {s = 0x0, len = 0}, transport_protocol_str = {
            s = 0x7f900fedccf6 "RTP/AVPF7:call-id10:1WIp53JB2F13:received-froml3:IP414:89.209.124.148e8:from-tag9:K4O~1wW326:to-tag10:cvjgbp7n6g7:command6:answere", len = 8}, address_family_str = {s = 0x0, len = 0}, 
          transport_protocol = 0x43c350 <transport_protocols+48>, parsed_received_from = {__in6_u = {
              __u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, 
          parsed_media_address = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, 
              __u6_addr32 = {0, 0, 0, 0}}}, direction = {{s = 0x0, len = 0}, {s = 0x0, len = 0}}, address_family = 0, tos = 256, 
          asymmetric = 0, trust_address = -1, replace_origin = -1, replace_sess_conn = -1, ice_remove = -1, ice_force = 0, 
          ice_force_relay = 0, rtcp_mux_offer = 0, rtcp_mux_demux = 0, rtcp_mux_accept = 0, rtcp_mux_reject = 0, strict_source = 0, 
          media_handover = 0, dtls_passive = -1}
        chopper = 0x7f9000019780
#10 0x000000000042eb60 in call_answer_ng (input=0x7f900003c8d8, m=0x24e9c00, output=0x7f900003c878) at call_interfaces.c:698
No locals.
#11 0x0000000000420d6b in control_ng_incoming (obj=0x24ec030, buf=0x7f900fedc5a0, sin=0x7f900fedc5b0, 
    addr=0x7f900fedc5d0 "127.0.0.1:42871") at control_ng.c:145
        c = 0x24ec030
        bencbuf = {pieces = 0x7f900003e250, free_list = 0x7f900003e2e0, error = 0}
        dict = 0x7f900003c8d8
        resp = 0x7f900003c878
        cmd = {s = 0x7f900fedcd71 "answere", len = 6}
        cookie = {s = 0x7f900fedc610 "19066_13", len = 8}
        data = {
          s = 0x7f900fedc619 "d3:sdp1638:v=0\r\no=- 5427046385408022074 3 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS C1yO3MBdwjtpVn2vBECEbjs25npSFvQuwwUh\r\nm=audio 46656 RTP/SAVPF 124 0 8 101\r\nc=IN IP4 192.168.10.160\r\na=rtcp:"..., len = 1887}
        reply = {s = 0x7f9000027678 "\001", len = 64}
        to_send = 0x0
        callid = {
          s = 0x7f900fedcd0a "1WIp53JB2F13:received-froml3:IP414:89.209.124.148e8:from-tag9:K4O~1wW326:to-tag10:cvjgbp7n6g7:command6:answere", len = 10}
        errstr = 0x0
        mh = {msg_name = 0x7f900fedc5b0, msg_namelen = 267240921, msg_iov = 0x7f900fedc560, msg_iovlen = 4324106, msg_control = 0x0, 
          msg_controllen = 64, msg_flags = 267240880}
        iov = {{iov_base = 0x7f900fedc530, iov_len = 4324039}, {iov_base = 0x40, iov_len = 184129542946817}, {
            iov_base = 0x7f900fedc5b8, iov_len = 140256719259088}}
        log_str = 0xffff0000
        cur = 0x24e9b50
#12 0x000000000041fd5f in udp_listener_incoming (fd=6, p=0x24e86a0, x=0) at udp_listener.c:52
        cb = 0x24e86a0
        sin = {sin6_family = 10, sin6_port = 30631, sin6_flowinfo = 0, sin6_addr = {__in6_u = {
              __u6_addr8 = "\000\000\000\000\000\000\000\000\000\000\377\377\177\000\000\001", __u6_addr16 = {0, 0, 0, 0, 0, 65535, 
                127, 256}, __u6_addr32 = {0, 0, 4294901760, 16777343}}}, sin6_scope_id = 0}
        sin_len = 28
        len = 1896
        buf = "19066_13\000d3:sdp1638:v=0\r\no=- 5427046385408022074 3 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS C1yO3MBdwjtpVn2vBECEbjs25npSFvQuwwUh\r\nm=audio 46656 RTP/SAVPF 124 0 8 101\r\nc=IN IP4 192.168.10.160"...
        addr = "127.0.0.1:42871", '\000' <repeats 48 times>
        str = {s = 0x7f900fedc610 "19066_13", len = 1896}
#13 0x00000000004101ae in poller_poll (p=0x24e6d60, timeout=100) at poller.c:348
        ret = 1
        i = 0
        it = 0x24cb640
        evs = {{events = 1, data = {ptr = 0x6, fd = 6, u32 = 6, u64 = 6}}, {events = 1, data = {ptr = 0x18, fd = 24, u32 = 24, 
              u64 = 24}}, {events = 1, data = {ptr = 0xb, fd = 11, u32 = 11, u64 = 11}}, {events = 1, data = {ptr = 0xc, fd = 12, 
              u32 = 12, u64 = 12}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}} <repeats 82 times>, {events = 0, 
            data = {ptr = 0xfeecac000000000, fd = 0, u32 = 0, u64 = 1148077881008586752}}, {events = 32656, data = {
              ptr = 0xffff806ff0113541, fd = -267307711, u32 = 4027659585, u64 = 18446603816990225729}}, {events = 267307711, 
            data = {ptr = 0x7f90, fd = 32656, u32 = 32656, u64 = 32656}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, 
              u64 = 0}}, {events = 1056, data = {ptr = 0xf01134d100000000, fd = 0, u32 = 0, u64 = 17298665715959595008}}, {
            events = 4294934639, data = {ptr = 0x43, fd = 67, u32 = 67, u64 = 67}}, {events = 16, data = {ptr = 0x4000000000, 
              fd = 0, u32 = 0, u64 = 274877906944}}, {events = 0, data = {ptr = 0x7f900feecb30, fd = 267307824, u32 = 267307824, 
              u64 = 140256719326000}}, {events = 2, data = {ptr = 0x800000000, fd = 0, u32 = 0, u64 = 34359738368}}, {events = 93, 
            data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x6e00000000, fd = 0, u32 = 0, 
              u64 = 472446402560}}, {events = 119, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 267307823, data = {
              ptr = 0x100007f90, fd = 32656, u32 = 32656, u64 = 4294999952}}, {events = 0, data = {ptr = 0x20000, fd = 131072, 
              u32 = 131072, u64 = 131072}}, {events = 4096, data = {ptr = 0xfeecb4f00000000, fd = 0, u32 = 0, 
              u64 = 1148078495188910080}}, {events = 32656, data = {ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 131072, data = {
              ptr = 0x100000000000, fd = 0, u32 = 0, u64 = 17592186044416}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, 
              u64 = 0}}, {events = 0, data = {ptr = 0x1a0000000000, fd = 0, u32 = 0, u64 = 28587302322176}}, {events = 32656, 
            data = {ptr = 0x7f90000019f0, fd = 6640, u32 = 6640, u64 = 140256452024816}}, {events = 512, data = {ptr = 0x2000000000, 
              fd = 0, u32 = 0, u64 = 137438953472}}, {events = 32656, data = {ptr = 0x26, fd = 38, u32 = 38, u64 = 38}}, {
            events = 51, data = {ptr = 0x15f02f8f00000000, fd = 0, u32 = 0, u64 = 1580815760433872896}}, {events = 32656, data = {
              ptr = 0x200, fd = 512, u32 = 512, u64 = 512}}, {events = 32, data = {ptr = 0x1f000007f90, fd = 32656, u32 = 32656, 
              u64 = 2130303811472}}, {events = 0, data = {ptr = 0x20, fd = 32, u32 = 32, u64 = 32}}, {events = 38, data = {
              ptr = 0x15f0482400000000, fd = 0, u32 = 0, u64 = 1580842788663066624}}, {events = 32656, data = {ptr = 0x7f900feecbf8, 
              fd = 267308024, u32 = 267308024, u64 = 140256719326200}}, {events = 8, data = {ptr = 0x20000000000, fd = 0, u32 = 0, 
              u64 = 2199023255552}}, {events = 0, data = {ptr = 0x7f9015f06472 <__malloc_trim+386>, fd = 368075890, u32 = 368075890, 
              u64 = 140256820094066}}, {events = 32, data = {ptr = 0x175350be00000000, fd = 0, u32 = 0, u64 = 1680775862913335296}}, 
          {events = 32656, data = {ptr = 0x7f90000008c0, fd = 2240, u32 = 2240, u64 = 140256452020416}}, {events = 6656, data = {
              ptr = 0x8c000007f90, fd = 32656, u32 = 32656, u64 = 9620726775696}}, {events = 32656, data = {ptr = 0x18, fd = 24, 
              u32 = 24, u64 = 24}}, {events = 2272, data = {ptr = 0x175a49b100007f90, fd = 32656, u32 = 32656, 
              u64 = 1682738435334373264}}, {events = 32656, data = {ptr = 0x20, fd = 32, u32 = 32, u64 = 32}}, {events = 391636797, 
            data = {ptr = 0x8d000007f90, fd = 32656, u32 = 32656, u64 = 9689446252432}}, {events = 32656, data = {
              ptr = 0x7f9008001c80, fd = 134225024, u32 = 134225024, u64 = 140256586243200}}, {events = 16, data = {
              ptr = 0x1b6000000000, fd = 0, u32 = 0, u64 = 30099130810368}}, {events = 32656, data = {ptr = 0x0, fd = 0, u32 = 0, 
              u64 = 0}}, {events = 38579488, data = {ptr = 0x80014b000000000, fd = 0, u32 = 0, u64 = 576483498450223104}}, {
            events = 32656, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}}
        ev = 0x7f900feec670
        e = {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}
#14 0x0000000000410764 in poller_loop (d=0x24e6d60) at poller.c:502
        p = 0x24e6d60
#15 0x0000000000410c30 in thread_detach_func (d=0x24e8a50) at aux.c:143
        dt = 0x24e8a50
        t = 0x7f90080014b0
#16 0x00007f901624f182 in start_thread (arg=0x7f900feed700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f900feed700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140256719329024, -2640881265775207578, 0, 0, 140256719329728, 140256719329024, 
                2628320589327899494, 2628299202121571174}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {
              prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#17 0x00007f9015f7c00d in __qfcvt_r (value=0, ndigit=0, decpt=0x7f900feed9c0, sign=0x0, buf=0x0, len=0) at efgcvt_r.c:100
        n = <optimized out>
        i = <optimized out>
        left = 267310848
#18 0x0000000000000000 in ?? ()
No symbol table info available.
(gdb) quit
```

**Comment by krieger-od** [comment]
I guess this is related to disabling/enabling video during the call, with UPDATE request.

**Comment by krieger-od** [comment]
Thanks a lot!
